//! Vendor-path detection reproducing `src-d/enry` v2.1.0's `IsVendor`.
//!
//! enry classification is decision-parity-critical (DESIGN §2.6): the set of
//! files included in an analysis selects which bytes appear in machine reports,
//! which `tests/compat` pins against the reference binary. We therefore
//! vendor the **same** regex table enry embeds in its generated
//! `data/vendor.go` (itself extracted from GitHub Linguist's `vendor.yml`),
//! instead of swapping to a different detector.
//!
//! ## Data source
//!
//! The pattern list is produced by [`build.rs`](../build.rs.html) into
//! `$OUT_DIR/vendor_patterns.rs` as `GENERATED_VENDOR_PATTERNS`, extracted from
//! the pinned enry source (`github.com/src-d/enry/v2@v2.1.0/data/vendor.go`).
//! When that source is unavailable at build time the generated slice is empty
//! and we fall back to the checked-in [`crate::vendor_data::VENDOR_PATTERNS`]
//! transcription. Both lists are byte-identical to the upstream `VendorMatchers`
//! sources, in upstream order. See [`vendor_patterns`].
//!
//! ## How enry matches
//!
//! enry's `IsVendor` is `data.VendorMatchers.Match(path)` where `VendorMatchers`
//! is `substring.Or(substring.Regexp(p1), substring.Regexp(p2), …)`: each
//! pattern is searched **unanchored** (it may match anywhere in the path), and
//! `Or` returns true if ANY matcher matches. We reproduce this as a single
//! combined [`Regex`] formed by `(?:p1)|(?:p2)|…` searched unanchored —
//! equivalent because per-pattern anchors (`^`, `$`) are preserved inside each
//! `(?:…)` group and the alternation matches iff any branch matches somewhere
//! in the path.
//!
//! ## Engine note
//!
//! enry's regexp engine and the Rust `regex` crate are both RE2-lineage
//! (linear-time, no backreferences). The `vendor.yml` patterns use only
//! features common to both (character classes, alternation, anchors,
//! `?`/`*`/`+`, groups, lazy `*?`), so the match set is identical.

use std::sync::LazyLock;

use regex::Regex;

use crate::vendor_data;

// Generated by build.rs from the pinned enry `data/vendor.go`. Defines
// `pub static GENERATED_VENDOR_PATTERNS: &[&str]`. Empty when the enry source
// was unavailable at build time (then we use the checked-in fallback below).
include!(concat!(env!("OUT_DIR"), "/vendor_patterns.rs"));

/// Returns the active vendor-pattern table: the build-time-generated list
/// extracted from the real enry source when available, otherwise the checked-in
/// [`vendor_data::VENDOR_PATTERNS`] fallback. Both are byte-identical to enry
/// v2.1.0's `VendorMatchers`, so the choice does not change behavior — it only
/// determines whether parity is *verified at build time* or *asserted against
/// the checked-in reference*.
fn vendor_patterns() -> &'static [&'static str] {
    if GENERATED_VENDOR_PATTERNS.is_empty() {
        vendor_data::VENDOR_PATTERNS
    } else {
        GENERATED_VENDOR_PATTERNS
    }
}

/// Combined `VendorMatchers` alternation, compiled once.
///
/// enry searches each path against the union of all patterns with an unanchored
/// match. Wrapping every pattern in a non-capturing group preserves per-pattern
/// anchors (`^`, `$`) while letting the alternation as a whole match anywhere.
static VENDOR_RE: LazyLock<Regex> = LazyLock::new(|| {
    let joined = vendor_patterns()
        .iter()
        .map(|p| format!("(?:{p})"))
        .collect::<Vec<_>>()
        .join("|");
    Regex::new(&joined).expect("enry vendor patterns must compile")
});

/// Reports whether `path` is a vendored / third-party path, reproducing
/// `enry.IsVendor`.
///
/// The match is unanchored (the combined pattern may match any substring of
/// `path`), exactly as enry searches each `substring.Regexp` matcher in
/// `VendorMatchers`.
///
/// # Examples
///
/// ```
/// use cf_pathfilter::is_vendor;
///
/// assert!(is_vendor("vendor/github.com/foo/bar.go"));
/// assert!(is_vendor("node_modules/lodash/index.js"));
/// // Unanchored: a vendor dir nested anywhere still matches.
/// assert!(is_vendor("pkg/internal/vendor/foo/bar.go"));
/// assert!(!is_vendor("internal/server/handler.go"));
/// ```
#[must_use]
pub fn is_vendor(path: &str) -> bool {
    VENDOR_RE.is_match(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn combined_regex_compiles() {
        // Forces lazy compilation; a panic here means a pattern is invalid for
        // the Rust `regex` engine and must be reconciled with enry's source.
        assert!(!is_vendor("definitely/a/normal/file.go"));
    }

    #[test]
    fn matches_canonical_vendor_dirs() {
        assert!(is_vendor("vendor/github.com/foo/bar.go"));
        assert!(is_vendor("node_modules/lodash/index.js"));
        assert!(is_vendor("bower_components/jquery/jquery.js"));
        assert!(is_vendor("Godeps/_workspace/src/foo/bar.go"));
    }

    #[test]
    fn matches_nested_vendor_dirs() {
        assert!(is_vendor("pkg/internal/vendor/foo/bar.go"));
        assert!(is_vendor("packages/app/node_modules/react/index.js"));
    }

    #[test]
    fn rejects_normal_source() {
        assert!(!is_vendor("main.go"));
        assert!(!is_vendor("internal/server/handler.go"));
        assert!(!is_vendor("src/index.ts"));
        assert!(!is_vendor(""));
    }

    /// Spot-checks several enry patterns beyond the canonical vendor dirs, to
    /// catch table truncation or ordering drift.
    #[test]
    fn matches_assorted_enry_patterns() {
        assert!(is_vendor("testdata/sample.json")); // (^|/)testdata/
        assert!(is_vendor("app.min.js")); //          (\.|-)min\.(js|css)$
        assert!(is_vendor("Jenkinsfile")); //         ^Jenkinsfile$
        assert!(is_vendor("dist/app.js")); //         (^|/)dist/
        assert!(is_vendor("3rd-party/lib.c")); //     (3rd|[Tt]hird)[-_]?[Pp]arty/
        assert!(is_vendor("foo/bar.d.ts")); //        (.*?)\.d\.ts$
    }

    /// When the enry source was present at build time, the generated table must
    /// match the checked-in fallback reference byte-for-byte and in order.
    /// (Skipped automatically on offline builds where the generated list is
    /// empty.) This is the parity assertion referenced by `build.rs`.
    #[test]
    fn vendor_patterns_match_enry_source() {
        if GENERATED_VENDOR_PATTERNS.is_empty() {
            // Offline build: nothing extracted from enry; fallback is the only
            // reference, so there is nothing to cross-check.
            return;
        }
        assert_eq!(
            GENERATED_VENDOR_PATTERNS,
            vendor_data::VENDOR_PATTERNS,
            "generated enry vendor table diverged from the checked-in reference; \
             update src/vendor_data.rs to match the pinned enry data/vendor.go"
        );
    }
}
