package pathfilter

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestIsExcluded_VendorPaths(t *testing.T) {
	t.Parallel()

	f := New()

	// enry.IsVendor covers these patterns.
	assert.True(t, f.IsExcluded("vendor/github.com/foo/bar.go"))
	assert.True(t, f.IsExcluded("node_modules/lodash/index.js"))
	assert.True(t, f.IsExcluded("bower_components/jquery/jquery.js"))
	assert.True(t, f.IsExcluded("Godeps/_workspace/src/foo/bar.go"))
}

func TestIsExcluded_NestedVendorPaths(t *testing.T) {
	t.Parallel()

	f := New()

	assert.True(t, f.IsExcluded("pkg/internal/vendor/foo/bar.go"))
	assert.True(t, f.IsExcluded("packages/app/node_modules/react/index.js"))
}

func TestIsExcluded_GeneratedSuffixes(t *testing.T) {
	t.Parallel()

	f := New()

	assert.True(t, f.IsExcluded("api/types.pb.go"))
	assert.True(t, f.IsExcluded("api/types.pb.gw.go"))
	assert.True(t, f.IsExcluded("pkg/foo.generated.go"))
	assert.True(t, f.IsExcluded("pkg/types.deepcopy.go"))
	assert.True(t, f.IsExcluded("pkg/status_string.go"))
	assert.True(t, f.IsExcluded("pkg/color_enumer.go"))
	assert.True(t, f.IsExcluded("pkg/model_easyjson.go"))
	assert.True(t, f.IsExcluded("proto/service_pb2.py"))
	assert.True(t, f.IsExcluded("proto/service_pb2_grpc.py"))
	assert.True(t, f.IsExcluded("proto/service.pb.cc"))
	assert.True(t, f.IsExcluded("proto/service.pb.h"))
	assert.True(t, f.IsExcluded("proto/service.grpc.pb.cc"))
	assert.True(t, f.IsExcluded("proto/service.grpc.pb.h"))
	assert.True(t, f.IsExcluded("static/app.min.js"))
	assert.True(t, f.IsExcluded("static/style.min.css"))
	assert.True(t, f.IsExcluded("dist/app.bundle.js"))
}

func TestIsExcluded_GeneratedFilenamePrefixes(t *testing.T) {
	t.Parallel()

	f := New()

	assert.True(t, f.IsExcluded("pkg/api/zz_generated_deepcopy.go"))
	assert.True(t, f.IsExcluded("pkg/api/zz_generated.defaults.go"))
	assert.True(t, f.IsExcluded("pkg/mock_service.go"))
	assert.True(t, f.IsExcluded("pkg/fake_client.go"))
	assert.True(t, f.IsExcluded("internal/wire_gen.go"))
}

func TestIsExcluded_NonExcludedPaths(t *testing.T) {
	t.Parallel()

	f := New()

	assert.False(t, f.IsExcluded("main.go"))
	assert.False(t, f.IsExcluded("internal/server/handler.go"))
	assert.False(t, f.IsExcluded("pkg/api/types.go"))
	assert.False(t, f.IsExcluded("cmd/app/main.go"))
	assert.False(t, f.IsExcluded("src/index.ts"))
	assert.False(t, f.IsExcluded("lib/utils.py"))
	assert.False(t, f.IsExcluded("test/integration_test.go"))
}

func TestIsExcluded_EmptyPath(t *testing.T) {
	t.Parallel()

	f := New()

	assert.False(t, f.IsExcluded(""))
}

func TestIsExcludedWithContent_GeneratedFile(t *testing.T) {
	t.Parallel()

	f := New()

	tests := []struct {
		name     string
		content  string
		excluded bool
	}{
		{"Code generated header", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n", true},
		{"DO NOT EDIT header", "// DO NOT EDIT. Auto-generated.\npackage api\n", true},
		{"AUTO-GENERATED header", "// AUTO-GENERATED FILE\npackage api\n", true},
		{"auto-generated header", "// auto-generated by tool\npackage api\n", true},
		{"Autogenerated header", "/* Autogenerated */\npackage api\n", true},
		{"@generated annotation", "// @generated\npackage api\n", true},
		{"Normal code", "package api\n\ntype Foo struct{}\n", false},
	}

	for _, tc := range tests {
		assert.Equal(t, tc.excluded, f.IsExcludedWithContent("pkg/api/types.go", []byte(tc.content)), tc.name)
	}
}

func TestIsExcludedWithContent_NilContent(t *testing.T) {
	t.Parallel()

	f := New()

	// With nil content, falls back to path-only check.
	assert.True(t, f.IsExcludedWithContent("vendor/foo/bar.go", nil))
	assert.False(t, f.IsExcludedWithContent("main.go", nil))
}

func TestIsGeneratedPath(t *testing.T) {
	t.Parallel()

	f := New()

	// Generated suffixes should match.
	assert.True(t, f.IsGeneratedPath("api/types.pb.go"))
	assert.True(t, f.IsGeneratedPath("static/app.min.js"))

	// Generated filename prefixes should match.
	assert.True(t, f.IsGeneratedPath("pkg/zz_generated_deepcopy.go"))
	assert.True(t, f.IsGeneratedPath("pkg/mock_service.go"))

	// Vendor paths should NOT match (IsGeneratedPath skips enry.IsVendor).
	assert.False(t, f.IsGeneratedPath("vendor/github.com/foo/bar.go"))
	assert.False(t, f.IsGeneratedPath("node_modules/lodash/index.js"))

	// Normal source files should NOT match.
	assert.False(t, f.IsGeneratedPath("main.go"))
	assert.False(t, f.IsGeneratedPath("internal/server/handler.go"))
}

func TestIsGeneratedContent(t *testing.T) {
	t.Parallel()

	f := New()

	assert.True(t, f.IsGeneratedContent([]byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n")))
	assert.True(t, f.IsGeneratedContent([]byte("// @generated\npackage api\n")))
	assert.True(t, f.IsGeneratedContent([]byte("// AUTO-GENERATED FILE\npackage api\n")))

	// Normal code should NOT match.
	assert.False(t, f.IsGeneratedContent([]byte("package api\n\ntype Foo struct{}\n")))

	// Nil/empty content should NOT match.
	assert.False(t, f.IsGeneratedContent(nil))
	assert.False(t, f.IsGeneratedContent([]byte{}))
}

func TestNew_DefaultRulesApplied(t *testing.T) {
	t.Parallel()

	f := New()

	// Verify default suffixes and filename prefixes are populated.
	assert.NotEmpty(t, f.suffixes)
	assert.NotEmpty(t, f.filenamePfx)
}
