// Package pathfilter excludes vendor, third-party, and generated files from
// analysis. It uses enry as the foundation for vendor detection and adds
// supplementary generated-file name patterns that enry does not cover.
//
// A Filter is immutable after construction and safe for concurrent use.
package pathfilter

import (
	"bytes"
	"path"
	"strings"

	"github.com/src-d/enry/v2"
)

// Filter determines whether a file should be excluded from analysis.
// It combines enry vendor detection with generated-file name patterns.
type Filter struct {
	suffixes    []string // file suffix matches (e.g., ".pb.go").
	filenamePfx []string // filename prefix matches (e.g., "zz_generated").
}

// Option configures a Filter.
type Option func(*Filter)

// New creates a Filter. With no options, it uses DefaultRules.
func New(opts ...Option) *Filter {
	f := &Filter{}

	for _, opt := range opts {
		opt(f)
	}

	if len(f.suffixes) == 0 && len(f.filenamePfx) == 0 {
		DefaultRules()(f)
	}

	return f
}

// IsExcluded reports whether the given path should be excluded from analysis.
// This performs path-only checks (no file content needed).
func (f *Filter) IsExcluded(filePath string) bool {
	if enry.IsVendor(filePath) {
		return true
	}

	for _, s := range f.suffixes {
		if strings.HasSuffix(filePath, s) {
			return true
		}
	}

	if len(f.filenamePfx) > 0 {
		base := path.Base(filePath)
		for _, p := range f.filenamePfx {
			if strings.HasPrefix(base, p) {
				return true
			}
		}
	}

	return false
}

// IsExcludedWithContent performs path-only checks first, then inspects the
// first line of content for generated-file markers (e.g., "DO NOT EDIT").
func (f *Filter) IsExcludedWithContent(filePath string, content []byte) bool {
	if f.IsExcluded(filePath) {
		return true
	}

	return len(content) > 0 && hasGeneratedMarker(content)
}

// generatedMarkers are byte patterns found in the first line or header comment
// of generated files. Checking a small prefix is cheap and avoids parsing.
var generatedMarkers = [][]byte{
	[]byte("DO NOT EDIT"),
	[]byte("Code generated"),
	[]byte("AUTO-GENERATED"),
	[]byte("auto-generated"),
	[]byte("Autogenerated"),
	[]byte("@generated"),
}

// generatedMarkerScanLimit is how many bytes of the file header to scan for
// generated markers. Keeps the check fast even for large files.
const generatedMarkerScanLimit = 512

// IsGeneratedPath checks suffix and filename-prefix rules only (no enry.IsVendor).
// This allows callers to distinguish vendor files from generated files.
func (f *Filter) IsGeneratedPath(filePath string) bool {
	for _, s := range f.suffixes {
		if strings.HasSuffix(filePath, s) {
			return true
		}
	}

	if len(f.filenamePfx) > 0 {
		base := path.Base(filePath)
		for _, p := range f.filenamePfx {
			if strings.HasPrefix(base, p) {
				return true
			}
		}
	}

	return false
}

// IsGeneratedContent checks file content for generated-file header markers.
func (f *Filter) IsGeneratedContent(content []byte) bool {
	return len(content) > 0 && hasGeneratedMarker(content)
}

// hasGeneratedMarker checks the file header for common generated-file markers.
func hasGeneratedMarker(content []byte) bool {
	header := content
	if len(header) > generatedMarkerScanLimit {
		header = header[:generatedMarkerScanLimit]
	}

	for _, marker := range generatedMarkers {
		if bytes.Contains(header, marker) {
			return true
		}
	}

	return false
}

// DefaultRules returns an Option that populates the filter with built-in
// generated-file patterns. Vendor detection is always handled by enry.
func DefaultRules() Option {
	return func(f *Filter) {
		f.suffixes = defaultSuffixes
		f.filenamePfx = defaultFilenamePrefixes
	}
}

// defaultSuffixes are file suffixes indicating generated code that should not
// be structurally analyzed. These produce noise in UAST-based metrics and their
// parse trees consume excessive tree-sitter memory.
var defaultSuffixes = []string{
	// Go generated files.
	".pb.go",
	".pb.gw.go",
	".generated.go",
	".deepcopy.go",
	"_string.go",   // stringer output.
	"_enumer.go",   // enumer output.
	"_easyjson.go", // easyjson output.
	// Protocol buffer outputs for other languages.
	"_pb2.py",
	"_pb2_grpc.py",
	".pb.cc",
	".pb.h",
	".grpc.pb.cc",
	".grpc.pb.h",
	// Minified / bundled assets.
	".min.js",
	".min.css",
	".bundle.js",
}

// defaultFilenamePrefixes are filename prefixes (matched against [path.Base])
// indicating generated code.
var defaultFilenamePrefixes = []string{
	"zz_generated", // Kubernetes code-generator output.
	"mock_",        // mockgen output.
	"fake_",        // counterfeiter output.
	"wire_gen",     // Google Wire.
}
