//! Build script: regenerates the embedded UAST mapping table.
//!
//! This is the Rust port of the Go generator `tools/uastmapsgen/gen_uastmaps.py`
//! (which produced `pkg/uast/embedded_mappings.gen.go`). Rather than
//! hand-translating that ~33 MB generated artifact, we reproduce the generator:
//! glob `mappings/*.uastmap`, sort the paths exactly as Python's
//! `sorted(glob.glob(...))` does, derive each language name as the filename with
//! the `.uastmap` extension stripped, and emit `$OUT_DIR/mappings.gen.rs`
//! containing a static `[(name, &'static str)]` table whose content is embedded
//! via `include_str!`.
//!
//! `include_str!` is the direct analogue of Go's string-literal embedding: the
//! embedded bytes are identical to the on-disk `.uastmap` files, which are
//! themselves byte-identical to the files the Go generator reads from
//! `pkg/uast/uastmaps`. The Go generator's 60-char chunking is purely cosmetic
//! source formatting and does not affect the runtime string value, so there is
//! nothing to reproduce there.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let mappings_dir = Path::new(&manifest_dir).join("mappings");

    // Re-run if the directory or this script changes.
    println!("cargo:rerun-if-changed=mappings");
    println!("cargo:rerun-if-changed=build.rs");

    // Collect every `*.uastmap` file as (language_name, absolute_path).
    //
    // The Go generator keys its `map[string]string` by `basename - ".uastmap"`;
    // we use the same stem. Map iteration order is irrelevant in Go (maps are
    // unordered) and the only order-sensitive Go consumer
    // (`SupportedLanguages`) sorts, so we sort here for determinism — matching
    // Python's `sorted(glob.glob(...))`.
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    let read_dir = fs::read_dir(&mappings_dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", mappings_dir.display()));
    for entry in read_dir {
        let entry = entry.expect("failed to read mappings dir entry");
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("uastmap") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("non-utf8 mapping filename")
            .to_string();
        println!("cargo:rerun-if-changed={}", path.display());
        let abs = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("canonicalize {}: {e}", path.display()));
        entries.push((stem, abs));
    }

    if entries.is_empty() {
        // Mirror the Go generator's hard failure on an empty mappings dir.
        panic!(
            "no .uastmap files found in {} (vendor them from pkg/uast/uastmaps)",
            mappings_dir.display()
        );
    }

    // Sort by language name (UTF-8 byte order), matching `sort.Strings` on the
    // Go side and `sorted()` in the Python generator.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs (port of tools/uastmapsgen/gen_uastmaps.py). DO NOT EDIT.\n",
    );
    out.push_str("// Regenerate by editing files under `mappings/` and rebuilding.\n\n");
    out.push_str("/// Number of embedded UAST mappings.\n");
    out.push_str(&format!(
        "pub(crate) const MAPPING_COUNT: usize = {};\n\n",
        entries.len()
    ));
    out.push_str("/// Embedded UAST mappings as `(name, content)` pairs, sorted by name.\n");
    out.push_str("/// `content` is embedded at compile time and is byte-identical to the\n");
    out.push_str("/// corresponding `mappings/<name>.uastmap` file.\n");
    out.push_str(&format!(
        "pub(crate) static MAPPINGS: [(&str, &str); {}] = [\n",
        entries.len()
    ));
    for (stem, abs) in &entries {
        out.push_str(&format!(
            "    ({stem:?}, include_str!({:?})),\n",
            abs.display().to_string()
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("mappings.gen.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
