# golangci-lint v2 strict configuration for Codefang
# See https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly
  go: "1.24"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - linter
    - file
  show-stats: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Sumatoshi-tech/codefang

linters:
  # Enable ALL linters, only disable what's truly inapplicable.
  default: all
  disable:
    # --- Deprecated ---
    - wsl # Deprecated in v2; replaced by wsl_v5

    # --- Framework/DB-specific: not used in this project ---
    - arangolint # ArangoDB
    - ginkgolinter # Ginkgo testing framework
    - loggercheck # logr/klog/zap structured loggers
    - promlinter # Prometheus metrics naming
    - protogetter # Protobuf getters
    - rowserrcheck # database/sql rows.Err()
    - spancheck # OpenTelemetry spans
    - sqlclosecheck # database/sql Close()
    - zerologlint # zerolog

    # --- Too noisy for this codebase ---
    - exhaustruct # Go idiom is zero-value initialization; this linter fights the language
    - gochecknoglobals # No config options; all 35 globals are legitimate (ldflags, sync.Pool, registries, lookup tables)
    - testpackage # All 58 test files intentionally use white-box testing for internal implementation

    # --- Conflicting linters ---
    - whitespace # Conflicts with wsl_v5: multi-func requires blank lines that wsl_v5 forbids
    - nonamedreturns # Conflicts with gocritic(unnamedResult): forbids named returns that gocritic requires for clarity

  settings:
    cyclop:
      max-complexity: 15
      package-average: 7.0

    depguard:
      rules:
        "deprecated":
          files: ["$all"]
          deny:
            - pkg: github.com/golang/protobuf
              desc: "Use google.golang.org/protobuf instead"
            - pkg: github.com/satori/go.uuid
              desc: "Use github.com/google/uuid instead"
            - pkg: github.com/gofrs/uuid$
              desc: "Use github.com/gofrs/uuid/v5 or later"
        "non-test":
          files: ["!$test"]
          deny:
            - pkg: math/rand$
              desc: "Use math/rand/v2 instead"

    dupl:
      threshold: 100

    embeddedstructfieldcheck:
      forbid-mutex: true

    errcheck:
      check-type-assertions: true
      check-blank: true

    errorlint:
      errorf: true
      asserts: true
      comparison: true
      errorf-multi: true

    exhaustive:
      check: [switch, map]
      default-signifies-exhaustive: false

    exhaustruct:
      exclude:
        # Standard library
        - ^net/http\.(Client|Cookie|Request|Response|Server|Transport)$
        - ^net/url\.URL$
        - ^os/exec\.Cmd$
        - ^reflect\.StructField$
        # Third-party
        - ^github\.com/spf13/cobra\.(Command|CompletionOptions)$
        - ^github\.com/stretchr/testify/mock\.Mock$
        - ^golang\.org/x/tools/go/analysis\.Analyzer$
        - ^gopkg\.in/yaml\.v3\.Node$
        - ^github\.com/go-git/go-git
        - ^github\.com/tliron/glsp
        - ^github\.com/sergi/go-diff
        # Project-internal: analyzers and plumbing (zero values are intentional by design)
        - ^github\.com/Sumatoshi-tech/codefang/pkg/analyzers/
        - ^github\.com/Sumatoshi-tech/codefang/pkg/uast/
        - ^github\.com/Sumatoshi-tech/codefang/pkg/importmodel\.
        - ^github\.com/Sumatoshi-tech/codefang/pkg/plumbing\.
        - ^github\.com/Sumatoshi-tech/codefang/cmd/
      allow-empty-returns: true

    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: "Use log/slog for structured output instead of fmt.Print"
          pkg: ^fmt$
      analyze-types: true

    funcorder:
      struct-method: false

    funlen:
      lines: 80
      statements: 40
      ignore-comments: true

    gochecksumtype:
      default-signifies-exhaustive: false

    gocognit:
      min-complexity: 15

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - rangeValCopy
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    gocyclo:
      min-complexity: 15

    godoclint:
      enable:
        - no-unused-link
        - require-stdlib-doclink

    godot:
      scope: all
      # capital: true triggers index-out-of-range panic in godot on some comments (e.g. in gitlib).
      capital: false

    gomoddirectives:
      replace-local: true

    gosec:
      excludes:
        - G115 # Integer overflow conversion - values are bounded by repository/file sizes
        - G204 # Subprocess launched with variable - needed for command execution
        - G401 # Use of weak cryptographic primitive (SHA1) - used for content fingerprinting, not security
        - G505 # Import of crypto/sha1 - used for content fingerprinting, not security
      severity: medium
      confidence: medium

    govet:
      enable-all: true
      disable:
        - fieldalignment # conflicts with embeddedstructfieldcheck
      settings:
        shadow:
          strict: true

    iface:
      enable: [identical, unused, opaque]

    inamedparam:
      skip-single-param: true

    interfacebloat:
      max: 10

    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
        - github\.com/go-echarts/go-echarts/v2/components\.Charter
        - github\.com/Sumatoshi-tech/codefang/pkg/analyzers/analyze\.PlumbingSnapshot
        - github\.com/Sumatoshi-tech/codefang/pkg/analyzers/analyze\.ResultAggregator
        - github\.com/Sumatoshi-tech/codefang/pkg/analyzers/analyze\.AnalysisVisitor
        - github\.com/Sumatoshi-tech/codefang/pkg/analyzers/analyze\.ReportSection
        - github\.com/Sumatoshi-tech/codefang/pkg/analyzers/analyze\.StaticAnalyzer
        - github\.com/Sumatoshi-tech/codefang/pkg/uast/pkg/node\.DSLNode
        - github\.com/Sumatoshi-tech/codefang/pkg/uast/pkg/node\.FieldProcessor
        - github\.com/Sumatoshi-tech/codefang/pkg/uast/pkg/node\.ValueExtractor
        - github\.com/xeipuuv/gojsonschema\.JSONLoader
        - go\.opentelemetry\.io/otel/.*

    lll:
      line-length: 140
      tab-width: 4

    maintidx:
      under: 20

    misspell:
      locale: US

    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - strconv.Format*
        - strconv.Parse*

    nakedret:
      max-func-lines: 0

    nestif:
      min-complexity: 4

    nilnil:
      checked-types: [ptr, func, iface, map, chan]

    nolintlint:
      allow-no-explanation: [funlen, gocognit, lll]
      require-explanation: true
      require-specific: true

    nonamedreturns:
      report-error-in-defer: true

    perfsprint:
      strconcat: false

    reassign:
      patterns: [".*"]

    revive:
      rules:
        - name: exported
          arguments: ["checkPrivateReceivers"]
        - name: var-naming
        - name: package-comments
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: range
        - name: context-keys-type
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: unexported-return
        - name: blank-imports
        - name: dot-imports
        - name: context-as-argument
        - name: early-return
        - name: unnecessary-stmt
        - name: receiver-naming
        - name: superfluous-else
        - name: confusing-naming
        - name: modifies-value-receiver
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: waitgroup-by-value
        - name: atomic
        - name: empty-block
        - name: bool-literal-in-expr
        - name: constant-logical-expr
        - name: identical-branches
        - name: modifies-parameter
        - name: string-of-int
        - name: defer
          arguments:
            - [
                "call-chain",
                "loop",
                "method-call",
                "recover",
                "immediate-recover",
                "return",
              ]
        - name: range-val-address
        - name: range-val-in-closure
        - name: get-return
        - name: string-format

    sloglint:
      no-global: all
      context: scope

    staticcheck:
      checks: [all]

    tagalign:
      align: true
      sort: true

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: camel

    testifylint:
      enable-all: true

    unconvert:
      fast-math: true
      safe: true

    unparam:
      check-exported: false

    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true

    usetesting:
      os-temp-dir: true

    varnamelen:
      max-distance: 6
      min-name-length: 1
      check-receiver: false
      check-return: true
      check-type-param: true
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-names:
        - ok
        - err
        - id
        - wg
        - mu
        - db
        - tx
        - fn
        - fs
        - ip
        - tt
        - tc
        - tb
        - sb
        - fd
        - rw
        - kv
        - op
        - ch
        - ln
        - cb
        - ts
        - tp
        - rc
        - dd
        - da
        - si
        - gh
      ignore-decls:
        - i int
        - j int
        - k int
        - n int
        - t testing.T
        - b testing.B
        - f testing.F
        - e error
        - w io.Writer
        - r io.Reader
        - s string

    whitespace:
      multi-if: true
      multi-func: true

    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
      ignore-package-globs:
        - github.com/Sumatoshi-tech/codefang/*

    wsl_v5: {}

  exclusions:
    warn-unused: true
    presets:
      - std-error-handling
      - common-false-positives
    # Generated PEG parser files and embedded mappings - machine-generated, exclude from all linting.
    paths:
      - '\.peg\.go$'
      - 'pkg/uast/embedded_mappings\.gen\.go$'
    rules:
      # Pipeline processing involves inherently complex batch/retry/error logic.
      - path: pkg/framework/(blob|diff)_pipeline\.go
        linters: [funlen, gocognit, gocyclo, cyclop, nestif]

      # CGO bridge functions are long due to C interop boilerplate and result conversion.
      - path: pkg/gitlib/cgo_bridge\.go
        linters: [funlen, gocognit, gocyclo, cyclop]

      # Worker handle() dispatches multiple request types in a single function.
      - path: pkg/gitlib/worker\.go
        linters: [funlen, gocognit, gocyclo, cyclop, nestif]

      # Burndown history analysis has inherently complex change-tracking logic.
      - path: pkg/analyzers/burndown/history\.go
        linters: [funlen, gocognit]

      # RB-tree insertion with rebalancing is inherently complex.
      - path: pkg/rbtree/rbtree\.go
        linters: [gocognit]

      # CGO files: C code comments in import "C" blocks can't end in periods;
      # nlreturn false-positives on C function calls (non-Go column offsets).
      - path: pkg/gitlib/cgo_bridge\.go
        linters: [godot, nlreturn]
      - path: pkg/uast/cgo_end_positions\.go
        linters: [godot]
      - path: pkg/uast/cgo_named_children_batch\.go
        linters: [godot]

      # CGO file: gocritic false positives on CGO-generated code (dupImport, dupSubExpr, underef).
      - path: pkg/gitlib/cgo_bridge\.go
        linters: [gocritic]

      # libgit2 callback signatures require error return; unparam reports always-nil.
      - path: pkg/gitlib/diff\.go
        text: "result 0 \\(error\\) is always nil|result 1 \\(error\\) is always nil"
        linters: [unparam]

      # Package-comment style exclusions for nolint/TODO lines.
      - text: 'package comment should be of the form ".+"'
        source: "// ?(nolint|TODO)"
        linters: [revive]
      - text: 'comment on exported \S+ \S+ should be of the form ".+"'
        source: "// ?(nolint|TODO)"
        linters: [revive, staticcheck]

      # DSL parser test contains long raw string literals (mapping DSL grammar) that cannot be broken.
      - path: pkg/uast/pkg/mapping/dsl_parser_test\.go
        linters: [lll]

      # LSP protocol requires nil (*Hover) response when no result is available.
      - path: pkg/uast/lsp/server\.go
        linters: [nilnil]

      # git2go callback returns nil function to skip hunk processing; library-defined signature.
      - path: pkg/gitlib/gitlib_test\.go
        linters: [nilnil]

      # DSL AST converter functions must return DSLNode to satisfy the nodeConverter function type.
      - path: pkg/uast/pkg/node/querydsl\.go
        linters: [iface]

      # Parallelizable is used via type assertions in runner.go, not as a parameter/return type.
      - path: pkg/analyzers/analyze/history\.go
        text: "Parallelizable"
        linters: [iface]

      # color.NoColor is the library-provided way to control colored output.
      - path: cmd/uast/validate\.go
        linters: [reassign]

      # Test files naturally have similar setup/assertion patterns and long test functions.
      - path: _test\.go
        linters: [dupl, funlen, gocognit, gocyclo, cyclop, nestif]

      # Test intentionally creates a blocked directory with restrictive then restored permissions.
      - path: pkg/analyzers/analyze/static_test\.go
        text: "G302"
        linters: [gosec]

      # findFunctions error return is always nil but needed for consistent internal API.
      - path: pkg/analyzers/cohesion/cohesion\.go
        text: findFunctions
        linters: [unparam]

      # Binary files silently skipped when CountLines fails; nil error return is intentional.
      - path: pkg/analyzers/burndown/history\.go
        linters: [nilerr]

      # Example functions are long due to inline UAST mapping definitions.
      - path: examples/
        linters: [funlen]

      # Build script template generation is inherently long but cannot be split.
      - path: tools/
        linters: [funlen]

      # Cross-function span lifecycle pattern; spancheck false positive.
      - path: pkg/observability/tracer_filter\.go
        linters: [spancheck]

      # Timeline is a core interface that legitimately needs 11 methods (Replace, Iterate, Len, Nodes,
      # Validate, CloneShallow, CloneDeep, Erase, Flatten, Reconstruct, MergeAdjacentSameValue).
      - path: pkg/burndown/timeline\.go
        linters: [interfacebloat]

      # NewTreapTimeline returns concrete *treapTimeline to satisfy ireturn/iface;
      # revive unexported-return conflicts with these linters.
      - path: pkg/burndown/timeline_treap\.go
        text: "unexported-return"
        linters: [revive]

      # Package names "metrics" and "version" conflict with stdlib but renaming would be disruptive.
      - path: pkg/metrics/
        text: "var-naming.*conflict"
        linters: [revive]
      - path: pkg/version/
        text: "var-naming.*conflict"
        linters: [revive]

      # Aggregator embedding is an intentional design pattern for method promotion.
      - path: pkg/analyzers/(comments|complexity|halstead)/aggregator\.go
        linters: [embeddedstructfieldcheck]

      # BaseReportSection embedding is standard Go pattern for partial interface implementation in tests.
      - path: pkg/analyzers/common/renderer/(json_test|renderer_test)\.go
        linters: [embeddedstructfieldcheck]

      # CGO init() is required to call C.cf_init() for library initialization.
      - path: pkg/gitlib/cgo_bridge\.go
        linters: [gochecknoinits]

      # testing.AllocsPerRun is incompatible with t.Parallel(); exclude paralleltest for this file.
      - path: pkg/uast/parser_dsl_test\.go
        text: "TestNodeType_FallbackInline_ZeroAllocs"
        linters: [paralleltest]

      # init() required to populate global registries used by ParseDSL/LowerDSL at package import time.
      - path: pkg/uast/pkg/node/(lowering|querydsl)\.go
        linters: [gochecknoinits]

      # Package name "common" is an established convention in this codebase for shared analyzer utilities.
      - path: pkg/analyzers/common/
        text: "var-naming"
        linters: [revive]

      # DSL parser switch statements intentionally handle only relevant pegRule cases.
      - path: pkg/uast/pkg/mapping/dsl_parser\.go
        linters: [exhaustive]

      # findGE/FindGE is an intentional private/public pair for RB-tree search.
      - path: pkg/rbtree/rbtree\.go
        text: "confusing-naming.*findGE"
        linters: [revive]
