# golangci-lint configuration for Codefang
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt # Code formatting
    - goimports # Import organization
    - govet # Go vet checks
    - errcheck # Unchecked error detection
    - staticcheck # Static analysis
    - gosimple # Simplification suggestions
    - unused # Unused code detection
    - ineffassign # Ineffectual assignments
    - misspell # Spelling errors
    - revive # Replacement for golint
    - gocyclo # Cyclomatic complexity
    - dupl # Code duplication
    - gosec # Security issues
    - unconvert # Unnecessary type conversions
    - prealloc # Slice pre-allocation
    - nolintlint # Validate //nolint directives

linters-settings:
  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  govet:
    enable-all: true
    disable:
      - shadow # Too strict for some cases
      - fieldalignment # Not critical, can reduce readability

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
      - name: var-naming
      - name: package-comments
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: context-keys-type
      - name: time-naming
      - name: indent-error-flow
      - name: errorf

  gosec:
    excludes:
      - G204 # Subprocess launched with variable - needed for command execution
    severity: medium
    confidence: medium

  errcheck:
    check-type-assertions: true
    check-blank: false # Allow _ = f() intentionally

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
        - errcheck # Tests often intentionally ignore errors
        - govet # Tests may have unused writes for initialization

    # Exclude TODO comments from failing the build
    - linters:
        - godot
      text: "Comment should end in a period"

    # Allow unused functions that are planned for future use
    - linters:
        - unused
      text: "is unused"

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
