version: 2

before:
  hooks:
    - go mod tidy
    - go run ./tools/precompgen/precompile.go -o pkg/uast/embedded_mappings.gen.go

builds:
  - id: codefang
    main: ./cmd/codefang
    binary: codefang
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/Sumatoshi-tech/codefang/pkg/version.Version={{.Version}}
      - -X github.com/Sumatoshi-tech/codefang/pkg/version.Commit={{.Commit}}
      - -X github.com/Sumatoshi-tech/codefang/pkg/version.Date={{.Date}}

  - id: uast
    main: ./cmd/uast
    binary: uast
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/Sumatoshi-tech/codefang/pkg/version.Version={{.Version}}
      - -X github.com/Sumatoshi-tech/codefang/pkg/version.Commit={{.Commit}}
      - -X github.com/Sumatoshi-tech/codefang/pkg/version.Date={{.Date}}

archives:
  - id: default
    ids:
      - codefang
      - uast
    name_template: >-
      codefang_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Sumatoshi-tech
    name: codefang
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
