//! `cf-uast-node` — the canonical UAST (Universal Abstract Syntax Tree) node
//! representation and the operations that travel with it.
//!
//! This is a faithful Rust port of the Go package `pkg/uast/pkg/node`. It is the
//! keystone data type of codefang: it is imported by `uast`, `framework`,
//! `analyze`, and nearly every analyzer. The most byte-identity-critical export
//! is [`Node::to_map`], whose output is serialized into machine reports — its
//! keys (`children`, `id`, `pos`, `props`, `roles`, `token`, `type`) must emit in
//! raw-UTF-8 byte order to match Go's `encoding/json` map encoding. To guarantee
//! that, [`Node::to_map`] returns a [`GoValue`] built from a map-origin [`GoMap`]
//! (sort-on-encode), never `serde_json`. See DESIGN.md §2.2.
//!
//! # Relationship to `cf-gojson`
//!
//! The design routes all report serialization through the shared `cf-gojson`
//! crate. At the time of this port `cf-gojson` is a bare scaffold (no public
//! `GoValue`/`GoMap`/`Encoder`), so per DESIGN rule (5) the minimal subset of
//! that surface lives here in [`gojson`]. The [`GoValue`]/[`GoMap`] API is shaped
//! to match the planned crate so the eventual migration is mechanical: delete
//! `gojson.rs`, depend on `cf-gojson`, and re-point the imports.
//!
//! # Differences from the Go original
//!
//! - Go uses a `sync.Pool` for `Node`/`Positions` reuse. Rust's ownership model
//!   makes that pattern both unnecessary and unsafe across threads, so the global
//!   pool collapses into ordinary [`Node::new`] construction; the per-worker
//!   free-list [`Allocator`] is ported as a real object pool (behavioral parity
//!   only — pooling never affects output bytes).
//! - Go's `PreOrder()` returns a goroutine-backed channel. Rust exposes the same
//!   traversal eagerly via [`Node::pre_order`] returning a `Vec`, plus the
//!   zero-allocation callback variants [`Node::visit_pre_order`] /
//!   [`Node::visit_post_order`] which mirror the Go callbacks exactly.
//! - The query DSL (`map`/`filter`/`reduce`/field-access pipelines) is ported in
//!   the [`dsl`] module. The Go parser was generated by `pointlander/peg` from
//!   `dsl_parser.peg`; per the rewrite rules we do NOT hand-translate the
//!   generated artifact — instead [`dsl::parse`] is a hand-written
//!   recursive-descent parser implementing the same PEG grammar.

#![forbid(unsafe_code)]

mod allocator;
mod classifier;
mod comparison;
pub mod dsl;
mod gojson;
mod node;
mod tomap;
mod traversal;
mod types;

// Re-exported so callers can build/serialize `to_map` output. These mirror the
// planned `cf-gojson` API and will be replaced by it (see `gojson.rs`).
pub use gojson::{GoMap, GoValue};

pub use allocator::Allocator;
pub use classifier::is_literal_type;
pub use node::{release_tree, Builder, Node, Positions, Role, Type};

// Re-export the UAST type and role string constants at the crate root, mirroring
// the Go package's flat `node.UASTFunction` / `node.RoleName` access pattern.
pub use node::roles::*;
pub use node::uast_types::*;
