[package]
name = "cf-cohesion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
cf-gojson = { workspace = true }
cf-goyaml = { path = "../cf-goyaml" }
cf-reportutil = { path = "../cf-reportutil" }
cf-uast-node = { path = "../cf-uast-node" }
cf-analyze = { path = "../cf-analyze" }
cf-analyzers-common = { path = "../cf-analyzers-common" }
cf-alg-bloom = { path = "../cf-alg-bloom" }
