//! Cross-format flag parity for the static analyzers.
//!
//! A shipped regression honored `--include-generated` / `--include-vendored`
//! only on the JSON path (text/compact/yaml/bin silently ignored them) and made
//! `--languages` a complete no-op. The fix threads the ONE shared
//! [`StaticFilter`] built from the run flags through every static analyzer's
//! folder walk in every output format; these tests lock that in by reading the
//! same total-functions figure back out of several encodings and asserting they
//! move together when the filter changes.
//!
//! Fixture: a multi-language tree with one function per file spanning the
//! path-policy classes (normal `.go`, suffix-generated `.pb.go`, content-marker
//! generated `.go`, `vendor/`-ed `.go`) plus a `.py` file, so the walk's file
//! selection is directly readable off the "Total Functions" metric.

use cf_commands::handlers::section_render::render_text_report;
use cf_commands::handlers::{
    static_complexity, static_complexity_yaml, static_halstead, static_multi_json,
    static_multi_text, StaticFilter,
};

/// Builds the multi-language fixture tree. Every file holds exactly ONE
/// function, so each analyzed file contributes 1 to "Total Functions".
fn fixture() -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("tempdir");
    // Plain Go source: always analyzed.
    std::fs::write(
        dir.path().join("normal.go"),
        "package main\n\nfunc add(a, b int) int {\n\treturn a + b\n}\n",
    )
    .unwrap();
    // Generated by SUFFIX (`.pb.go`): excluded unless `--include-generated`.
    std::fs::write(
        dir.path().join("gen.pb.go"),
        "package main\n\nfunc genOne() int {\n\treturn 1\n}\n",
    )
    .unwrap();
    // Generated by CONTENT MARKER only: the walk filter classifies by PATH
    // (`pathpolicy.Exclude(path, nil, opts)` — no content is read before the
    // skip decision), so this file is analyzed under either policy.
    std::fs::write(
        dir.path().join("marked.go"),
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\n\nfunc markedOne() int {\n\treturn 2\n}\n",
    )
    .unwrap();
    // Vendored: excluded unless `--include-vendored`.
    std::fs::create_dir(dir.path().join("vendor")).unwrap();
    std::fs::write(
        dir.path().join("vendor/dep.go"),
        "package dep\n\nfunc depOne() int {\n\treturn 3\n}\n",
    )
    .unwrap();
    // Second language, for the `--languages` split.
    std::fs::write(
        dir.path().join("helper.py"),
        "def helper():\n    return 4\n",
    )
    .unwrap();
    dir
}

/// The permissive walk filter: `--include-generated --include-vendored`, no
/// language restriction (the flags the regression dropped on the non-JSON
/// paths).
fn permissive() -> StaticFilter {
    StaticFilter {
        policy: cf_pathpolicy::Options {
            include_generated: true,
            include_vendored: true,
            ..cf_pathpolicy::Options::default()
        },
        language_globs: None,
    }
}

/// [`permissive`] restricted to the given `--languages` basename globs.
fn permissive_with_globs(globs: &[&str]) -> StaticFilter {
    StaticFilter {
        language_globs: Some(globs.iter().map(ToString::to_string).collect()),
        ..permissive()
    }
}

/// Strips ANSI SGR escape sequences (`ESC [ … m`) so numeric extraction from
/// the terminal-text render never trips over the digits inside color codes.
fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' {
            // Consume through the SGR terminator.
            for e in chars.by_ref() {
                if e == 'm' {
                    break;
                }
            }
            continue;
        }
        out.push(c);
    }
    out
}

/// First run of ASCII digits after `anchor` in `s` — reads the value out of
/// `"label": "Total Functions" … "value": "N"` (json), `Total Functions   N`
/// (text Key Metrics row), and `total_functions: N` (yaml) alike.
fn digits_after(s: &str, anchor: &str) -> i64 {
    let at = s
        .find(anchor)
        .unwrap_or_else(|| panic!("anchor {anchor:?} missing in:\n{s}"));
    let rest = &s[at + anchor.len()..];
    let start = rest
        .find(|c: char| c.is_ascii_digit())
        .unwrap_or_else(|| panic!("no digits after {anchor:?} in:\n{s}"));
    let digits: String = rest[start..]
        .chars()
        .take_while(char::is_ascii_digit)
        .collect();
    digits.parse().expect("digit run parses as i64")
}

/// The complexity total-functions figure per format: (json, text, yaml).
fn complexity_totals(path: &str, filter: &StaticFilter) -> (i64, i64, i64) {
    let json = static_complexity::complexity_report_flags(path, filter, false).expect("json");
    let text = render_text_report(
        &static_complexity::complexity_report_value_summary(path, filter).expect("text value"),
    );
    let yaml = static_complexity_yaml::complexity_report_yaml(path, filter).expect("yaml");
    (
        digits_after(std::str::from_utf8(&json).unwrap(), "\"Total Functions\""),
        digits_after(
            &strip_ansi(std::str::from_utf8(&text).unwrap()),
            "Total Functions",
        ),
        digits_after(std::str::from_utf8(&yaml).unwrap(), "total_functions:"),
    )
}

/// The halstead total-functions figure per format: (json, text, yaml).
fn halstead_totals(path: &str, filter: &StaticFilter) -> (i64, i64, i64) {
    let json = static_halstead::halstead_json_report_flags(path, filter, false).expect("json");
    let text = render_text_report(
        &static_halstead::halstead_report_value_summary(path, filter).expect("text value"),
    );
    let yaml = static_halstead::halstead_yaml_report(path, filter).expect("yaml");
    (
        digits_after(std::str::from_utf8(&json).unwrap(), "\"Total Functions\""),
        digits_after(
            &strip_ansi(std::str::from_utf8(&text).unwrap()),
            "Total Functions",
        ),
        digits_after(std::str::from_utf8(&yaml).unwrap(), "total_functions:"),
    )
}

#[test]
fn complexity_totals_agree_across_formats_and_observe_policy_flags() {
    let dir = fixture();
    let path = dir.path().to_str().unwrap();

    // Permissive policy: every fixture file is walked; the total must be the
    // SAME in every encoding (one shared filter, one walk contract).
    let (json, text, yaml) = complexity_totals(path, &permissive());
    assert_eq!(json, text, "json vs text disagree under permissive policy");
    assert_eq!(json, yaml, "json vs yaml disagree under permissive policy");
    assert_eq!(json, 5, "all 5 one-function files must be analyzed");

    // Default policy: the generated + vendored files drop out of EVERY format.
    // A format that ignores the flags would keep reporting the same total.
    let (djson, dtext, dyaml) = complexity_totals(path, &StaticFilter::default());
    assert_eq!(djson, dtext, "json vs text disagree under default policy");
    assert_eq!(djson, dyaml, "json vs yaml disagree under default policy");
    assert!(
        json > djson,
        "include-generated/include-vendored must reach the walk (permissive {json} vs default {djson})"
    );
}

#[test]
fn halstead_totals_agree_across_formats_and_observe_policy_flags() {
    let dir = fixture();
    let path = dir.path().to_str().unwrap();

    let (json, text, yaml) = halstead_totals(path, &permissive());
    assert_eq!(json, text, "json vs text disagree under permissive policy");
    assert_eq!(json, yaml, "json vs yaml disagree under permissive policy");
    assert_eq!(json, 5, "all 5 one-function files must be analyzed");

    let (djson, dtext, dyaml) = halstead_totals(path, &StaticFilter::default());
    assert_eq!(djson, dtext, "json vs text disagree under default policy");
    assert_eq!(djson, dyaml, "json vs yaml disagree under default policy");
    assert!(
        json > djson,
        "include-generated/include-vendored must reach the walk (permissive {json} vs default {djson})"
    );
}

#[test]
fn languages_filter_selects_per_language_totals_identically_across_formats() {
    let dir = fixture();
    let path = dir.path().to_str().unwrap();

    // `--languages Go` (basename globs `*.go`): the 4 Go files, in every format.
    let (json, text, yaml) = complexity_totals(path, &permissive_with_globs(&["*.go"]));
    assert_eq!((json, text, yaml), (4, 4, 4), "Go-only selection diverged");

    // `--languages Python`: only helper.py survives the walk.
    let (json, text, yaml) = complexity_totals(path, &permissive_with_globs(&["*.py"]));
    assert_eq!(
        (json, text, yaml),
        (1, 1, 1),
        "Python-only selection diverged"
    );

    // No globs (`--languages all` / flag absent): no restriction.
    let (json, text, yaml) = complexity_totals(path, &permissive());
    assert_eq!((json, text, yaml), (5, 5, 5), "unrestricted walk diverged");
}

#[test]
fn run_rejects_unknown_language_token_with_exit_1() {
    let dir = fixture();
    // The CLI error contract: an unresolvable `--languages` token aborts the
    // run (`Error: static --languages: unknown language: "notalang"`, exit 1)
    // instead of silently analyzing everything.
    let code = cf_commands::run([
        "codefang",
        "run",
        "--analyzers",
        "static/complexity",
        "--format",
        "json",
        "--languages",
        "NotALang",
        dir.path().to_str().unwrap(),
    ]);
    assert_eq!(code, 1, "unknown --languages token must exit 1");
}

#[test]
fn multi_analyzer_merge_paths_observe_the_walk_filter() {
    let dir = fixture();
    let path = dir.path().to_str().unwrap();

    // The merged multi-analyzer renders walk once per analyzer with the SAME
    // shared filter; if any merge path dropped it, the permissive and default
    // outputs would collapse to identical bytes.
    let json_perm = static_multi_json(&["static/*"], path, &permissive(), false).expect("json");
    let json_def =
        static_multi_json(&["static/*"], path, &StaticFilter::default(), false).expect("json");
    assert_ne!(
        json_perm, json_def,
        "static_multi_json ignored the walk filter"
    );

    let text_perm = static_multi_text(&["static/*"], path, &permissive()).expect("text");
    let text_def = static_multi_text(&["static/*"], path, &StaticFilter::default()).expect("text");
    assert_ne!(
        text_perm, text_def,
        "static_multi_text ignored the walk filter"
    );

    // The language restriction must reach the merge walks too.
    let json_py = static_multi_json(
        &["static/*"],
        path,
        &permissive_with_globs(&["*.py"]),
        false,
    )
    .expect("json");
    assert_ne!(
        json_perm, json_py,
        "static_multi_json ignored the language globs"
    );
}
