//! Embedded per-language UAST (`.uastmap`) mapping tables.
//!
//! This crate is the Rust port of the Go "uastmaps" data module: the
//! `pkg/uast/uastmaps` directory of `.uastmap` files plus the generated
//! `pkg/uast/embedded_mappings.gen.go`, which exposes a single
//! `var EmbeddedMappings map[string]string` keyed by language name.
//!
//! # What the Go side actually is
//!
//! `pkg/uast/uastmaps` contains **only data** (68 `*.uastmap` files, no `.go`
//! source and no Go tests). The generator `tools/uastmapsgen/gen_uastmaps.py`
//! reads those files (sorted) and emits a Go map keyed by `<stem>` whose value is
//! the file contents. That map is consumed in `pkg/uast` by `NewLoader`
//! (`mappings: EmbeddedMappings`) and by `SupportedLanguages` (which ranges over
//! the map and sorts the keys).
//!
//! # Generated data — regenerated, not hand-translated
//!
//! Per the Rust-rewrite design (DESIGN.md §5 and rule 6), the large generated
//! artifact is **not** hand-ported. [`build.rs`] is the Rust port of the Python
//! generator: it scans the vendored `mappings/*.uastmap` files and regenerates an
//! embedding table (`$OUT_DIR/mappings.gen.rs`) at build time using
//! `include_str!` (the analogue of Go's string-literal embedding). The vendored
//! `.uastmap` files are byte-identical to the Go module's data, so the embedded
//! content matches the Go implementation exactly.
//!
//! # Determinism
//!
//! Go map iteration is randomized; the only order-sensitive Go consumer
//! ([`supported_languages`]) sorts. We back the data with a [`BTreeMap`], so
//! iteration is inherently sorted and every derived listing is deterministic.
//!
//! [`build.rs`]: https://doc.rust-lang.org/cargo/reference/build-scripts.html

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::sync::OnceLock;

// Generated by build.rs (port of gen_uastmaps.py):
//   pub(crate) const MAPPING_COUNT: usize = N;
//   pub(crate) static MAPPINGS: [(&str, &str); N] = [ ... ];  // sorted by name
include!(concat!(env!("OUT_DIR"), "/mappings.gen.rs"));

/// The number of UAST mappings embedded at compile time.
///
/// Equal to the number of keys in the Go `EmbeddedMappings` map.
pub const EMBEDDED_MAPPING_COUNT: usize = MAPPING_COUNT;

/// Lazily-built lookup over the embedded mappings, keyed by language name.
///
/// A [`BTreeMap`] is used (rather than a `HashMap`) so iteration is inherently
/// sorted by key, keeping every derived listing deterministic. This is the Rust
/// analogue of Go's `EmbeddedMappings map[string]string`.
fn map() -> &'static BTreeMap<&'static str, &'static str> {
    static MAP: OnceLock<BTreeMap<&'static str, &'static str>> = OnceLock::new();
    MAP.get_or_init(|| MAPPINGS.iter().copied().collect())
}

/// Returns the embedded UAST mappings as a map of language name to `.uastmap`
/// content.
///
/// This is the Rust analogue of the Go `EmbeddedMappings` variable. The returned
/// reference is to a process-wide, lazily-initialized table; keys are language
/// names (the `.uastmap` filename stems) and values are the full mapping file
/// contents, byte-identical to the corresponding `mappings/<name>.uastmap` file.
pub fn embedded_mappings() -> &'static BTreeMap<&'static str, &'static str> {
    map()
}

/// Returns the mapping content for a given language name, if present.
///
/// Equivalent to indexing the Go `EmbeddedMappings` map, expressed as an
/// [`Option`]. This mirrors `Loader.LoadMapping`'s `(content, ok)` shape.
pub fn get(language: &str) -> Option<&'static str> {
    map().get(language).copied()
}

/// Returns whether a mapping is embedded for the given language name.
pub fn contains(language: &str) -> bool {
    map().contains_key(language)
}

/// Returns a sorted list of all supported language names.
///
/// Port of `pkg/uast.SupportedLanguages`, which ranges over `EmbeddedMappings`
/// and sorts the keys with `sort.Strings`. Because the backing store is a
/// [`BTreeMap`], the keys are already in sorted (UTF-8 byte) order.
pub fn supported_languages() -> Vec<&'static str> {
    map().keys().copied().collect()
}

/// Returns the number of embedded mappings.
#[allow(clippy::len_without_is_empty)]
pub fn len() -> usize {
    map().len()
}

/// Returns whether there are no embedded mappings.
///
/// Always `false` in practice (the build fails if no `.uastmap` files are
/// vendored), but provided so the type satisfies the usual `len`/`is_empty`
/// pairing.
pub fn is_empty() -> bool {
    map().is_empty()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The full set of language stems we expect to be embedded. This is the
    /// authoritative list of `.uastmap` files vendored from `pkg/uast/uastmaps`
    /// and must stay in sync with that directory (and with the Go
    /// `EmbeddedMappings` keys). Order is UTF-8 byte order (matching the
    /// `BTreeMap`).
    const EXPECTED: &[&str] = &[
        "ansible",
        "bash",
        "c",
        "c_sharp",
        "clojure",
        "cmake",
        "commonlisp",
        "cpp",
        "crystal",
        "css",
        "csv",
        "dart",
        "dockerfile",
        "dotenv",
        "elixir",
        "elm",
        "fish",
        "fortran",
        "git_config",
        "gitattributes",
        "gitignore",
        "go",
        "gosum",
        "gotmpl",
        "gowork",
        "graphql",
        "groovy",
        "haskell",
        "hcl",
        "helm",
        "html",
        "ini",
        "java",
        "javascript",
        "json",
        "kotlin",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "nim",
        "nim_format_string",
        "perl",
        "php",
        "powershell",
        "properties",
        "proto",
        "proxima",
        "prql",
        "psv",
        "python",
        "r",
        "rego",
        "ruby",
        "rust",
        "rust_with_rstml",
        "scala",
        "sql",
        "ssh_config",
        "swift",
        "tcl",
        "toml",
        "tsx",
        "typescript",
        "xml",
        "yaml",
        "zig",
    ];

    #[test]
    fn count_is_sixty_eight() {
        assert_eq!(len(), 68);
        assert_eq!(EMBEDDED_MAPPING_COUNT, 68);
        assert_eq!(EXPECTED.len(), 68);
    }

    #[test]
    fn not_empty() {
        assert!(!is_empty());
        assert!(!embedded_mappings().is_empty());
    }

    #[test]
    fn exactly_the_expected_languages() {
        let langs = supported_languages();
        assert_eq!(langs, EXPECTED);
    }

    #[test]
    fn supported_languages_is_sorted() {
        let langs = supported_languages();
        let mut sorted = langs.clone();
        sorted.sort_unstable();
        assert_eq!(langs, sorted, "supported_languages must be sorted");
    }

    #[test]
    fn every_mapping_is_non_empty() {
        for (&name, &content) in embedded_mappings() {
            assert!(!content.is_empty(), "mapping {name} is empty");
        }
    }

    #[test]
    fn get_present_and_absent() {
        assert!(get("go").is_some());
        assert!(get("python").is_some());
        assert!(get("nonexistent-language").is_none());
    }

    #[test]
    fn contains_checks() {
        assert!(contains("rust"));
        assert!(contains("typescript"));
        assert!(!contains("cobol"));
    }

    /// Each embedded mapping equals the on-disk source file, byte-for-byte. This
    /// is the data-parity check: the `include_str!` value must match the vendored
    /// `mappings/<name>.uastmap`, which is in turn byte-identical to the Go
    /// module's data.
    #[test]
    fn embedded_content_matches_source_files() {
        macro_rules! check {
            ($($lang:literal),+ $(,)?) => {{
                $(
                    let expected = include_str!(concat!("../mappings/", $lang, ".uastmap"));
                    let got = get($lang).expect(concat!("missing mapping: ", $lang));
                    assert_eq!(got, expected, "{} mapping content mismatch", $lang);
                )+
            }};
        }
        // Spot-check a representative spread (smallest, largest, common langs).
        check!(
            "go",
            "rust",
            "python",
            "java",
            "javascript",
            "typescript",
            "cpp",
            "c",
            "ini",
            "json",
            "yaml",
            "bash",
            "html",
            "proxima",
        );
    }

    /// The header of a real `.uastmap` file is bracketed
    /// (`[language "ini", extensions: ".ini"]`), which is part of the embedded
    /// content verbatim. Guard against accidental trimming/normalization.
    #[test]
    fn content_preserves_bracketed_header() {
        let ini = get("ini").expect("missing ini mapping");
        assert!(
            ini.starts_with("[language \"ini\""),
            "ini mapping header not preserved verbatim"
        );
    }
}
