//! GENERATED by uastmap2rs — transpiled from `ansible.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `ansible` language.
pub static ANSIBLE: LanguageMapping = uast_language! {
    name: "ansible",
    extensions: [".yml", ".yaml"],
    rules: {
        stream => {
            type: File,
        },
        document => {
            type: Block,
            token: self,
            roles: [Body],
        },
        block_mapping => {
            type: Dict,
            token: self,
            roles: [Literal],
        },
        block_mapping_pair => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
        },
        flow_mapping => {
            type: Dict,
            token: self,
            roles: [Literal],
        },
        flow_pair => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
        },
        block_sequence => {
            type: List,
            token: self,
            roles: [Literal],
        },
        block_sequence_item => {
            type: Block,
            token: self,
            roles: [Body],
        },
        flow_sequence => {
            type: List,
            token: self,
            roles: [Literal],
        },
        block_node => {
            type: Block,
            token: self,
            roles: [Body],
        },
        flow_node => {
            type: Block,
            token: self,
            roles: [Body],
        },
        string_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        plain_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        single_quote_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        double_quote_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        float_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        boolean_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        null_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        block_scalar => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        alias => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        alias_name => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        anchor => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        anchor_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        tag => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        yaml_directive => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        tag_directive => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
    }
};
