//! GENERATED by uastmap2rs — transpiled from `c.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `c` language.
pub static C: LanguageMapping = uast_language! {
    name: "c",
    extensions: [".c", ".h"],
    rules: {
        translation_unit => {
            type: File,
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        field_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Member],
        },
        type_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        statement_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        preproc_include => {
            type: Import,
            roles: [Import],
            children: ["call_expression", "identifier", "string_literal", "system_lib_string"],
        },
        system_lib_string => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        null => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        NULL => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        nullptr => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        char_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        concatenated_string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        binary_expression => {
            type: BinaryOp,
            roles: [Operator],
            children: ["expression", "preproc_defined"],
        },
        unary_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression", "preproc_defined"],
        },
        update_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        pointer_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        conditional_expression => {
            type: If,
            roles: [Condition],
            children: ["comma_expression", "expression"],
        },
        comma_expression => {
            type: BinaryOp,
            roles: [Operator],
            children: ["comma_expression", "expression"],
        },
        assignment_expression => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["call_expression", "expression", "field_expression", "identifier", "parenthesized_expression", "pointer_expression", "subscript_expression"],
        },
        subscript_expression => {
            type: Index,
            roles: [Index],
            children: ["expression"],
        },
        sizeof_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["expression", "type_descriptor"],
        },
        alignof_expression => {
            type: Call,
            roles: [Call],
            children: ["type_descriptor"],
        },
        offsetof_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["field_identifier", "type_descriptor"],
        },
        call_expression => {
            type: Call,
            roles: [Call],
            children: ["argument_list", "expression"],
        },
        cast_expression => {
            type: Cast,
            roles: [Type],
            children: ["expression", "type_descriptor"],
        },
        function_definition => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["_declarator", "compound_statement", "type_specifier"],
        },
        function_declarator => {
            type: Function,
            roles: [Function, Declaration],
            children: ["_declarator", "_field_declarator", "_type_declarator", "parameter_list"],
        },
        abstract_function_declarator => {
            type: Function,
            roles: [Function, Declaration],
            children: ["_abstract_declarator", "parameter_list"],
        },
        preproc_function_def => {
            type: Function,
            roles: [Function, Declaration],
            children: ["identifier", "preproc_arg", "preproc_params"],
        },
        if_statement => {
            type: If,
            roles: [Condition],
            children: ["else_clause", "parenthesized_expression", "statement"],
        },
        else_clause => {
            type: Block,
            token: self,
            roles: [Body],
        },
        for_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["comma_expression", "declaration", "expression", "statement"],
        },
        while_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        do_statement => {
            type: Loop,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        switch_statement => {
            type: Switch,
            roles: [Branch],
            children: ["compound_statement", "parenthesized_expression"],
        },
        case_statement => {
            type: Case,
            token: self,
            roles: [Branch],
            children: ["expression"],
        },
        break_statement => {
            type: Break,
            token: self,
            roles: [Break],
        },
        continue_statement => {
            type: Continue,
            token: self,
            roles: [Continue],
        },
        return_statement => {
            type: Return,
            token: self,
            roles: [Return],
        },
        goto_statement => {
            type: Break,
            token: self,
            roles: [Break],
            children: ["statement_identifier"],
        },
        labeled_statement => {
            type: Block,
            roles: [Body],
            children: ["statement_identifier"],
        },
        compound_statement => {
            type: Block,
            roles: [Body],
        },
        struct_specifier => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["field_declaration_list", "type_identifier"],
        },
        union_specifier => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["field_declaration_list", "type_identifier"],
        },
        enum_specifier => {
            type: Enum,
            roles: [Enum, Declaration],
            children: ["enumerator_list", "primitive_type", "type_identifier"],
        },
        enumerator => {
            type: EnumMember,
            token: self,
            roles: [Member, Declaration],
            children: ["expression", "identifier"],
        },
        enumerator_list => {
            type: List,
        },
        field_declaration => {
            type: Field,
            token: self,
            roles: [Member, Declaration],
            children: ["_field_declarator", "type_specifier"],
        },
        field_declaration_list => {
            type: List,
        },
        field_expression => {
            type: Field,
            roles: [Member],
            children: ["expression", "field_identifier"],
        },
        field_designator => {
            type: Identifier,
            token: self,
            roles: [Name, Member],
        },
        bitfield_clause => {
            type: Field,
            roles: [Member],
        },
        declaration => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["array_declarator", "attributed_declarator", "function_declarator", "gnu_asm_expression", "identifier", "init_declarator", "ms_call_modifier", "parenthesized_declarator", "pointer_declarator", "type_specifier"],
        },
        init_declarator => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
            children: ["_declarator", "expression", "initializer_list"],
        },
        parameter_declaration => {
            type: Parameter,
            roles: [Parameter],
            children: ["_abstract_declarator", "_declarator", "type_specifier"],
        },
        parameter_list => {
            type: List,
            token: self,
        },
        variadic_parameter => {
            type: Parameter,
            roles: [Parameter],
        },
        type_definition => {
            type: TypeAnnotation,
            roles: [Type, Declaration],
            children: ["_type_declarator", "type_specifier"],
        },
        type_descriptor => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["_abstract_declarator", "type_specifier"],
        },
        primitive_type => {
            type: Identifier,
            token: self,
            roles: [Type, Name],
        },
        sized_type_specifier => {
            type: Synthetic,
            children: ["primitive_type", "type_identifier"],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        attribute => {
            type: Attribute,
            roles: [Attribute],
            children: ["identifier"],
        },
        attribute_declaration => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        attribute_specifier => {
            type: Attribute,
            roles: [Attribute],
        },
        attributed_declarator => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        attributed_statement => {
            type: Attribute,
            roles: [Attribute],
        },
        preproc_if => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["binary_expression", "call_expression", "char_literal", "identifier", "number_literal", "parenthesized_expression", "preproc_defined", "preproc_elif", "preproc_elifdef", "preproc_else", "unary_expression"],
        },
        preproc_ifdef => {
            type: If,
            roles: [Condition],
            children: ["identifier", "preproc_elif", "preproc_elifdef", "preproc_else"],
        },
        preproc_elif => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["binary_expression", "call_expression", "char_literal", "identifier", "number_literal", "parenthesized_expression", "preproc_defined", "preproc_elif", "preproc_elifdef", "preproc_else", "unary_expression"],
        },
        preproc_elifdef => {
            type: If,
            roles: [Condition],
            children: ["identifier", "preproc_elif", "preproc_elifdef", "preproc_else"],
        },
        preproc_else => {
            type: Block,
            token: self,
            roles: [Body],
        },
        preproc_call => {
            type: Call,
            roles: [Call],
            children: ["preproc_arg", "preproc_directive"],
        },
        preproc_def => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
            children: ["identifier", "preproc_arg"],
        },
        preproc_defined => {
            type: Call,
            roles: [Call],
        },
        preproc_params => {
            type: List,
        },
        preproc_arg => {
            type: Synthetic,
            token: self,
        },
        preproc_directive => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        seh_try_statement => {
            type: Try,
            token: self,
            roles: [Try],
            children: ["compound_statement"],
        },
        seh_except_clause => {
            type: Catch,
            roles: [Catch],
            children: ["compound_statement", "parenthesized_expression"],
        },
        seh_finally_clause => {
            type: Finally,
            token: self,
            roles: [Finally],
            children: ["compound_statement"],
        },
        seh_leave_statement => {
            type: Break,
            roles: [Break],
        },
        argument_list => {
            type: List,
            token: self,
        },
        initializer_list => {
            type: List,
        },
        initializer_pair => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
            children: ["expression", "field_designator", "field_identifier", "initializer_list", "subscript_designator", "subscript_range_designator"],
        },
        declaration_list => {
            type: List,
            token: self,
        },
        subscript_designator => {
            type: Index,
            token: self,
            roles: [Index],
        },
        subscript_range_designator => {
            type: Slice,
            token: self,
            roles: [Index],
            children: ["expression"],
        },
        compound_literal_expression => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["initializer_list", "type_descriptor"],
        },
        gnu_asm_expression => {
            type: Synthetic,
            children: ["concatenated_string", "gnu_asm_clobber_list", "gnu_asm_goto_list", "gnu_asm_input_operand_list", "gnu_asm_output_operand_list", "string_literal"],
        },
        gnu_asm_clobber_list => {
            type: List,
            token: self,
            children: ["concatenated_string", "string_literal"],
        },
        gnu_asm_goto_list => {
            type: List,
            token: self,
            children: ["identifier"],
        },
        gnu_asm_input_operand => {
            type: Synthetic,
            children: ["expression", "identifier", "string_literal"],
        },
        gnu_asm_input_operand_list => {
            type: List,
            token: self,
            children: ["gnu_asm_input_operand"],
        },
        gnu_asm_output_operand => {
            type: Synthetic,
            children: ["expression", "identifier", "string_literal"],
        },
        gnu_asm_output_operand_list => {
            type: List,
            token: self,
            children: ["gnu_asm_output_operand"],
        },
        gnu_asm_qualifier => {
            type: Synthetic,
        },
        linkage_specification => {
            type: Synthetic,
            token: self,
            children: ["declaration", "declaration_list", "function_definition", "string_literal"],
        },
        macro_type_specifier => {
            type: Synthetic,
            children: ["identifier", "type_descriptor"],
        },
        generic_expression => {
            type: Synthetic,
        },
        extension_expression => {
            type: Synthetic,
        },
        expression_statement => {
            type: Synthetic,
            token: self,
        },
        parenthesized_expression => {
            type: Synthetic,
            token: self,
        },
        _abstract_declarator => {
            type: Synthetic,
        },
        _declarator => {
            type: Synthetic,
            token: self,
        },
        _field_declarator => {
            type: Identifier,
            roles: [Name, Member],
        },
        _type_declarator => {
            type: Synthetic,
            token: self,
        },
        expression => {
            type: Synthetic,
        },
        statement => {
            type: Synthetic,
            token: self,
        },
        type_specifier => {
            type: Synthetic,
        },
        abstract_array_declarator => {
            type: Synthetic,
            token: self,
            children: ["_abstract_declarator", "expression"],
        },
        abstract_parenthesized_declarator => {
            type: Synthetic,
            token: self,
        },
        abstract_pointer_declarator => {
            type: Synthetic,
            children: ["_abstract_declarator"],
        },
        alignas_qualifier => {
            type: Synthetic,
            token: self,
        },
        array_declarator => {
            type: Synthetic,
            children: ["_declarator", "_field_declarator", "_type_declarator", "expression"],
        },
        parenthesized_declarator => {
            type: Synthetic,
        },
        pointer_declarator => {
            type: Synthetic,
            children: ["_declarator", "_field_declarator", "_type_declarator"],
        },
        type_qualifier => {
            type: Synthetic,
        },
        storage_class_specifier => {
            type: Synthetic,
        },
        ms_based_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_call_modifier => {
            type: Synthetic,
        },
        ms_declspec_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_pointer_modifier => {
            type: Synthetic,
        },
        ms_unaligned_ptr_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_restrict_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_signed_ptr_modifier => {
            type: Synthetic,
        },
        ms_unsigned_ptr_modifier => {
            type: Synthetic,
            token: self,
        },
        if => {
            type: Synthetic,
        },
        else => {
            type: Synthetic,
            token: self,
        },
        for => {
            type: Synthetic,
            token: self,
        },
        while => {
            type: Synthetic,
            token: self,
        },
        do => {
            type: Synthetic,
        },
        switch => {
            type: Synthetic,
            token: self,
        },
        case => {
            type: Synthetic,
        },
        default => {
            type: Synthetic,
        },
        break => {
            type: Synthetic,
            token: self,
        },
        continue => {
            type: Synthetic,
            token: self,
        },
        return => {
            type: Synthetic,
            token: self,
        },
        goto => {
            type: Synthetic,
        },
        struct => {
            type: Synthetic,
        },
        union => {
            type: Synthetic,
            token: self,
        },
        enum => {
            type: Synthetic,
        },
        typedef => {
            type: Synthetic,
        },
        const => {
            type: Synthetic,
            token: self,
        },
        volatile => {
            type: Synthetic,
            token: self,
        },
        restrict => {
            type: Synthetic,
        },
        register => {
            type: Synthetic,
            token: self,
        },
        static => {
            type: Synthetic,
        },
        extern => {
            type: Synthetic,
        },
        inline => {
            type: Synthetic,
            token: self,
        },
        auto => {
            type: Synthetic,
        },
        sizeof => {
            type: Synthetic,
        },
        alignof => {
            type: Synthetic,
        },
        offsetof => {
            type: Synthetic,
        },
        asm => {
            type: Synthetic,
            token: self,
        },
        defined => {
            type: Synthetic,
            token: self,
        },
        short => {
            type: Synthetic,
        },
        long => {
            type: Synthetic,
        },
        signed => {
            type: Synthetic,
            token: self,
        },
        unsigned => {
            type: Synthetic,
        },
        character => {
            type: Synthetic,
            token: self,
        },
        escape_sequence => {
            type: Synthetic,
            token: self,
        },
        string_content => {
            type: Synthetic,
            token: self,
        },
        thread_local => {
            type: Synthetic,
            token: self,
        },
        constexpr => {
            type: Synthetic,
        },
        noreturn => {
            type: Synthetic,
        },
        _Alignas => {
            type: Synthetic,
            token: self,
        },
        _Alignof => {
            type: Synthetic,
        },
        _Atomic => {
            type: Synthetic,
            token: self,
        },
        _Generic => {
            type: Synthetic,
        },
        _Nonnull => {
            type: Synthetic,
            token: self,
        },
        _Noreturn => {
            type: Synthetic,
        },
        __alignof => {
            type: Synthetic,
            token: self,
        },
        __alignof__ => {
            type: Synthetic,
        },
        __asm => {
            type: Synthetic,
            token: self,
        },
        __asm__ => {
            type: Synthetic,
        },
        __attribute => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        __attribute__ => {
            type: Attribute,
            roles: [Attribute],
        },
        __based => {
            type: Synthetic,
            token: self,
        },
        __cdecl => {
            type: Synthetic,
        },
        __clrcall => {
            type: Synthetic,
            token: self,
        },
        __declspec => {
            type: Synthetic,
        },
        __except => {
            type: Synthetic,
            token: self,
        },
        __extension__ => {
            type: Synthetic,
        },
        __fastcall => {
            type: Synthetic,
            token: self,
        },
        __finally => {
            type: Finally,
            roles: [Finally],
        },
        __forceinline => {
            type: Synthetic,
            token: self,
        },
        __inline => {
            type: Synthetic,
        },
        __inline__ => {
            type: Synthetic,
            token: self,
        },
        __leave => {
            type: Synthetic,
        },
        __restrict__ => {
            type: Synthetic,
            token: self,
        },
        __stdcall => {
            type: Synthetic,
        },
        __thiscall => {
            type: Synthetic,
            token: self,
        },
        __thread => {
            type: Synthetic,
        },
        __try => {
            type: Try,
            token: self,
            roles: [Try],
        },
        __unaligned => {
            type: Synthetic,
        },
        __vectorcall => {
            type: Synthetic,
            token: self,
        },
        __volatile__ => {
            type: Synthetic,
        },
        _alignof => {
            type: Synthetic,
            token: self,
        },
        _unaligned => {
            type: Synthetic,
        },
        alignas => {
            type: Synthetic,
            token: self,
        },
    }
};
