//! GENERATED by uastmap2rs — transpiled from `dockerfile.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `dockerfile` language.
pub static DOCKERFILE: LanguageMapping = uast_language! {
    name: "dockerfile",
    extensions: [".dockerfile"],
    files: ["Dockerfile"],
    rules: {
        source_file => {
            type: File,
        },
        from_instruction => {
            type: Import,
            roles: [Import],
        },
        image_spec => {
            type: Identifier,
            roles: [Name],
        },
        image_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        image_tag => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        image_digest => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        image_alias => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        arg_instruction => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        env_instruction => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        env_pair => {
            type: KeyValue,
            roles: [Key, Value],
        },
        run_instruction => {
            type: Call,
            roles: [Call],
        },
        cmd_instruction => {
            type: Call,
            roles: [Call],
        },
        entrypoint_instruction => {
            type: Call,
            roles: [Call],
        },
        copy_instruction => {
            type: Call,
            roles: [Call],
        },
        add_instruction => {
            type: Call,
            roles: [Call],
        },
        workdir_instruction => {
            type: Call,
            roles: [Call],
        },
        expose_instruction => {
            type: Call,
            roles: [Call],
        },
        expose_port => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        volume_instruction => {
            type: Call,
            roles: [Call],
        },
        user_instruction => {
            type: Call,
            roles: [Call],
        },
        label_instruction => {
            type: Property,
            roles: [Member],
        },
        label_pair => {
            type: KeyValue,
            roles: [Key, Value],
        },
        maintainer_instruction => {
            type: Property,
            roles: [Member],
        },
        shell_instruction => {
            type: Call,
            roles: [Call],
        },
        healthcheck_instruction => {
            type: Call,
            roles: [Call],
        },
        stopsignal_instruction => {
            type: Call,
            roles: [Call],
        },
        onbuild_instruction => {
            type: Call,
            roles: [Call],
        },
        cross_build_instruction => {
            type: Call,
            roles: [Call],
        },
        shell_command => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        shell_fragment => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        json_string_array => {
            type: List,
            roles: [Literal],
        },
        json_string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        double_quoted_string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        single_quoted_string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        unquoted_string => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        path => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        variable => {
            type: Identifier,
            token: self,
            roles: [Name, Variable],
        },
        expansion => {
            type: Identifier,
            token: self,
            roles: [Name, Reference],
        },
        param => {
            type: Property,
            token: self,
            roles: [Member],
        },
        mount_param => {
            type: Property,
            roles: [Member],
        },
        mount_param_param => {
            type: KeyValue,
            roles: [Key, Value],
        },
        heredoc_block => {
            type: Block,
            roles: [Body],
        },
        heredoc_line => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        heredoc_marker => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        heredoc_end => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        escape_sequence => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        line_continuation => {
            type: Synthetic,
        },
        mount => {
            type: Synthetic,
            token: self,
        },
        FROM => {
            type: Synthetic,
            token: self,
        },
        AS => {
            type: Synthetic,
            token: self,
        },
        ARG => {
            type: Synthetic,
            token: self,
        },
        ENV => {
            type: Synthetic,
            token: self,
        },
        RUN => {
            type: Synthetic,
            token: self,
        },
        CMD => {
            type: Synthetic,
            token: self,
        },
        ENTRYPOINT => {
            type: Synthetic,
            token: self,
        },
        COPY => {
            type: Synthetic,
            token: self,
        },
        ADD => {
            type: Synthetic,
            token: self,
        },
        WORKDIR => {
            type: Synthetic,
            token: self,
        },
        EXPOSE => {
            type: Synthetic,
            token: self,
        },
        VOLUME => {
            type: Synthetic,
            token: self,
        },
        USER => {
            type: Synthetic,
            token: self,
        },
        LABEL => {
            type: Synthetic,
            token: self,
        },
        MAINTAINER => {
            type: Synthetic,
            token: self,
        },
        SHELL => {
            type: Synthetic,
            token: self,
        },
        HEALTHCHECK => {
            type: Synthetic,
            token: self,
        },
        STOPSIGNAL => {
            type: Synthetic,
            token: self,
        },
        ONBUILD => {
            type: Synthetic,
            token: self,
        },
        CROSS_BUILD => {
            type: Synthetic,
            token: self,
        },
        NONE => {
            type: Synthetic,
            token: self,
        },
        _heredoc_nl => {
            type: Synthetic,
        },
    }
};
