//! GENERATED by uastmap2rs — transpiled from `gitattributes.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `gitattributes` language.
pub static GITATTRIBUTES: LanguageMapping = uast_language! {
    name: "gitattributes",
    extensions: [".gitattributes"],
    rules: {
        file => {
            type: File,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        pattern => {
            type: Literal,
            roles: [Literal],
        },
        quoted_pattern => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        attribute => {
            type: KeyValue,
            roles: [Key, Value],
        },
        attr_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        attr_set => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        attr_unset => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        attr_reset => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        boolean_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        macro_def => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        macro_tag => {
            type: Synthetic,
            token: self,
        },
        builtin_attr => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        pattern_negation => {
            type: Synthetic,
            token: self,
        },
        dir_sep => {
            type: Synthetic,
            token: self,
        },
        trailing_slash => {
            type: Synthetic,
            token: self,
        },
        wildcard => {
            type: Synthetic,
            token: self,
        },
        character_class => {
            type: Synthetic,
        },
        class_range => {
            type: Synthetic,
            token: self,
        },
        range_notation => {
            type: Synthetic,
        },
        range_negation => {
            type: Synthetic,
            token: self,
        },
        escaped_char => {
            type: Synthetic,
            token: self,
        },
        ansi_c_escape => {
            type: Synthetic,
            token: self,
        },
        redundant_escape => {
            type: Synthetic,
            token: self,
        },
        ignored_value => {
            type: Synthetic,
            token: self,
        },
        text => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        binary => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        crlf => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        eol => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        diff => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        merge => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        filter => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ident => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        delta => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        encoding => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        whitespace => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
    }
};
