//! GENERATED by uastmap2rs — transpiled from `gitignore.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `gitignore` language.
pub static GITIGNORE: LanguageMapping = uast_language! {
    name: "gitignore",
    extensions: [".gitignore"],
    rules: {
        document => {
            type: File,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        pattern => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        pattern_char => {
            type: Synthetic,
            token: self,
        },
        pattern_char_escaped => {
            type: Synthetic,
            token: self,
        },
        negation => {
            type: Synthetic,
            token: self,
        },
        directory_separator => {
            type: Synthetic,
            token: self,
        },
        directory_separator_escaped => {
            type: Synthetic,
            token: self,
        },
        wildcard_char_single => {
            type: Synthetic,
            token: self,
        },
        wildcard_chars => {
            type: Synthetic,
            token: self,
        },
        wildcard_chars_allow_slash => {
            type: Synthetic,
            token: self,
        },
        bracket_expr => {
            type: Synthetic,
        },
        bracket_negation => {
            type: Synthetic,
            token: self,
        },
        bracket_char => {
            type: Synthetic,
            token: self,
        },
        bracket_char_escaped => {
            type: Synthetic,
            token: self,
        },
        bracket_range => {
            type: Synthetic,
            token: self,
        },
        bracket_char_class => {
            type: Synthetic,
        },
        alnum => {
            type: Synthetic,
            token: self,
        },
        alpha => {
            type: Synthetic,
            token: self,
        },
        blank => {
            type: Synthetic,
            token: self,
        },
        cntrl => {
            type: Synthetic,
            token: self,
        },
        digit => {
            type: Synthetic,
            token: self,
        },
        graph => {
            type: Synthetic,
            token: self,
        },
        lower => {
            type: Synthetic,
            token: self,
        },
        print => {
            type: Synthetic,
            token: self,
        },
        punct => {
            type: Synthetic,
            token: self,
        },
        space => {
            type: Synthetic,
            token: self,
        },
        upper => {
            type: Synthetic,
            token: self,
        },
        xdigit => {
            type: Synthetic,
            token: self,
        },
    }
};
