//! GENERATED by uastmap2rs — transpiled from `gosum.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `gosum` language.
pub static GOSUM: LanguageMapping = uast_language! {
    name: "gosum",
    extensions: [],
    files: ["go.sum"],
    rules: {
        checksum => {
            type: Synthetic,
        },
        checksum_database => {
            type: File,
        },
        checksum_value => {
            type: Synthetic,
        },
        version => {
            type: Synthetic,
            token: self,
            children: ["alpha", "beta", "dev", "hex_number", "module_version", "number", "number_with_decimal", "pre", "rc"],
        },
        alpha => {
            type: Synthetic,
        },
        beta => {
            type: Synthetic,
            token: self,
        },
        dev => {
            type: Synthetic,
        },
        hash => {
            type: Synthetic,
            token: self,
        },
        hash_version => {
            type: Synthetic,
        },
        hex_number => {
            type: Synthetic,
            token: self,
        },
        module_path => {
            type: Import,
            token: self,
            roles: [Import],
        },
        module_version => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number => {
            type: Synthetic,
        },
        number_with_decimal => {
            type: Synthetic,
            token: self,
        },
        pre => {
            type: Synthetic,
        },
        rc => {
            type: Synthetic,
            token: self,
        },
    }
};
