//! GENERATED by uastmap2rs — transpiled from `helm.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `helm` language.
pub static HELM: LanguageMapping = uast_language! {
    name: "helm",
    extensions: [".yaml", ".yml"],
    rules: {
        argument_list => {
            type: List,
        },
        assignment => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["assignment", "chained_pipeline", "dot", "false", "field", "float_literal", "function_call", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "raw_string_literal", "rune_literal", "selector_expression", "true", "variable", "variable_definition"],
        },
        block_action => {
            type: Block,
            roles: [Body],
            children: ["assignment", "block_action", "chained_pipeline", "comment", "define_action", "dot", "false", "field", "float_literal", "function_call", "if_action", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "range_action", "raw_string_literal", "rune_literal", "selector_expression", "template_action", "text", "true", "variable", "variable_definition", "with_action", "yaml_no_injection_text"],
        },
        chained_pipeline => {
            type: Synthetic,
            token: self,
        },
        define_action => {
            type: Synthetic,
            children: ["assignment", "block_action", "chained_pipeline", "comment", "define_action", "dot", "false", "field", "float_literal", "function_call", "if_action", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "range_action", "raw_string_literal", "rune_literal", "selector_expression", "template_action", "text", "true", "variable", "variable_definition", "with_action", "yaml_no_injection_text"],
        },
        dot => {
            type: Synthetic,
            token: self,
        },
        field => {
            type: Field,
            roles: [Member],
            children: ["identifier"],
        },
        function_call => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["argument_list", "identifier"],
        },
        if_action => {
            type: If,
            children: ["assignment", "block_action", "chained_pipeline", "comment", "define_action", "dot", "false", "field", "float_literal", "function_call", "if_action", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "range_action", "raw_string_literal", "rune_literal", "selector_expression", "template_action", "text", "true", "variable", "variable_definition", "with_action", "yaml_no_injection_text"],
        },
        interpreted_string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        method_call => {
            type: Method,
            roles: [Function, Declaration, Member],
            children: ["argument_list", "field", "selector_expression"],
        },
        parenthesized_pipeline => {
            type: Call,
            token: self,
            roles: [Call],
        },
        range_action => {
            type: Synthetic,
            children: ["assignment", "block_action", "chained_pipeline", "comment", "define_action", "dot", "false", "field", "float_literal", "function_call", "if_action", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "range_action", "raw_string_literal", "rune_literal", "selector_expression", "template_action", "text", "true", "variable", "variable_definition", "with_action", "yaml_no_injection_text"],
        },
        range_variable_definition => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
            children: ["assignment", "chained_pipeline", "dot", "false", "field", "float_literal", "function_call", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "raw_string_literal", "rune_literal", "selector_expression", "true", "variable", "variable_definition"],
        },
        selector_expression => {
            type: Synthetic,
            children: ["field", "field_identifier", "parenthesized_pipeline", "selector_expression", "variable"],
        },
        template => {
            type: File,
        },
        template_action => {
            type: Synthetic,
            children: ["assignment", "chained_pipeline", "dot", "false", "field", "float_literal", "function_call", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "raw_string_literal", "rune_literal", "selector_expression", "true", "variable", "variable_definition"],
        },
        text => {
            type: Synthetic,
            token: self,
        },
        variable => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["identifier"],
        },
        variable_definition => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
            children: ["assignment", "chained_pipeline", "dot", "false", "field", "float_literal", "function_call", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "raw_string_literal", "rune_literal", "selector_expression", "true", "variable", "variable_definition"],
        },
        with_action => {
            type: Synthetic,
            children: ["assignment", "block_action", "chained_pipeline", "comment", "define_action", "dot", "false", "field", "float_literal", "function_call", "if_action", "imaginary_literal", "int_literal", "interpreted_string_literal", "method_call", "nil", "parenthesized_pipeline", "range_action", "raw_string_literal", "rune_literal", "selector_expression", "template_action", "text", "true", "variable", "variable_definition", "with_action", "yaml_no_injection_text"],
        },
        block => {
            type: Block,
            token: self,
            roles: [Body],
        },
        comment => {
            type: Comment,
            roles: [Comment],
        },
        define => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        else => {
            type: Synthetic,
        },
        end => {
            type: Synthetic,
            token: self,
        },
        escape_sequence => {
            type: Synthetic,
        },
        false => {
            type: Synthetic,
            token: self,
        },
        field_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        float_literal => {
            type: Literal,
            token: self,
            roles: [Reference, Literal],
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        if => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        imaginary_literal => {
            type: Literal,
            roles: [Literal],
        },
        int_literal => {
            type: Literal,
            token: self,
            roles: [Literal, Literal],
        },
        nil => {
            type: Synthetic,
        },
        range => {
            type: Synthetic,
            token: self,
        },
        raw_string_literal => {
            type: Literal,
            roles: [Literal],
        },
        rune_literal => {
            type: Literal,
            token: self,
            roles: [Literal, Literal],
        },
        true => {
            type: Synthetic,
            token: self,
        },
        with => {
            type: Synthetic,
        },
        yaml_no_injection_text => {
            type: Synthetic,
            token: self,
        },
    }
};
