//! GENERATED by uastmap2rs — transpiled from `nim.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `nim` language.
pub static NIM: LanguageMapping = uast_language! {
    name: "nim",
    extensions: [".nim"],
    rules: {
        source_file => {
            type: File,
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        integer_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        float_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        char_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        interpreted_string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        long_string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        raw_string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        nil_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        custom_numeric_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        import_statement => {
            type: Import,
            token: self,
            roles: [Import],
        },
        import_from_statement => {
            type: Import,
            token: self,
            roles: [Import],
        },
        include_statement => {
            type: Import,
            token: self,
            roles: [Import],
        },
        export_statement => {
            type: Export,
            token: self,
            roles: [Export],
        },
        proc_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        func_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        method_declaration => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
        },
        iterator_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        converter_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        macro_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        template_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        type_declaration => {
            type: TypeDeclaration,
            token: self,
            roles: [Type, Declaration],
        },
        object_declaration => {
            type: Class,
            token: self,
            roles: [Type, Declaration],
        },
        enum_declaration => {
            type: Enum,
            token: self,
            roles: [Enum, Declaration],
        },
        variable_declaration => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
        },
        const_section => {
            type: Block,
            token: self,
            roles: [Declaration],
        },
        let_section => {
            type: Block,
            token: self,
            roles: [Declaration],
        },
        var_section => {
            type: Block,
            token: self,
            roles: [Declaration],
        },
        type_section => {
            type: Block,
            token: self,
            roles: [Type, Declaration],
        },
        assignment => {
            type: Assignment,
            token: self,
            roles: [Assignment],
        },
        call => {
            type: Call,
            token: self,
            roles: [Call],
        },
        dot_generic_call => {
            type: Call,
            token: self,
            roles: [Call],
        },
        dot_expression => {
            type: MemberAccess,
            token: self,
            roles: [Member],
        },
        bracket_expression => {
            type: Index,
            token: self,
            roles: [Index],
        },
        infix_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        prefix_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
        },
        if => {
            type: If,
            token: self,
            roles: [Condition],
        },
        elif_branch => {
            type: If,
            token: self,
            roles: [Condition],
        },
        else_branch => {
            type: Block,
            token: self,
            roles: [Body],
        },
        case => {
            type: Switch,
            token: self,
            roles: [Condition],
        },
        of_branch => {
            type: Case,
            token: self,
            roles: [Branch],
        },
        for => {
            type: Loop,
            token: self,
            roles: [Loop],
        },
        while => {
            type: Loop,
            token: self,
            roles: [Loop],
        },
        block => {
            type: Block,
            token: self,
            roles: [Body],
        },
        do_block => {
            type: Block,
            token: self,
            roles: [Body],
        },
        statement_list => {
            type: Block,
            token: self,
            roles: [Body],
        },
        try => {
            type: Try,
            token: self,
            roles: [Try],
        },
        except_branch => {
            type: Catch,
            token: self,
            roles: [Catch],
        },
        finally_branch => {
            type: Finally,
            token: self,
            roles: [Finally],
        },
        raise_statement => {
            type: Throw,
            token: self,
            roles: [Throw],
        },
        return_statement => {
            type: Return,
            token: self,
            roles: [Return],
        },
        break_statement => {
            type: Break,
            token: self,
            roles: [Break],
        },
        continue_statement => {
            type: Continue,
            token: self,
            roles: [Continue],
        },
        yield_statement => {
            type: Yield,
            token: self,
            roles: [Yield],
        },
        discard_statement => {
            type: Synthetic,
            token: self,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        documentation_comment => {
            type: Comment,
            token: self,
            roles: [Comment, Doc],
        },
        block_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        block_documentation_comment => {
            type: Comment,
            token: self,
            roles: [Comment, Doc],
        },
        argument_list => {
            type: List,
            token: self,
            roles: [Argument],
        },
        expression_list => {
            type: List,
            token: self,
        },
        parameter_declaration => {
            type: Parameter,
            token: self,
            roles: [Parameter],
        },
        parameter_declaration_list => {
            type: List,
            token: self,
            roles: [Parameter],
        },
        generic_parameter_list => {
            type: List,
            token: self,
            roles: [Type],
        },
        generic_argument_list => {
            type: List,
            token: self,
            roles: [Type],
        },
        tuple_construction => {
            type: Tuple,
            token: self,
        },
        tuple_type => {
            type: Tuple,
            token: self,
            roles: [Type],
        },
        array_construction => {
            type: List,
            token: self,
        },
        curly_construction => {
            type: Dict,
            token: self,
        },
        field_declaration => {
            type: Field,
            token: self,
            roles: [Member],
        },
        field_declaration_list => {
            type: List,
            token: self,
            roles: [Member],
        },
        enum_field_declaration => {
            type: Field,
            token: self,
            roles: [Member],
        },
        type_expression => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        colon_expression => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
        },
        proc_expression => {
            type: Lambda,
            token: self,
            roles: [Lambda],
        },
        func_expression => {
            type: Lambda,
            token: self,
            roles: [Lambda],
        },
        iterator_expression => {
            type: Lambda,
            token: self,
            roles: [Lambda],
        },
        cast => {
            type: Cast,
            token: self,
            roles: [Cast],
        },
        when => {
            type: If,
            token: self,
            roles: [Condition],
        },
        pragma_expression => {
            type: Annotation,
            token: self,
            roles: [Annotation],
        },
        pragma_list => {
            type: List,
            token: self,
            roles: [Annotation],
        },
        pragma_statement => {
            type: Annotation,
            token: self,
            roles: [Annotation],
        },
        defer => {
            type: Defer,
            token: self,
            roles: [Defer],
        },
        static_statement => {
            type: Block,
            token: self,
            roles: [Static],
        },
        operator => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
    }
};
