//! GENERATED by uastmap2rs — transpiled from `php.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `php` language.
pub static PHP: LanguageMapping = uast_language! {
    name: "php",
    extensions: [".php", ".phtml"],
    rules: {
        program => {
            type: File,
        },
        name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        null => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        float => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        encapsed_string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        heredoc => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["heredoc_body", "heredoc_end", "heredoc_start"],
        },
        nowdoc => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["heredoc_end", "heredoc_start", "nowdoc_body"],
        },
        boolean => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        namespace_use_declaration => {
            type: Import,
            roles: [Import],
            children: ["const", "function", "namespace_use_group"],
        },
        namespace_use_clause => {
            type: Import,
            token: self,
            roles: [Import],
            children: ["const", "function", "name"],
        },
        namespace_use_group => {
            type: Import,
            token: self,
            roles: [Import],
        },
        include_expression => {
            type: Import,
            token: self,
            roles: [Import],
        },
        include_once_expression => {
            type: Import,
            token: self,
            roles: [Import],
        },
        require_expression => {
            type: Import,
            token: self,
            roles: [Import],
        },
        require_once_expression => {
            type: Import,
            token: self,
            roles: [Import],
        },
        namespace_definition => {
            type: Namespace,
            token: self,
            roles: [Module],
            children: ["compound_statement", "namespace_name"],
        },
        namespace_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        binary_expression => {
            type: BinaryOp,
            roles: [Operator],
            children: ["and", "dynamic_variable_name", "expression", "instanceof", "member_access_expression", "name", "nullsafe_member_access_expression", "or", "parenthesized_expression", "qualified_name", "relative_name", "scoped_property_access_expression", "subscript_expression", "variable_name", "xor"],
        },
        unary_op_expression => {
            type: UnaryOp,
            roles: [Operator],
            children: ["expression"],
        },
        update_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["cast_expression", "dynamic_variable_name", "function_call_expression", "member_access_expression", "member_call_expression", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "scoped_call_expression", "scoped_property_access_expression", "subscript_expression", "variable_name"],
        },
        conditional_expression => {
            type: If,
            roles: [Condition],
            children: ["expression"],
        },
        class_declaration => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["attribute_list", "declaration_list", "name"],
        },
        anonymous_class => {
            type: Class,
            roles: [Class, Declaration],
            children: ["attribute_list", "declaration_list"],
        },
        class_interface_clause => {
            type: Synthetic,
        },
        class_constant_access_expression => {
            type: Synthetic,
        },
        interface_declaration => {
            type: Interface,
            token: self,
            roles: [Interface, Declaration],
            children: ["attribute_list", "declaration_list", "name"],
        },
        trait_declaration => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["attribute_list", "declaration_list", "name"],
        },
        enum_declaration => {
            type: Enum,
            token: self,
            roles: [Enum, Declaration],
            children: ["attribute_list", "enum_declaration_list", "name"],
        },
        enum_declaration_list => {
            type: Block,
            roles: [Body],
        },
        enum_case => {
            type: EnumMember,
            roles: [Member],
            children: ["attribute_list", "expression", "name"],
        },
        function_definition => {
            type: Function,
            roles: [Function, Declaration],
            children: ["attribute_list", "bottom_type", "compound_statement", "formal_parameters", "name", "type"],
        },
        method_declaration => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
            children: ["attribute_list", "bottom_type", "compound_statement", "formal_parameters", "name", "type"],
        },
        anonymous_function => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["attribute_list", "bottom_type", "compound_statement", "formal_parameters", "reference_modifier", "static_modifier", "type"],
        },
        arrow_function => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["attribute_list", "bottom_type", "expression", "formal_parameters", "reference_modifier", "static_modifier", "type"],
        },
        anonymous_function_use_clause => {
            type: Synthetic,
        },
        function_call_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["arguments", "array_creation_expression", "dynamic_variable_name", "encapsed_string", "function_call_expression", "heredoc", "member_call_expression", "name", "nowdoc", "nullsafe_member_call_expression", "object_creation_expression", "parenthesized_expression", "qualified_name", "relative_name", "scoped_call_expression", "string", "subscript_expression", "variable_name"],
        },
        member_call_expression => {
            type: Call,
            roles: [Call],
            children: ["arguments", "array_creation_expression", "cast_expression", "class_constant_access_expression", "dynamic_variable_name", "encapsed_string", "expression", "function_call_expression", "heredoc", "member_access_expression", "member_call_expression", "name", "nowdoc", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "object_creation_expression", "parenthesized_expression", "qualified_name", "relative_name", "scoped_call_expression", "scoped_property_access_expression", "string", "subscript_expression", "variable_name"],
        },
        nullsafe_member_call_expression => {
            type: Call,
            roles: [Call],
            children: ["arguments", "array_creation_expression", "cast_expression", "class_constant_access_expression", "dynamic_variable_name", "encapsed_string", "expression", "function_call_expression", "heredoc", "member_access_expression", "member_call_expression", "name", "nowdoc", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "object_creation_expression", "parenthesized_expression", "qualified_name", "relative_name", "scoped_call_expression", "scoped_property_access_expression", "string", "subscript_expression", "variable_name"],
        },
        scoped_call_expression => {
            type: Call,
            roles: [Call],
            children: ["arguments", "array_creation_expression", "cast_expression", "class_constant_access_expression", "dynamic_variable_name", "encapsed_string", "expression", "function_call_expression", "heredoc", "member_access_expression", "member_call_expression", "name", "nowdoc", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "object_creation_expression", "parenthesized_expression", "qualified_name", "relative_name", "relative_scope", "scoped_call_expression", "scoped_property_access_expression", "string", "subscript_expression", "variable_name"],
        },
        object_creation_expression => {
            type: Call,
            token: self,
            roles: [Call],
        },
        formal_parameters => {
            type: Synthetic,
        },
        simple_parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["attribute_list", "expression", "reference_modifier", "type", "variable_name"],
        },
        variadic_parameter => {
            type: Parameter,
            token: self,
            roles: [Parameter, Spread],
            children: ["attribute_list", "reference_modifier", "type", "variable_name"],
        },
        property_promotion_parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["attribute_list", "by_ref", "expression", "readonly_modifier", "type", "variable_name", "visibility_modifier"],
        },
        argument => {
            type: Synthetic,
            token: self,
            roles: [Argument],
            children: ["name", "reference_modifier"],
        },
        arguments => {
            type: Synthetic,
        },
        variable_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        dynamic_variable_name => {
            type: Identifier,
            roles: [Name],
        },
        assignment_expression => {
            type: Assignment,
            roles: [Assignment],
            children: ["cast_expression", "dynamic_variable_name", "expression", "function_call_expression", "list_literal", "member_access_expression", "member_call_expression", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "scoped_call_expression", "scoped_property_access_expression", "subscript_expression", "variable_name"],
        },
        augmented_assignment_expression => {
            type: Assignment,
            roles: [Assignment],
            children: ["cast_expression", "dynamic_variable_name", "expression", "function_call_expression", "member_access_expression", "member_call_expression", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "scoped_call_expression", "scoped_property_access_expression", "subscript_expression", "variable_name"],
        },
        reference_assignment_expression => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["cast_expression", "dynamic_variable_name", "expression", "function_call_expression", "list_literal", "member_access_expression", "member_call_expression", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "scoped_call_expression", "scoped_property_access_expression", "subscript_expression", "variable_name"],
        },
        if_statement => {
            type: If,
            roles: [Condition],
            children: ["colon_block", "else_clause", "else_if_clause", "parenthesized_expression", "statement"],
        },
        else_clause => {
            type: Synthetic,
            children: ["colon_block", "statement"],
        },
        else_if_clause => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["colon_block", "parenthesized_expression", "statement"],
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
            children: ["expression", "sequence_expression", "statement"],
        },
        foreach_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["colon_block", "statement"],
        },
        while_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["colon_block", "parenthesized_expression", "statement"],
        },
        do_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        switch_statement => {
            type: Switch,
            token: self,
            children: ["parenthesized_expression", "switch_block"],
        },
        switch_block => {
            type: Block,
            roles: [Body],
        },
        case_statement => {
            type: Case,
            roles: [Branch],
            children: ["expression"],
        },
        default_statement => {
            type: Case,
            token: self,
            roles: [Branch],
        },
        match_expression => {
            type: Match,
            roles: [Match],
            children: ["match_block", "parenthesized_expression"],
        },
        match_block => {
            type: Block,
            roles: [Body],
        },
        match_conditional_expression => {
            type: Case,
            roles: [Branch],
            children: ["expression", "match_condition_list"],
        },
        match_default_expression => {
            type: Case,
            token: self,
            roles: [Branch],
            children: ["expression"],
        },
        match_condition_list => {
            type: List,
            token: self,
        },
        break_statement => {
            type: Break,
            roles: [Break],
        },
        continue_statement => {
            type: Continue,
            token: self,
            roles: [Continue],
        },
        return_statement => {
            type: Return,
            token: self,
            roles: [Return],
        },
        try_statement => {
            type: Try,
            roles: [Try],
            children: ["compound_statement"],
        },
        catch_clause => {
            type: Catch,
            token: self,
            roles: [Catch],
            children: ["compound_statement", "type_list", "variable_name"],
        },
        finally_clause => {
            type: Finally,
            token: self,
            roles: [Finally],
            children: ["compound_statement"],
        },
        throw_expression => {
            type: Throw,
            roles: [Throw],
        },
        compound_statement => {
            type: Block,
            token: self,
            roles: [Body],
        },
        colon_block => {
            type: Block,
            roles: [Body],
        },
        declaration_list => {
            type: Block,
            roles: [Body],
        },
        property_declaration => {
            type: Field,
            roles: [Member],
            children: ["attribute_list", "type"],
        },
        property_element => {
            type: Field,
            token: self,
            roles: [Member],
            children: ["expression", "variable_name"],
        },
        property_hook => {
            type: Method,
            roles: [Member],
            children: ["attribute_list", "compound_statement", "expression", "final_modifier", "formal_parameters", "reference_modifier"],
        },
        property_hook_list => {
            type: Synthetic,
            token: self,
        },
        scoped_property_access_expression => {
            type: Synthetic,
            token: self,
            children: ["array_creation_expression", "cast_expression", "class_constant_access_expression", "dynamic_variable_name", "encapsed_string", "function_call_expression", "heredoc", "member_access_expression", "member_call_expression", "name", "nowdoc", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "object_creation_expression", "parenthesized_expression", "qualified_name", "relative_name", "relative_scope", "scoped_call_expression", "scoped_property_access_expression", "string", "subscript_expression", "variable_name"],
        },
        member_access_expression => {
            type: Synthetic,
            token: self,
            children: ["array_creation_expression", "cast_expression", "class_constant_access_expression", "dynamic_variable_name", "encapsed_string", "expression", "function_call_expression", "heredoc", "member_access_expression", "member_call_expression", "name", "nowdoc", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "object_creation_expression", "parenthesized_expression", "qualified_name", "relative_name", "scoped_call_expression", "scoped_property_access_expression", "string", "subscript_expression", "variable_name"],
        },
        nullsafe_member_access_expression => {
            type: Synthetic,
            token: self,
            children: ["array_creation_expression", "cast_expression", "class_constant_access_expression", "dynamic_variable_name", "encapsed_string", "expression", "function_call_expression", "heredoc", "member_access_expression", "member_call_expression", "name", "nowdoc", "nullsafe_member_access_expression", "nullsafe_member_call_expression", "object_creation_expression", "parenthesized_expression", "qualified_name", "relative_name", "scoped_call_expression", "scoped_property_access_expression", "string", "subscript_expression", "variable_name"],
        },
        const_declaration => {
            type: Variable,
            token: self,
            roles: [Declaration, Constant],
            children: ["attribute_list", "type"],
        },
        const_element => {
            type: Synthetic,
        },
        static_variable_declaration => {
            type: Variable,
            roles: [Variable, Declaration, Static],
            children: ["expression", "variable_name"],
        },
        function_static_declaration => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration, Static],
        },
        array_creation_expression => {
            type: List,
            token: self,
            roles: [Literal],
        },
        array_element_initializer => {
            type: KeyValue,
            roles: [Key, Value],
        },
        list_literal => {
            type: List,
            token: self,
        },
        pair => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
        },
        subscript_expression => {
            type: Index,
            token: self,
            roles: [Index],
        },
        attribute => {
            type: Attribute,
            token: self,
            roles: [Attribute],
            children: ["arguments"],
        },
        attribute_group => {
            type: Attribute,
            roles: [Attribute],
        },
        attribute_list => {
            type: Synthetic,
            token: self,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        cast_expression => {
            type: Cast,
            token: self,
            children: ["cast_type", "clone_expression", "error_suppression_expression", "include_expression", "include_once_expression", "primary_expression", "unary_op_expression"],
        },
        cast_type => {
            type: Synthetic,
        },
        yield_expression => {
            type: Yield,
            roles: [Yield],
        },
        qualified_name => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["namespace_name"],
        },
        relative_name => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["namespace", "namespace_name"],
        },
        visibility_modifier => {
            type: Synthetic,
            token: self,
        },
        final_modifier => {
            type: Synthetic,
            token: self,
        },
        abstract_modifier => {
            type: Synthetic,
            token: self,
        },
        readonly_modifier => {
            type: Synthetic,
            token: self,
        },
        reference_modifier => {
            type: Synthetic,
        },
        static_modifier => {
            type: Synthetic,
            token: self,
        },
        var_modifier => {
            type: Synthetic,
        },
        abstract => {
            type: Synthetic,
            token: self,
        },
        and => {
            type: Synthetic,
        },
        array => {
            type: Synthetic,
            token: self,
        },
        as => {
            type: Synthetic,
        },
        bool => {
            type: Synthetic,
            token: self,
        },
        bottom_type => {
            type: Synthetic,
        },
        break => {
            type: Synthetic,
            token: self,
        },
        callable => {
            type: Synthetic,
        },
        case => {
            type: Synthetic,
            token: self,
        },
        catch => {
            type: Synthetic,
        },
        class => {
            type: Synthetic,
            token: self,
        },
        clone => {
            type: Synthetic,
        },
        const => {
            type: Synthetic,
            token: self,
        },
        continue => {
            type: Synthetic,
            token: self,
        },
        declare => {
            type: Synthetic,
        },
        default => {
            type: Synthetic,
            token: self,
        },
        do => {
            type: Synthetic,
        },
        echo => {
            type: Synthetic,
            token: self,
        },
        else => {
            type: Synthetic,
        },
        elseif => {
            type: Synthetic,
            token: self,
        },
        encoding => {
            type: Synthetic,
        },
        enddeclare => {
            type: Synthetic,
            token: self,
        },
        endfor => {
            type: Synthetic,
        },
        endforeach => {
            type: Synthetic,
            token: self,
        },
        endif => {
            type: Synthetic,
        },
        endswitch => {
            type: Synthetic,
            token: self,
        },
        endwhile => {
            type: Synthetic,
        },
        enum => {
            type: Synthetic,
            token: self,
        },
        escape_sequence => {
            type: Synthetic,
        },
        exit => {
            type: Synthetic,
            token: self,
        },
        extends => {
            type: Synthetic,
        },
        final => {
            type: Synthetic,
            token: self,
        },
        finally => {
            type: Synthetic,
            token: self,
        },
        fn => {
            type: Synthetic,
        },
        for => {
            type: Synthetic,
            token: self,
        },
        foreach => {
            type: Synthetic,
        },
        from => {
            type: Synthetic,
            token: self,
        },
        function => {
            type: Synthetic,
        },
        global => {
            type: Synthetic,
            token: self,
        },
        goto => {
            type: Synthetic,
        },
        heredoc_end => {
            type: Synthetic,
            token: self,
        },
        heredoc_start => {
            type: Synthetic,
        },
        heredoc_body => {
            type: Synthetic,
            token: self,
        },
        nowdoc_body => {
            type: Synthetic,
            token: self,
        },
        nowdoc_string => {
            type: Synthetic,
        },
        if => {
            type: Synthetic,
            token: self,
        },
        implements => {
            type: Synthetic,
        },
        include => {
            type: Synthetic,
            token: self,
        },
        include_once => {
            type: Synthetic,
        },
        instanceof => {
            type: Synthetic,
            token: self,
        },
        insteadof => {
            type: Synthetic,
        },
        int => {
            type: Synthetic,
            token: self,
        },
        interface => {
            type: Synthetic,
            token: self,
        },
        iterable => {
            type: Synthetic,
        },
        list => {
            type: Synthetic,
            token: self,
        },
        match => {
            type: Synthetic,
        },
        mixed => {
            type: Synthetic,
            token: self,
        },
        namespace => {
            type: Synthetic,
        },
        new => {
            type: Synthetic,
            token: self,
        },
        operation => {
            type: Synthetic,
        },
        or => {
            type: Synthetic,
            token: self,
        },
        parent => {
            type: Identifier,
            roles: [Reference],
        },
        php_tag => {
            type: Synthetic,
            token: self,
        },
        print => {
            type: Synthetic,
        },
        private => {
            type: Synthetic,
            token: self,
        },
        protected => {
            type: Synthetic,
        },
        public => {
            type: Synthetic,
            token: self,
        },
        readonly => {
            type: Synthetic,
        },
        require => {
            type: Synthetic,
            token: self,
        },
        require_once => {
            type: Synthetic,
        },
        return => {
            type: Synthetic,
            token: self,
        },
        self => {
            type: Identifier,
            roles: [Reference],
        },
        static => {
            type: Synthetic,
            token: self,
        },
        strict_types => {
            type: Synthetic,
        },
        switch => {
            type: Synthetic,
        },
        throw => {
            type: Synthetic,
            token: self,
        },
        ticks => {
            type: Synthetic,
        },
        trait => {
            type: Synthetic,
            token: self,
        },
        try => {
            type: Synthetic,
            token: self,
        },
        unset => {
            type: Synthetic,
        },
        use => {
            type: Synthetic,
            token: self,
        },
        void => {
            type: Synthetic,
            token: self,
        },
        while => {
            type: Synthetic,
        },
        xor => {
            type: Synthetic,
            token: self,
        },
        yield => {
            type: Synthetic,
        },
        expression => {
            type: Synthetic,
        },
        literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        primary_expression => {
            type: Synthetic,
        },
        statement => {
            type: Synthetic,
            token: self,
        },
        type => {
            type: Synthetic,
        },
        expression_statement => {
            type: Synthetic,
            token: self,
        },
        empty_statement => {
            type: Synthetic,
        },
        parenthesized_expression => {
            type: Synthetic,
        },
        sequence_expression => {
            type: Synthetic,
        },
        base_clause => {
            type: Synthetic,
            token: self,
        },
        clone_expression => {
            type: Synthetic,
            token: self,
        },
        declare_statement => {
            type: Synthetic,
        },
        declare_directive => {
            type: Synthetic,
            token: self,
        },
        disjunctive_normal_form_type => {
            type: Synthetic,
        },
        echo_statement => {
            type: Synthetic,
            token: self,
        },
        error_suppression_expression => {
            type: Synthetic,
            token: self,
        },
        exit_statement => {
            type: Synthetic,
        },
        global_declaration => {
            type: Synthetic,
            token: self,
        },
        goto_statement => {
            type: Synthetic,
            token: self,
        },
        intersection_type => {
            type: Synthetic,
        },
        labeled_statement => {
            type: Synthetic,
        },
        named_label_statement => {
            type: Synthetic,
            token: self,
        },
        named_type => {
            type: Synthetic,
        },
        optional_type => {
            type: Synthetic,
        },
        primitive_type => {
            type: Synthetic,
            token: self,
        },
        print_intrinsic => {
            type: Synthetic,
        },
        relative_scope => {
            type: Synthetic,
        },
        shell_command_expression => {
            type: Synthetic,
            token: self,
        },
        string_content => {
            type: Synthetic,
        },
        type_list => {
            type: Synthetic,
            token: self,
        },
        union_type => {
            type: Synthetic,
            token: self,
        },
        unset_statement => {
            type: Synthetic,
        },
        use_as_clause => {
            type: Synthetic,
        },
        use_declaration => {
            type: Synthetic,
            token: self,
        },
        use_instead_of_clause => {
            type: Synthetic,
        },
        use_list => {
            type: Synthetic,
            token: self,
        },
        variadic_placeholder => {
            type: Synthetic,
        },
        variadic_unpacking => {
            type: Spread,
            token: self,
            roles: [Spread],
        },
        by_ref => {
            type: Synthetic,
            token: self,
        },
    }
};
