//! GENERATED by uastmap2rs — transpiled from `ssh_config.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `ssh_config` language.
pub static SSH_CONFIG: LanguageMapping = uast_language! {
    name: "ssh_config",
    extensions: [".ssh_config"],
    files: ["ssh_config"],
    rules: {
        config => {
            type: File,
        },
        host_declaration => {
            type: Block,
            token: self,
            roles: [Body],
        },
        match_declaration => {
            type: Block,
            roles: [Body],
        },
        parameter => {
            type: KeyValue,
            roles: [Key, Value],
        },
        condition => {
            type: Synthetic,
            token: self,
        },
        pattern => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        bytes => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        time => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        variable => {
            type: Identifier,
            roles: [Reference],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        yes => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        no => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        Host => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Match => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Hostname => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        User => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Port => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        IdentityFile => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ForwardAgent => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Compression => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Include => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        AddKeysToAgent => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        AddressFamily => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        BatchMode => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        BindAddress => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        BindInterface => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CASignatureAlgorithms => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CanonicalDomains => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CanonicalizeFallbackLocal => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CanonicalizeHostname => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CanonicalizeMaxDots => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CanonicalizePermittedCNAMEs => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CertificateFile => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ChallengeResponseAuthentication => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        CheckHostIP => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Ciphers => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ClearAllForwardings => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ConnectTimeout => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ConnectionAttempts => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ControlMaster => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ControlPath => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ControlPersist => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        DynamicForward => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        EnableEscapeCommandline => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        EnableSSHKeysign => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        EscapeChar => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ExitOnForwardFailure => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        FingerprintHash => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ForkAfterAuthentication => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ForwardX11 => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ForwardX11Timeout => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ForwardX11Trusted => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        GSSAPIAuthentication => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        GSSAPIDelegateCredentials => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        GlobalKnownHostsFile => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        HashKnownHosts => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        HostKeyAlgorithms => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        HostKeyAlias => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        HostbasedAcceptedAlgorithms => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        HostbasedAuthentication => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        HostbasedKeyTypes => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        IPQoS => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        IdentitiesOnly => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        IdentityAgent => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        IgnoreUnknown => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        KbdInteractiveAuthentication => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        KexAlgorithms => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        KnownHostsCommand => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        LocalCommand => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        LocalForward => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        LogLevel => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        LogVerbose => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        MACs => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        NoHostAuthenticationForLocalhost => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        NumberOfPasswordPrompts => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PKCS11Provider => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PasswordAuthentication => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PermitLocalCommand => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PermitRemoteOpen => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PreferredAuthentications => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ProxyCommand => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ProxyJump => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ProxyUseFdpass => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PubkeyAcceptedAlgorithms => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PubkeyAcceptedKeyTypes => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        PubkeyAuthentication => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        RekeyLimit => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        RemoteCommand => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        RemoteForward => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        RequestTTY => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        RequiredRSASize => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        RevokedHostKeys => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        SSH_AUTH_SOCK => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        SecurityKeyProvider => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        SendEnv => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ServerAliveCountMax => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ServerAliveInterval => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        SessionType => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        SetEnv => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        StdinNull => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        StreamLocalBindMask => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        StreamLocalBindUnlink => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        StrictHostKeyChecking => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        SyslogFacility => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        TCPKeepAlive => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Tag => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        Tunnel => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        TunnelDevice => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        UpdateHostKeys => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        UseKeychain => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        UserKnownHostsFile => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        VerifyHostKeyDNS => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        VisualHostKey => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        XAuthLocation => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        all => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        always => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        any => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        ask => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        auto => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        autoask => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        none => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        off => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        force => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        confirm => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        default => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        authentication => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        canonical => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        exec => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        final => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        host => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        localnetwork => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        localuser => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        originalhost => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        tagged => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        user => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        inet => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        inet6 => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        ethernet => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        cipher => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        kex => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        key_sig => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        mac => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        sig => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        md5 => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        sha256 => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        ipqos => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        facility => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        verbosity => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        subsystem => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        token => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        unbound => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        uri => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
    }
};
