//! GENERATED by uastmap2rs — transpiled from `c_sharp.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `csharp` language.
pub static CSHARP: LanguageMapping = uast_language! {
    name: "csharp",
    extensions: [".cs"],
    rules: {
        compilation_unit => {
            type: File,
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        using_directive => {
            type: Import,
            roles: [Import],
            children: ["qualified_name", "identifier", "alias_qualified_name", "generic_name"],
        },
        qualified_name => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["alias_qualified_name", "generic_name", "identifier", "qualified_name"],
        },
        namespace_declaration => {
            type: Namespace,
            token: self,
            roles: [Module],
            children: ["alias_qualified_name", "declaration_list", "generic_name", "identifier", "qualified_name"],
        },
        file_scoped_namespace_declaration => {
            type: Namespace,
            token: self,
            roles: [Module],
            children: ["alias_qualified_name", "generic_name", "identifier", "qualified_name"],
        },
        class_declaration => {
            type: Class,
            roles: [Class, Declaration],
            children: ["declaration_list", "identifier"],
        },
        class => {
            type: Synthetic,
        },
        interface_declaration => {
            type: Interface,
            token: self,
            roles: [Interface, Declaration],
            children: ["declaration_list", "identifier", "type_parameter_list"],
        },
        interface => {
            type: Synthetic,
        },
        struct_declaration => {
            type: Struct,
            token: self,
            roles: [Struct, Declaration],
            children: ["declaration_list", "identifier"],
        },
        struct => {
            type: Synthetic,
        },
        record_declaration => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["declaration_list", "identifier"],
        },
        record => {
            type: Synthetic,
        },
        enum_declaration => {
            type: Enum,
            roles: [Enum, Declaration],
            children: ["enum_member_declaration_list", "identifier"],
        },
        enum => {
            type: Synthetic,
        },
        enum_member_declaration => {
            type: EnumMember,
            token: child("identifier"),
            roles: [Member, Declaration],
            children: ["expression", "identifier"],
        },
        enum_member_declaration_list => {
            type: Synthetic,
        },
        method_declaration => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
            children: ["arrow_expression_clause", "block", "identifier", "parameter_list", "type", "type_parameter_list"],
        },
        method => {
            type: Synthetic,
        },
        constructor_declaration => {
            type: Method,
            roles: [Function, Declaration],
            children: ["arrow_expression_clause", "block", "identifier", "parameter_list"],
        },
        destructor_declaration => {
            type: Method,
            token: self,
            roles: [Function, Declaration],
            children: ["arrow_expression_clause", "block", "identifier", "parameter_list"],
        },
        constructor_initializer => {
            type: Synthetic,
            token: self,
        },
        constructor_constraint => {
            type: Synthetic,
            token: self,
        },
        local_function_statement => {
            type: Function,
            roles: [Function, Declaration],
            children: ["arrow_expression_clause", "block", "identifier", "parameter_list", "type", "type_parameter_list"],
        },
        lambda_expression => {
            type: Lambda,
            roles: [Lambda],
            children: ["block", "expression", "implicit_parameter", "parameter_list", "type"],
        },
        anonymous_method_expression => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["parameter_list"],
        },
        parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["identifier", "type"],
        },
        parameter_list => {
            type: Synthetic,
            token: self,
            children: ["parameter"],
        },
        implicit_parameter => {
            type: Parameter,
            roles: [Parameter],
        },
        type_parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["identifier"],
        },
        type_parameter_list => {
            type: Synthetic,
            token: self,
        },
        type_parameter_constraint => {
            type: Synthetic,
            token: self,
            children: ["type"],
        },
        type_parameter_constraints_clause => {
            type: Synthetic,
        },
        bracketed_parameter_list => {
            type: Synthetic,
            children: ["parameter"],
        },
        block => {
            type: Block,
            token: self,
            roles: [Body],
        },
        declaration_list => {
            type: Block,
            token: self,
            roles: [Body],
        },
        if_statement => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["expression", "statement"],
        },
        if => {
            type: Synthetic,
        },
        else => {
            type: Synthetic,
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
            children: ["expression", "statement", "variable_declaration"],
        },
        for => {
            type: Synthetic,
            token: self,
        },
        foreach_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["expression", "identifier", "statement", "tuple_pattern", "type"],
        },
        foreach => {
            type: Synthetic,
        },
        while_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["expression", "statement"],
        },
        while => {
            type: Synthetic,
            token: self,
        },
        do_statement => {
            type: Loop,
            roles: [Loop],
            children: ["expression", "statement"],
        },
        do => {
            type: Synthetic,
            token: self,
        },
        switch_statement => {
            type: Switch,
            token: self,
            children: ["expression", "switch_body", "tuple_expression"],
        },
        switch => {
            type: Synthetic,
            token: self,
        },
        switch_body => {
            type: Synthetic,
            token: self,
        },
        switch_section => {
            type: Case,
            roles: [Branch],
        },
        switch_expression => {
            type: Switch,
        },
        switch_expression_arm => {
            type: Case,
            token: self,
            roles: [Branch],
        },
        case => {
            type: Synthetic,
            token: self,
        },
        default => {
            type: Synthetic,
        },
        return_statement => {
            type: Return,
            roles: [Return],
        },
        return => {
            type: Synthetic,
            token: self,
        },
        break_statement => {
            type: Break,
            token: self,
            roles: [Break],
        },
        break => {
            type: Synthetic,
            token: self,
        },
        continue_statement => {
            type: Continue,
            roles: [Continue],
        },
        continue => {
            type: Synthetic,
            token: self,
        },
        try_statement => {
            type: Try,
            roles: [Try],
            children: ["block"],
        },
        try => {
            type: Synthetic,
            token: self,
        },
        catch_clause => {
            type: Catch,
            roles: [Catch],
            children: ["block"],
        },
        catch => {
            type: Synthetic,
        },
        catch_declaration => {
            type: Synthetic,
            token: self,
            children: ["identifier", "type"],
        },
        catch_filter_clause => {
            type: Synthetic,
        },
        finally_clause => {
            type: Finally,
            roles: [Finally],
        },
        finally => {
            type: Synthetic,
            token: self,
        },
        throw_statement => {
            type: Throw,
            token: self,
            roles: [Throw],
        },
        throw_expression => {
            type: Throw,
            roles: [Throw],
        },
        throw => {
            type: Synthetic,
            token: self,
        },
        yield_statement => {
            type: Yield,
            roles: [Yield],
        },
        yield => {
            type: Synthetic,
            token: self,
        },
        await_expression => {
            type: Await,
            roles: [Await],
        },
        await => {
            type: Synthetic,
            token: self,
        },
        binary_expression => {
            type: BinaryOp,
            roles: [Operator],
            children: ["expression"],
        },
        unary_expression => {
            type: UnaryOp,
            roles: [Operator],
            children: ["expression"],
        },
        prefix_unary_expression => {
            type: UnaryOp,
            roles: [Operator],
        },
        postfix_unary_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
        },
        assignment_expression => {
            type: Assignment,
            roles: [Assignment],
            children: ["expression", "lvalue_expression"],
        },
        invocation_expression => {
            type: Call,
            roles: [Call],
            children: ["argument_list", "expression"],
        },
        literal => {
            type: Literal,
            roles: [Literal],
        },
        boolean_literal => {
            type: Literal,
            roles: [Literal],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        real_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        character_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        character_literal_content => {
            type: Synthetic,
            token: self,
        },
        string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_literal_content => {
            type: Synthetic,
        },
        string_literal_encoding => {
            type: Synthetic,
            token: self,
        },
        verbatim_string_literal => {
            type: Literal,
            roles: [Literal],
        },
        raw_string_literal => {
            type: Literal,
            roles: [Literal],
        },
        null_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        default_expression => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["type"],
        },
        variable_declaration => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
            children: ["type"],
        },
        variable_declarator => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["identifier"],
        },
        local_declaration_statement => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
        },
        field_declaration => {
            type: Field,
            roles: [Member],
        },
        field => {
            type: Synthetic,
            token: self,
        },
        event_field_declaration => {
            type: Field,
            roles: [Member],
        },
        event_declaration => {
            type: Field,
            token: self,
            roles: [Member],
            children: ["accessor_list", "identifier", "type"],
        },
        property_declaration => {
            type: Property,
            token: self,
            roles: [Member],
            children: ["accessor_list", "arrow_expression_clause", "expression", "identifier", "type"],
        },
        property => {
            type: Synthetic,
        },
        property_pattern_clause => {
            type: Pattern,
            roles: [Pattern],
        },
        indexer_declaration => {
            type: Index,
            token: self,
            roles: [Index],
            children: ["accessor_list", "arrow_expression_clause", "bracketed_parameter_list", "type"],
        },
        accessor_declaration => {
            type: Synthetic,
            token: child("identifier"),
            children: ["add", "arrow_expression_clause", "block", "get", "identifier", "init", "remove", "set"],
        },
        accessor_list => {
            type: Synthetic,
        },
        get => {
            type: Synthetic,
        },
        set => {
            type: Synthetic,
            token: self,
        },
        init => {
            type: Synthetic,
        },
        add => {
            type: Synthetic,
            token: self,
        },
        remove => {
            type: Synthetic,
        },
        attribute => {
            type: Attribute,
            token: self,
            roles: [Attribute],
            children: ["alias_qualified_name", "generic_name", "identifier", "qualified_name"],
        },
        attribute_list => {
            type: Synthetic,
        },
        attribute_argument => {
            type: Synthetic,
        },
        attribute_argument_list => {
            type: Synthetic,
            token: self,
        },
        attribute_target_specifier => {
            type: Synthetic,
            token: self,
        },
        global_attribute => {
            type: Attribute,
            roles: [Attribute],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        argument => {
            type: Synthetic,
            token: self,
            children: ["identifier"],
        },
        argument_list => {
            type: Synthetic,
        },
        bracketed_argument_list => {
            type: Synthetic,
            token: self,
        },
        type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        predefined_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        array_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["type"],
        },
        nullable_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["type"],
        },
        pointer_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["type"],
        },
        tuple_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        ref_type => {
            type: Synthetic,
            children: ["type"],
        },
        scoped_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["type"],
        },
        function_pointer_type => {
            type: TypeAnnotation,
            roles: [Type],
            children: ["type"],
        },
        generic_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        alias_qualified_name => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["generic_name", "identifier"],
        },
        type_argument_list => {
            type: Synthetic,
            token: self,
        },
        implicit_type => {
            type: Synthetic,
        },
        pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        and_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["pattern"],
        },
        or_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["pattern"],
        },
        negated_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        constant_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        declaration_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["identifier", "type"],
        },
        var_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["identifier"],
        },
        type_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["type"],
        },
        recursive_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["identifier", "type"],
        },
        relational_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        parenthesized_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        positional_pattern_clause => {
            type: Pattern,
            roles: [Pattern],
        },
        list_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["identifier"],
        },
        subpattern => {
            type: Pattern,
            roles: [Pattern],
        },
        is_pattern_expression => {
            type: Pattern,
            roles: [Pattern],
            children: ["expression", "pattern"],
        },
        tuple_expression => {
            type: Tuple,
        },
        tuple_element => {
            type: Tuple,
            token: self,
            children: ["identifier", "type"],
        },
        tuple_pattern => {
            type: Tuple,
            token: self,
            children: ["identifier"],
        },
        array_creation_expression => {
            type: List,
            token: self,
            children: ["type"],
        },
        array_rank_specifier => {
            type: Synthetic,
        },
        implicit_array_creation_expression => {
            type: List,
        },
        object_creation_expression => {
            type: Call,
            roles: [Call],
            children: ["argument_list", "initializer_expression", "type"],
        },
        implicit_object_creation_expression => {
            type: Call,
            token: self,
            roles: [Call],
        },
        anonymous_object_creation_expression => {
            type: Call,
            roles: [Call],
        },
        initializer_expression => {
            type: Synthetic,
        },
        cast_expression => {
            type: Cast,
            token: self,
            children: ["expression", "type"],
        },
        as_expression => {
            type: Cast,
            token: self,
            children: ["expression", "type"],
        },
        is_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["expression", "type"],
        },
        element_access_expression => {
            type: Index,
            token: self,
            roles: [Index],
            children: ["bracketed_argument_list", "expression"],
        },
        element_binding_expression => {
            type: Synthetic,
        },
        member_access_expression => {
            type: Synthetic,
            token: self,
            children: ["expression", "identifier"],
        },
        member_binding_expression => {
            type: Synthetic,
            children: ["generic_name", "identifier"],
        },
        conditional_access_expression => {
            type: Synthetic,
            children: ["expression"],
        },
        range_expression => {
            type: Slice,
            token: self,
        },
        parenthesized_expression => {
            type: Synthetic,
        },
        conditional_expression => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["expression"],
        },
        checked_expression => {
            type: Synthetic,
        },
        checked_statement => {
            type: Synthetic,
            token: self,
        },
        checked => {
            type: Synthetic,
        },
        unchecked => {
            type: Synthetic,
            token: self,
        },
        statement => {
            type: Synthetic,
        },
        expression_statement => {
            type: Synthetic,
        },
        empty_statement => {
            type: Synthetic,
            token: self,
        },
        global_statement => {
            type: Synthetic,
            token: self,
        },
        labeled_statement => {
            type: Synthetic,
            token: self,
        },
        goto_statement => {
            type: Synthetic,
        },
        goto => {
            type: Synthetic,
        },
        lock_statement => {
            type: Synthetic,
            token: self,
        },
        lock => {
            type: Synthetic,
        },
        fixed_statement => {
            type: Synthetic,
            token: self,
        },
        fixed => {
            type: Synthetic,
        },
        using_statement => {
            type: Synthetic,
            token: self,
            children: ["statement"],
        },
        unsafe_statement => {
            type: Block,
            token: self,
            roles: [Body],
        },
        unsafe => {
            type: Synthetic,
        },
        expression => {
            type: Synthetic,
            token: self,
        },
        lvalue_expression => {
            type: Synthetic,
            token: self,
        },
        non_lvalue_expression => {
            type: Synthetic,
        },
        declaration => {
            type: Synthetic,
        },
        declaration_expression => {
            type: Synthetic,
            children: ["identifier", "type"],
        },
        type_declaration => {
            type: Synthetic,
        },
        arrow_expression_clause => {
            type: Synthetic,
        },
        delegate_declaration => {
            type: Synthetic,
            children: ["identifier", "parameter_list", "type", "type_parameter_list"],
        },
        delegate => {
            type: Synthetic,
            token: self,
        },
        base_list => {
            type: Synthetic,
            token: self,
        },
        primary_constructor_base_type => {
            type: Synthetic,
            children: ["identifier", "qualified_name"],
        },
        modifier => {
            type: Synthetic,
        },
        public => {
            type: Synthetic,
        },
        private => {
            type: Synthetic,
            token: self,
        },
        protected => {
            type: Synthetic,
            token: self,
        },
        internal => {
            type: Synthetic,
            token: self,
        },
        static => {
            type: Synthetic,
            token: self,
        },
        abstract => {
            type: Synthetic,
        },
        virtual => {
            type: Synthetic,
            token: self,
        },
        override => {
            type: Synthetic,
            token: self,
        },
        sealed => {
            type: Synthetic,
            token: self,
        },
        readonly => {
            type: Synthetic,
        },
        const => {
            type: Synthetic,
        },
        volatile => {
            type: Synthetic,
        },
        extern => {
            type: Synthetic,
            token: self,
        },
        async => {
            type: Synthetic,
        },
        new => {
            type: Synthetic,
        },
        partial => {
            type: Synthetic,
        },
        explicit => {
            type: Synthetic,
        },
        implicit => {
            type: Synthetic,
        },
        required => {
            type: Synthetic,
            token: self,
        },
        file => {
            type: Synthetic,
        },
        scoped => {
            type: Synthetic,
        },
        ref => {
            type: Synthetic,
            token: self,
        },
        out => {
            type: Synthetic,
        },
        in => {
            type: Synthetic,
            token: self,
        },
        params => {
            type: Synthetic,
            token: self,
        },
        this => {
            type: Synthetic,
        },
        base => {
            type: Synthetic,
        },
        typeof_expression => {
            type: Synthetic,
            token: self,
            children: ["type"],
        },
        typeof => {
            type: Synthetic,
            token: self,
        },
        sizeof_expression => {
            type: Synthetic,
            token: self,
            children: ["type"],
        },
        sizeof => {
            type: Synthetic,
            token: self,
        },
        nameof_expression => {
            type: Synthetic,
        },
        ref_expression => {
            type: Synthetic,
            token: self,
        },
        refvalue_expression => {
            type: Synthetic,
            children: ["expression", "type"],
        },
        reftype_expression => {
            type: Synthetic,
            token: self,
        },
        makeref_expression => {
            type: Synthetic,
        },
        stackalloc_expression => {
            type: Synthetic,
            children: ["type"],
        },
        implicit_stackalloc_expression => {
            type: Synthetic,
            token: self,
        },
        stackalloc => {
            type: Synthetic,
        },
        operator_declaration => {
            type: Method,
            token: self,
            roles: [Function, Declaration],
            children: ["arrow_expression_clause", "block", "parameter_list", "type"],
        },
        conversion_operator_declaration => {
            type: Method,
            token: self,
            roles: [Function, Declaration],
            children: ["arrow_expression_clause", "block", "parameter_list", "type"],
        },
        operator => {
            type: Synthetic,
        },
        with_expression => {
            type: Synthetic,
        },
        with_initializer => {
            type: Synthetic,
            token: self,
        },
        with => {
            type: Synthetic,
        },
        interpolated_string_expression => {
            type: Literal,
            roles: [Literal],
        },
        interpolation => {
            type: Synthetic,
            token: self,
        },
        interpolation_alignment_clause => {
            type: Synthetic,
        },
        interpolation_format_clause => {
            type: Synthetic,
            token: self,
        },
        interpolation_brace => {
            type: Synthetic,
        },
        interpolation_quote => {
            type: Synthetic,
            token: self,
        },
        interpolation_start => {
            type: Synthetic,
        },
        escape_sequence => {
            type: Synthetic,
        },
        raw_string_content => {
            type: Synthetic,
            token: self,
        },
        raw_string_start => {
            type: Synthetic,
            token: self,
        },
        raw_string_end => {
            type: Synthetic,
        },
        string_content => {
            type: Synthetic,
        },
        query_expression => {
            type: Synthetic,
        },
        from_clause => {
            type: Synthetic,
            children: ["identifier", "type"],
        },
        where_clause => {
            type: Synthetic,
        },
        select_clause => {
            type: Synthetic,
        },
        group_clause => {
            type: Synthetic,
            token: self,
        },
        order_by_clause => {
            type: Synthetic,
            token: self,
        },
        let_clause => {
            type: Synthetic,
            token: self,
        },
        join_clause => {
            type: Synthetic,
            token: self,
            children: ["type"],
        },
        join_into_clause => {
            type: Synthetic,
        },
        from => {
            type: Synthetic,
            token: self,
        },
        where => {
            type: Synthetic,
        },
        select => {
            type: Synthetic,
        },
        group => {
            type: Synthetic,
            token: self,
        },
        orderby => {
            type: Synthetic,
            token: self,
        },
        ascending => {
            type: Synthetic,
        },
        descending => {
            type: Synthetic,
        },
        let => {
            type: Synthetic,
        },
        join => {
            type: Synthetic,
            token: self,
        },
        on => {
            type: Synthetic,
        },
        equals => {
            type: Synthetic,
            token: self,
        },
        into => {
            type: Synthetic,
            token: self,
        },
        by => {
            type: Synthetic,
        },
        explicit_interface_specifier => {
            type: Synthetic,
            token: self,
        },
        parenthesized_variable_designation => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["identifier"],
        },
        discard => {
            type: Synthetic,
        },
        when_clause => {
            type: Synthetic,
            token: self,
        },
        when => {
            type: Synthetic,
            token: self,
        },
        extern_alias_directive => {
            type: Import,
            token: self,
            roles: [Import],
            children: ["identifier"],
        },
        alias => {
            type: Synthetic,
        },
        preproc_if => {
            type: Synthetic,
            children: ["expression"],
        },
        preproc_elif => {
            type: Synthetic,
        },
        preproc_else => {
            type: Synthetic,
            token: self,
        },
        preproc_if_in_attribute_list => {
            type: Synthetic,
            token: self,
            children: ["expression"],
        },
        preproc_define => {
            type: Synthetic,
            token: self,
        },
        preproc_undef => {
            type: Synthetic,
        },
        preproc_line => {
            type: Synthetic,
        },
        preproc_error => {
            type: Synthetic,
            token: self,
        },
        preproc_warning => {
            type: Synthetic,
            token: self,
        },
        preproc_pragma => {
            type: Synthetic,
        },
        preproc_nullable => {
            type: Synthetic,
            token: self,
        },
        preproc_region => {
            type: Synthetic,
            token: self,
            children: ["preproc_arg"],
        },
        preproc_endregion => {
            type: Synthetic,
            children: ["preproc_arg"],
        },
        preproc_arg => {
            type: Synthetic,
        },
        namespace => {
            type: Synthetic,
            token: self,
        },
        using => {
            type: Synthetic,
        },
        event => {
            type: Synthetic,
            token: self,
        },
        as => {
            type: Synthetic,
            token: self,
        },
        is => {
            type: Synthetic,
        },
        not => {
            type: Synthetic,
            token: self,
        },
        and => {
            type: Synthetic,
            token: self,
        },
        or => {
            type: Synthetic,
        },
        var => {
            type: Synthetic,
            token: self,
        },
        notnull => {
            type: Synthetic,
        },
        unmanaged => {
            type: Synthetic,
        },
        managed => {
            type: Synthetic,
        },
        global => {
            type: Synthetic,
            token: self,
        },
        module => {
            type: Synthetic,
        },
        type => {
            type: Synthetic,
        },
        typevar => {
            type: Synthetic,
        },
        param => {
            type: Synthetic,
        },
        annotations => {
            type: Synthetic,
        },
        assembly => {
            type: Synthetic,
            token: self,
        },
        warning => {
            type: Synthetic,
            token: self,
        },
        warnings => {
            type: Synthetic,
        },
        checksum => {
            type: Synthetic,
            token: self,
        },
        hidden => {
            type: Synthetic,
        },
        disable => {
            type: Synthetic,
            token: self,
        },
        enable => {
            type: Synthetic,
            token: self,
        },
        restore => {
            type: Synthetic,
        },
        shebang_directive => {
            type: Synthetic,
        },
        calling_convention => {
            type: Synthetic,
        },
        Cdecl => {
            type: Synthetic,
            token: self,
        },
        Fastcall => {
            type: Synthetic,
        },
        Stdcall => {
            type: Synthetic,
            token: self,
        },
        Thiscall => {
            type: Synthetic,
        },
        function_pointer_parameter => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["type"],
        },
        __makeref => {
            type: Synthetic,
            token: self,
        },
        __reftype => {
            type: Synthetic,
        },
        __refvalue => {
            type: Synthetic,
            token: self,
        },
    }
};
