//! GENERATED by uastmap2rs — transpiled from `cpp.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `cpp` language.
pub static CPP: LanguageMapping = uast_language! {
    name: "cpp",
    extensions: [".cpp", ".cc", ".cxx", ".hpp", ".hxx", ".h"],
    rules: {
        translation_unit => {
            type: File,
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        field_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Member],
        },
        namespace_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Module],
        },
        type_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        statement_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        qualified_identifier => {
            type: Identifier,
            roles: [Name],
            children: ["decltype", "dependent_name", "destructor_name", "field_identifier", "identifier", "namespace_identifier", "operator_cast", "operator_name", "pointer_type_declarator", "qualified_identifier", "template", "template_function", "template_method", "template_type", "type_identifier"],
        },
        destructor_name => {
            type: Identifier,
            token: self,
            roles: [Name, Function],
        },
        operator_name => {
            type: Identifier,
            token: self,
            roles: [Operator, Name],
        },
        preproc_include => {
            type: Import,
            roles: [Import],
            children: ["call_expression", "identifier", "string_literal", "system_lib_string"],
        },
        system_lib_string => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        import_declaration => {
            type: Import,
            token: self,
            roles: [Import],
            children: ["module_name", "module_partition", "string_literal", "system_lib_string"],
        },
        using_declaration => {
            type: Import,
            token: self,
            roles: [Import],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        null => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        nullptr => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        NULL => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        char_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        raw_string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["raw_string_delimiter"],
        },
        concatenated_string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        user_defined_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        literal_suffix => {
            type: Synthetic,
            token: self,
        },
        compound_literal_expression => {
            type: Literal,
            roles: [Literal],
            children: ["initializer_list", "primitive_type", "qualified_identifier", "template_type", "type_descriptor", "type_identifier"],
        },
        binary_expression => {
            type: BinaryOp,
            roles: [Operator],
            children: ["and", "bitand", "bitor", "expression", "not_eq", "or", "preproc_defined", "xor"],
        },
        unary_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["compl", "expression", "not", "preproc_defined"],
        },
        update_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        pointer_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        conditional_expression => {
            type: If,
            roles: [Condition],
            children: ["comma_expression", "expression"],
        },
        comma_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["comma_expression", "expression"],
        },
        assignment_expression => {
            type: Assignment,
            roles: [Assignment],
            children: ["and_eq", "expression", "initializer_list", "or_eq", "xor_eq"],
        },
        subscript_expression => {
            type: Index,
            roles: [Index],
            children: ["expression", "subscript_argument_list"],
        },
        new_expression => {
            type: Call,
            roles: [Call],
            children: ["argument_list", "initializer_list", "new_declarator", "type_specifier"],
        },
        delete_expression => {
            type: Call,
            roles: [Call],
        },
        sizeof_expression => {
            type: Call,
            roles: [Call],
            children: ["expression", "type_descriptor"],
        },
        alignof_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["type_descriptor"],
        },
        call_expression => {
            type: Call,
            roles: [Call],
            children: ["argument_list", "expression", "primitive_type"],
        },
        field_expression => {
            type: Field,
            roles: [Member],
            children: ["dependent_name", "destructor_name", "expression", "field_identifier", "qualified_identifier", "template_method"],
        },
        function_definition => {
            type: Function,
            roles: [Function, Declaration],
            children: ["_declarator", "_field_declarator", "compound_statement", "operator_cast", "try_statement", "type_specifier"],
        },
        function_declarator => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["_declarator", "_field_declarator", "_type_declarator", "parameter_list"],
        },
        abstract_function_declarator => {
            type: Function,
            roles: [Function, Declaration],
            children: ["_abstract_declarator", "parameter_list"],
        },
        preproc_function_def => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["identifier", "preproc_arg", "preproc_params"],
        },
        template_function => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["identifier", "template_argument_list"],
        },
        generic_expression => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        explicit_function_specifier => {
            type: Synthetic,
        },
        template_method => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
            children: ["field_identifier", "operator_name", "template_argument_list"],
        },
        default_method_clause => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
        },
        delete_method_clause => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
        },
        lambda_expression => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["compound_statement", "lambda_capture_specifier", "lambda_declarator", "requires_clause", "template_parameter_list"],
        },
        lambda_declarator => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["parameter_list"],
        },
        lambda_capture_specifier => {
            type: Synthetic,
        },
        lambda_capture_initializer => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["expression", "identifier"],
        },
        lambda_default_capture => {
            type: Synthetic,
        },
        lambda_specifier => {
            type: Synthetic,
        },
        class_specifier => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["field_declaration_list", "qualified_identifier", "template_type", "type_identifier"],
        },
        struct_specifier => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["field_declaration_list", "qualified_identifier", "template_type", "type_identifier"],
        },
        union_specifier => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["field_declaration_list", "qualified_identifier", "template_type", "type_identifier"],
        },
        enum_specifier => {
            type: Enum,
            token: self,
            roles: [Enum, Declaration],
            children: ["enumerator_list", "primitive_type", "qualified_identifier", "sized_type_specifier", "template_type", "type_identifier"],
        },
        enumerator => {
            type: EnumMember,
            roles: [Member, Declaration],
            children: ["expression", "identifier"],
        },
        enumerator_list => {
            type: List,
            token: self,
        },
        base_class_clause => {
            type: Synthetic,
        },
        namespace_definition => {
            type: Namespace,
            token: self,
            roles: [Module],
            children: ["declaration_list", "namespace_identifier", "nested_namespace_specifier"],
        },
        namespace_alias_definition => {
            type: Namespace,
            roles: [Module],
            children: ["namespace_identifier"],
        },
        module_declaration => {
            type: Module,
            roles: [Module],
            children: ["module_name", "module_partition"],
        },
        module_name => {
            type: Identifier,
            token: self,
            roles: [Name, Module],
        },
        module_partition => {
            type: Identifier,
            roles: [Name, Module],
        },
        global_module_fragment_declaration => {
            type: Module,
            roles: [Module],
        },
        private_module_fragment_declaration => {
            type: Module,
            roles: [Module],
        },
        export_declaration => {
            type: Synthetic,
        },
        if_statement => {
            type: If,
            roles: [Condition],
            children: ["condition_clause", "else_clause", "statement"],
        },
        else_clause => {
            type: Block,
            roles: [Body],
        },
        for_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["comma_expression", "declaration", "expression", "statement"],
        },
        for_range_loop => {
            type: Loop,
            roles: [Loop],
            children: ["_declarator", "expression", "init_statement", "initializer_list", "statement", "type_specifier"],
        },
        while_statement => {
            type: Loop,
            roles: [Loop],
            children: ["condition_clause", "statement"],
        },
        do_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        switch_statement => {
            type: Switch,
            roles: [Branch],
            children: ["compound_statement", "condition_clause"],
        },
        case_statement => {
            type: Case,
            token: self,
            roles: [Branch],
            children: ["expression"],
        },
        break_statement => {
            type: Break,
            token: self,
            roles: [Break],
        },
        continue_statement => {
            type: Continue,
            token: self,
            roles: [Continue],
        },
        return_statement => {
            type: Return,
            token: self,
            roles: [Return],
        },
        co_return_statement => {
            type: Return,
            token: self,
            roles: [Return],
        },
        goto_statement => {
            type: Break,
            token: self,
            roles: [Break],
            children: ["statement_identifier"],
        },
        labeled_statement => {
            type: Block,
            roles: [Body],
            children: ["statement_identifier"],
        },
        try_statement => {
            type: Try,
            token: self,
            roles: [Try],
            children: ["compound_statement"],
        },
        catch_clause => {
            type: Catch,
            token: self,
            roles: [Catch],
            children: ["compound_statement", "parameter_list"],
        },
        throw_statement => {
            type: Throw,
            roles: [Throw],
        },
        seh_try_statement => {
            type: Try,
            token: self,
            roles: [Try],
            children: ["compound_statement"],
        },
        seh_except_clause => {
            type: Catch,
            roles: [Catch],
            children: ["compound_statement", "parenthesized_expression"],
        },
        seh_finally_clause => {
            type: Finally,
            token: self,
            roles: [Finally],
            children: ["compound_statement"],
        },
        seh_leave_statement => {
            type: Break,
            roles: [Break],
        },
        co_await_expression => {
            type: Await,
            roles: [Await],
            children: ["co_await", "expression"],
        },
        co_yield_statement => {
            type: Yield,
            roles: [Yield],
        },
        compound_statement => {
            type: Block,
            roles: [Body],
        },
        declaration => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["_declarator", "expression", "gnu_asm_expression", "init_declarator", "initializer_list", "ms_call_modifier", "operator_cast", "type_specifier"],
        },
        init_declarator => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["_declarator", "argument_list", "expression", "initializer_list"],
        },
        field_declaration => {
            type: Field,
            token: self,
            roles: [Member, Declaration],
            children: ["_field_declarator", "expression", "initializer_list", "type_specifier"],
        },
        field_declaration_list => {
            type: List,
        },
        bitfield_clause => {
            type: Field,
            roles: [Member],
        },
        field_initializer => {
            type: Field,
            token: self,
            roles: [Member],
        },
        field_initializer_list => {
            type: List,
        },
        field_designator => {
            type: Identifier,
            token: self,
            roles: [Name, Member],
        },
        parameter_declaration => {
            type: Parameter,
            roles: [Parameter],
            children: ["_abstract_declarator", "_declarator", "type_specifier"],
        },
        parameter_list => {
            type: List,
            token: self,
        },
        optional_parameter_declaration => {
            type: Parameter,
            roles: [Parameter],
            children: ["_declarator", "abstract_reference_declarator", "expression", "type_specifier"],
        },
        variadic_parameter_declaration => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["reference_declarator", "type_specifier", "variadic_declarator"],
        },
        explicit_object_parameter_declaration => {
            type: Parameter,
            token: self,
            roles: [Parameter],
        },
        type_parameter_declaration => {
            type: Parameter,
            roles: [Parameter],
        },
        optional_type_parameter_declaration => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["type_identifier", "type_specifier"],
        },
        variadic_type_parameter_declaration => {
            type: Parameter,
            roles: [Parameter],
        },
        template_template_parameter_declaration => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["template_parameter_list"],
        },
        template_parameter_list => {
            type: List,
        },
        parameter_pack_expansion => {
            type: Spread,
            roles: [Spread],
            children: ["expression", "type_descriptor"],
        },
        type_definition => {
            type: TypeAnnotation,
            roles: [Type, Declaration],
            children: ["_type_declarator", "type_specifier"],
        },
        alias_declaration => {
            type: TypeAnnotation,
            token: self,
            roles: [Type, Declaration],
            children: ["type_descriptor", "type_identifier"],
        },
        type_descriptor => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["_abstract_declarator", "type_specifier"],
        },
        trailing_return_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type, Return],
        },
        cast_expression => {
            type: Cast,
            roles: [Type],
            children: ["expression", "type_descriptor"],
        },
        operator_cast => {
            type: Cast,
            roles: [Type, Operator],
            children: ["_abstract_declarator", "type_specifier"],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        attribute => {
            type: Attribute,
            token: self,
            roles: [Attribute],
            children: ["identifier"],
        },
        attribute_declaration => {
            type: Attribute,
            roles: [Attribute],
        },
        attribute_specifier => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        attributed_declarator => {
            type: Attribute,
            roles: [Attribute],
        },
        attributed_statement => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        preproc_if => {
            type: If,
            roles: [Condition],
            children: ["binary_expression", "call_expression", "char_literal", "identifier", "number_literal", "parenthesized_expression", "preproc_defined", "preproc_elif", "preproc_elifdef", "preproc_else", "unary_expression"],
        },
        preproc_ifdef => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["identifier", "preproc_elif", "preproc_elifdef", "preproc_else"],
        },
        preproc_elif => {
            type: If,
            roles: [Condition],
            children: ["binary_expression", "call_expression", "char_literal", "identifier", "number_literal", "parenthesized_expression", "preproc_defined", "preproc_elif", "preproc_elifdef", "preproc_else", "unary_expression"],
        },
        preproc_elifdef => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["identifier", "preproc_elif", "preproc_elifdef", "preproc_else"],
        },
        preproc_else => {
            type: Block,
            roles: [Body],
        },
        preproc_call => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["preproc_arg", "preproc_directive"],
        },
        preproc_def => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["identifier", "preproc_arg"],
        },
        preproc_defined => {
            type: Call,
            token: self,
            roles: [Call],
        },
        preproc_params => {
            type: List,
            token: self,
        },
        preproc_arg => {
            type: Synthetic,
            token: self,
        },
        preproc_directive => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        template_declaration => {
            type: Synthetic,
            children: ["template_parameter_list"],
        },
        template_instantiation => {
            type: Synthetic,
            children: ["_declarator", "type_specifier"],
        },
        template_type => {
            type: TypeAnnotation,
            roles: [Type],
            children: ["template_argument_list", "type_identifier"],
        },
        template_argument_list => {
            type: List,
            token: self,
        },
        concept_definition => {
            type: TypeAnnotation,
            roles: [Type, Declaration],
            children: ["identifier"],
        },
        requires_clause => {
            type: Synthetic,
            token: self,
            children: ["constraint_conjunction", "constraint_disjunction", "expression", "template_type", "type_identifier"],
        },
        requires_expression => {
            type: Synthetic,
            children: ["parameter_list", "requirement_seq"],
        },
        requirement_seq => {
            type: List,
        },
        simple_requirement => {
            type: Synthetic,
        },
        compound_requirement => {
            type: Synthetic,
            token: self,
        },
        type_requirement => {
            type: Synthetic,
        },
        constraint_conjunction => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["and", "constraint_conjunction", "constraint_disjunction", "expression", "template_type", "type_identifier"],
        },
        constraint_disjunction => {
            type: BinaryOp,
            roles: [Operator],
            children: ["constraint_conjunction", "constraint_disjunction", "expression", "or", "template_type", "type_identifier"],
        },
        argument_list => {
            type: List,
        },
        initializer_list => {
            type: List,
        },
        initializer_pair => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
            children: ["expression", "field_designator", "field_identifier", "initializer_list", "subscript_designator", "subscript_range_designator"],
        },
        subscript_argument_list => {
            type: List,
        },
        subscript_designator => {
            type: Index,
            token: self,
            roles: [Index],
        },
        subscript_range_designator => {
            type: Slice,
            token: self,
            roles: [Index],
            children: ["expression"],
        },
        declaration_list => {
            type: List,
            token: self,
        },
        fold_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["and", "bitand", "bitor", "expression", "not_eq", "or", "xor"],
        },
        gnu_asm_expression => {
            type: Synthetic,
            children: ["concatenated_string", "gnu_asm_clobber_list", "gnu_asm_goto_list", "gnu_asm_input_operand_list", "gnu_asm_output_operand_list", "raw_string_literal", "string_literal"],
        },
        gnu_asm_clobber_list => {
            type: List,
            token: self,
            children: ["concatenated_string", "raw_string_literal", "string_literal"],
        },
        gnu_asm_goto_list => {
            type: List,
            token: self,
            children: ["identifier"],
        },
        gnu_asm_input_operand => {
            type: Synthetic,
            children: ["expression", "identifier", "string_literal"],
        },
        gnu_asm_input_operand_list => {
            type: List,
            token: self,
            children: ["gnu_asm_input_operand"],
        },
        gnu_asm_output_operand => {
            type: Synthetic,
            children: ["expression", "identifier", "string_literal"],
        },
        gnu_asm_output_operand_list => {
            type: List,
            token: self,
            children: ["gnu_asm_output_operand"],
        },
        gnu_asm_qualifier => {
            type: Synthetic,
        },
        linkage_specification => {
            type: Synthetic,
            token: self,
            children: ["declaration", "declaration_list", "function_definition", "string_literal"],
        },
        friend_declaration => {
            type: Synthetic,
        },
        access_specifier => {
            type: Synthetic,
        },
        static_assert_declaration => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["concatenated_string", "expression", "raw_string_literal", "string_literal"],
        },
        offsetof_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["field_identifier", "type_descriptor"],
        },
        extension_expression => {
            type: Synthetic,
        },
        parenthesized_expression => {
            type: Synthetic,
        },
        expression_statement => {
            type: Synthetic,
            token: self,
        },
        condition_clause => {
            type: Synthetic,
            token: self,
            children: ["comma_expression", "declaration", "expression", "init_statement"],
        },
        init_statement => {
            type: Synthetic,
            token: self,
        },
        expression => {
            type: Synthetic,
        },
        statement => {
            type: Synthetic,
            token: self,
        },
        type_specifier => {
            type: Synthetic,
        },
        primitive_type => {
            type: Identifier,
            token: self,
            roles: [Type, Name],
        },
        sized_type_specifier => {
            type: Synthetic,
            token: self,
            children: ["primitive_type", "type_identifier"],
        },
        placeholder_type_specifier => {
            type: Synthetic,
            token: self,
            children: ["qualified_identifier", "template_type", "type_identifier"],
        },
        decltype => {
            type: Synthetic,
        },
        dependent_name => {
            type: Synthetic,
        },
        dependent_type => {
            type: Synthetic,
            token: self,
        },
        storage_class_specifier => {
            type: Synthetic,
        },
        type_qualifier => {
            type: Synthetic,
            token: self,
        },
        alignas_qualifier => {
            type: Synthetic,
        },
        virtual_specifier => {
            type: Synthetic,
            token: self,
        },
        noexcept => {
            type: Synthetic,
            token: self,
        },
        throw_specifier => {
            type: Synthetic,
            token: self,
        },
        pure_virtual_clause => {
            type: Synthetic,
            token: self,
        },
        _abstract_declarator => {
            type: Synthetic,
        },
        _declarator => {
            type: Synthetic,
            token: self,
        },
        _field_declarator => {
            type: Identifier,
            roles: [Name, Member],
        },
        _type_declarator => {
            type: Synthetic,
            token: self,
        },
        abstract_array_declarator => {
            type: Synthetic,
            token: self,
            children: ["_abstract_declarator", "expression"],
        },
        abstract_parenthesized_declarator => {
            type: Synthetic,
            token: self,
        },
        abstract_pointer_declarator => {
            type: Synthetic,
            children: ["_abstract_declarator"],
        },
        abstract_reference_declarator => {
            type: Synthetic,
            token: self,
        },
        array_declarator => {
            type: Synthetic,
            token: self,
            children: ["_declarator", "_field_declarator", "_type_declarator", "expression"],
        },
        parenthesized_declarator => {
            type: Synthetic,
            token: self,
        },
        pointer_declarator => {
            type: Synthetic,
            children: ["_declarator", "_field_declarator", "_type_declarator"],
        },
        pointer_type_declarator => {
            type: Synthetic,
            children: ["_type_declarator"],
        },
        reference_declarator => {
            type: Synthetic,
            token: self,
        },
        variadic_declarator => {
            type: Synthetic,
        },
        new_declarator => {
            type: Synthetic,
            token: self,
            children: ["expression"],
        },
        structured_binding_declarator => {
            type: List,
            token: self,
        },
        nested_namespace_specifier => {
            type: Synthetic,
        },
        ms_based_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_call_modifier => {
            type: Synthetic,
        },
        ms_declspec_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_pointer_modifier => {
            type: Synthetic,
        },
        ms_unaligned_ptr_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_restrict_modifier => {
            type: Synthetic,
        },
        ms_signed_ptr_modifier => {
            type: Synthetic,
            token: self,
        },
        ms_unsigned_ptr_modifier => {
            type: Synthetic,
        },
        if => {
            type: Synthetic,
            token: self,
        },
        else => {
            type: Synthetic,
            token: self,
        },
        for => {
            type: Synthetic,
            token: self,
        },
        while => {
            type: Synthetic,
            token: self,
        },
        do => {
            type: Synthetic,
        },
        switch => {
            type: Synthetic,
        },
        case => {
            type: Synthetic,
            token: self,
        },
        default => {
            type: Synthetic,
            token: self,
        },
        break => {
            type: Synthetic,
            token: self,
        },
        continue => {
            type: Synthetic,
            token: self,
        },
        return => {
            type: Synthetic,
            token: self,
        },
        goto => {
            type: Synthetic,
        },
        try => {
            type: Synthetic,
            token: self,
        },
        catch => {
            type: Synthetic,
        },
        throw => {
            type: Synthetic,
            token: self,
        },
        class => {
            type: Synthetic,
        },
        struct => {
            type: Synthetic,
            token: self,
        },
        union => {
            type: Synthetic,
            token: self,
        },
        enum => {
            type: Synthetic,
        },
        namespace => {
            type: Synthetic,
        },
        template => {
            type: Synthetic,
        },
        typename => {
            type: Synthetic,
        },
        typedef => {
            type: Synthetic,
            token: self,
        },
        using => {
            type: Synthetic,
            token: self,
        },
        new => {
            type: Synthetic,
        },
        delete => {
            type: Synthetic,
            token: self,
        },
        sizeof => {
            type: Synthetic,
        },
        alignof => {
            type: Synthetic,
            token: self,
        },
        offsetof => {
            type: Synthetic,
        },
        this => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        operator => {
            type: Synthetic,
        },
        const => {
            type: Synthetic,
            token: self,
        },
        volatile => {
            type: Synthetic,
            token: self,
        },
        mutable => {
            type: Synthetic,
            token: self,
        },
        register => {
            type: Synthetic,
        },
        static => {
            type: Synthetic,
        },
        extern => {
            type: Synthetic,
        },
        inline => {
            type: Synthetic,
        },
        virtual => {
            type: Synthetic,
        },
        explicit => {
            type: Synthetic,
        },
        friend => {
            type: Synthetic,
            token: self,
        },
        public => {
            type: Synthetic,
            token: self,
        },
        protected => {
            type: Synthetic,
        },
        private => {
            type: Synthetic,
            token: self,
        },
        final => {
            type: Synthetic,
            token: self,
        },
        override => {
            type: Synthetic,
            token: self,
        },
        auto => {
            type: Synthetic,
            token: self,
        },
        constexpr => {
            type: Synthetic,
            token: self,
        },
        consteval => {
            type: Synthetic,
        },
        constinit => {
            type: Synthetic,
        },
        thread_local => {
            type: Synthetic,
        },
        noreturn => {
            type: Synthetic,
        },
        requires => {
            type: Synthetic,
            token: self,
        },
        concept => {
            type: Synthetic,
        },
        co_await => {
            type: Synthetic,
            token: self,
        },
        co_return => {
            type: Synthetic,
        },
        co_yield => {
            type: Synthetic,
            token: self,
        },
        module => {
            type: Synthetic,
            token: self,
        },
        import => {
            type: Synthetic,
            token: self,
        },
        export => {
            type: Synthetic,
            token: self,
        },
        and => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        and_eq => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        bitand => {
            type: Identifier,
            roles: [Operator],
        },
        bitor => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        compl => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        not => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        not_eq => {
            type: Identifier,
            roles: [Operator],
        },
        or => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        or_eq => {
            type: Identifier,
            roles: [Operator],
        },
        xor => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        xor_eq => {
            type: Identifier,
            roles: [Operator],
        },
        defined => {
            type: Synthetic,
        },
        short => {
            type: Synthetic,
        },
        long => {
            type: Synthetic,
        },
        signed => {
            type: Synthetic,
            token: self,
        },
        unsigned => {
            type: Synthetic,
        },
        restrict => {
            type: Synthetic,
        },
        asm => {
            type: Synthetic,
        },
        character => {
            type: Synthetic,
            token: self,
        },
        escape_sequence => {
            type: Synthetic,
            token: self,
        },
        string_content => {
            type: Synthetic,
        },
        raw_string_content => {
            type: Synthetic,
        },
        raw_string_delimiter => {
            type: Synthetic,
            token: self,
        },
        _Alignas => {
            type: Synthetic,
        },
        _Alignof => {
            type: Synthetic,
            token: self,
        },
        _Atomic => {
            type: Synthetic,
        },
        _Generic => {
            type: Synthetic,
            token: self,
        },
        _Nonnull => {
            type: Synthetic,
        },
        _Noreturn => {
            type: Synthetic,
            token: self,
        },
        _alignof => {
            type: Synthetic,
        },
        _unaligned => {
            type: Synthetic,
            token: self,
        },
        alignas => {
            type: Synthetic,
        },
        __alignof => {
            type: Synthetic,
        },
        __alignof__ => {
            type: Synthetic,
            token: self,
        },
        __asm => {
            type: Synthetic,
        },
        __asm__ => {
            type: Synthetic,
            token: self,
        },
        __attribute => {
            type: Attribute,
            roles: [Attribute],
        },
        __attribute__ => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        __based => {
            type: Synthetic,
        },
        __cdecl => {
            type: Synthetic,
            token: self,
        },
        __clrcall => {
            type: Synthetic,
        },
        __declspec => {
            type: Synthetic,
            token: self,
        },
        __except => {
            type: Synthetic,
        },
        __extension__ => {
            type: Synthetic,
            token: self,
        },
        __fastcall => {
            type: Synthetic,
        },
        __finally => {
            type: Finally,
            token: self,
            roles: [Finally],
        },
        __forceinline => {
            type: Synthetic,
        },
        __inline => {
            type: Synthetic,
            token: self,
        },
        __inline__ => {
            type: Synthetic,
        },
        __leave => {
            type: Synthetic,
            token: self,
        },
        __restrict__ => {
            type: Synthetic,
        },
        __stdcall => {
            type: Synthetic,
            token: self,
        },
        __thiscall => {
            type: Synthetic,
        },
        __thread => {
            type: Synthetic,
            token: self,
        },
        __try => {
            type: Try,
            roles: [Try],
        },
        __unaligned => {
            type: Synthetic,
            token: self,
        },
        __vectorcall => {
            type: Synthetic,
        },
        __volatile__ => {
            type: Synthetic,
            token: self,
        },
    }
};
