//! GENERATED by uastmap2rs — transpiled from `css.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `css` language.
pub static CSS: LanguageMapping = uast_language! {
    name: "css",
    extensions: [".css"],
    rules: {
        stylesheet => {
            type: File,
        },
        import_statement => {
            type: Import,
            roles: [Import],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        js_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        class_name => {
            type: Identifier,
            token: self,
            roles: [Name, Class],
        },
        id_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        tag_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        property_name => {
            type: Identifier,
            token: self,
            roles: [Name, Member],
        },
        function_name => {
            type: Identifier,
            token: self,
            roles: [Name, Function],
        },
        keyframes_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        namespace_name => {
            type: Identifier,
            token: self,
            roles: [Name, Module],
        },
        feature_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        attribute_name => {
            type: Identifier,
            token: self,
            roles: [Name, Attribute],
        },
        string_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_content => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        float_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        color_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        plain_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        unit => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        grid_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        rule_set => {
            type: Synthetic,
        },
        selectors => {
            type: Synthetic,
        },
        block => {
            type: Block,
            roles: [Body],
        },
        declaration => {
            type: KeyValue,
            roles: [Key, Value],
        },
        important => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        class_selector => {
            type: Synthetic,
        },
        id_selector => {
            type: Synthetic,
        },
        universal_selector => {
            type: Synthetic,
            token: self,
        },
        attribute_selector => {
            type: Synthetic,
        },
        pseudo_class_selector => {
            type: Synthetic,
        },
        pseudo_element_selector => {
            type: Synthetic,
        },
        child_selector => {
            type: Synthetic,
        },
        descendant_selector => {
            type: Synthetic,
        },
        adjacent_sibling_selector => {
            type: Synthetic,
        },
        sibling_selector => {
            type: Synthetic,
        },
        namespace_selector => {
            type: Synthetic,
        },
        nesting_selector => {
            type: Synthetic,
            token: self,
        },
        call_expression => {
            type: Call,
            roles: [Call],
        },
        arguments => {
            type: Synthetic,
        },
        parenthesized_value => {
            type: Synthetic,
        },
        binary_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        at_rule => {
            type: Synthetic,
        },
        at_keyword => {
            type: Synthetic,
            token: self,
        },
        media_statement => {
            type: Synthetic,
        },
        keyframes_statement => {
            type: Synthetic,
        },
        keyframe_block => {
            type: Block,
            roles: [Body],
        },
        keyframe_block_list => {
            type: Block,
            roles: [Body],
        },
        charset_statement => {
            type: Synthetic,
        },
        namespace_statement => {
            type: Namespace,
            roles: [Module],
        },
        supports_statement => {
            type: Synthetic,
        },
        postcss_statement => {
            type: Synthetic,
        },
        binary_query => {
            type: BinaryOp,
            roles: [Operator],
        },
        unary_query => {
            type: UnaryOp,
            roles: [Operator],
        },
        selector_query => {
            type: Synthetic,
        },
        feature_query => {
            type: Synthetic,
        },
        parenthesized_query => {
            type: Synthetic,
        },
        keyword_query => {
            type: Synthetic,
        },
        and => {
            type: Synthetic,
            token: self,
        },
        or => {
            type: Synthetic,
            token: self,
        },
        not => {
            type: Synthetic,
            token: self,
        },
        only => {
            type: Synthetic,
            token: self,
        },
        from => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        to => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        of => {
            type: Synthetic,
            token: self,
        },
        escape_sequence => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        selector => {
            type: Synthetic,
        },
    }
};
