//! GENERATED by uastmap2rs — transpiled from `dotenv.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `dotenv` language.
pub static DOTENV: LanguageMapping = uast_language! {
    name: "dotenv",
    extensions: [".env"],
    rules: {
        source_file => {
            type: File,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        variable => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_interpolated => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        raw_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        bool => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        url => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        interpolated_variable => {
            type: Identifier,
            token: self,
            roles: [Name, Reference],
        },
        shell_command => {
            type: Call,
            token: self,
            roles: [Call],
        },
        escape_sequence => {
            type: Synthetic,
            token: self,
        },
    }
};
