//! GENERATED by uastmap2rs — transpiled from `elm.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `elm` language.
pub static ELM: LanguageMapping = uast_language! {
    name: "elm",
    extensions: [".elm"],
    rules: {
        file => {
            type: File,
        },
        module_declaration => {
            type: Module,
            token: self,
            roles: [Module],
        },
        import_clause => {
            type: Import,
            token: self,
            roles: [Import],
        },
        lower_case_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        upper_case_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        upper_case_qid => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        value_qid => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        number_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number_constant_expr => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        char_constant_expr => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string_constant_expr => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        unit_expr => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        value_declaration => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
        },
        function_declaration_left => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        anonymous_function_expr => {
            type: Lambda,
            token: self,
            roles: [Lambda],
        },
        function_call_expr => {
            type: Call,
            token: self,
            roles: [Call],
        },
        if_else_expr => {
            type: If,
            token: self,
            roles: [Condition],
        },
        case_of_expr => {
            type: Switch,
            token: self,
            roles: [Condition],
        },
        case_of_branch => {
            type: Case,
            token: self,
            roles: [Branch],
        },
        let_in_expr => {
            type: Block,
            token: self,
            roles: [Body],
        },
        bin_op_expr => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        negate_expr => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
        },
        list_expr => {
            type: List,
            token: self,
        },
        tuple_expr => {
            type: Tuple,
            token: self,
        },
        record_expr => {
            type: Dict,
            token: self,
        },
        field => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
        },
        field_access_expr => {
            type: MemberAccess,
            token: self,
            roles: [Member],
        },
        type_declaration => {
            type: TypeDeclaration,
            token: self,
            roles: [Type, Declaration],
        },
        type_alias_declaration => {
            type: TypeDeclaration,
            token: self,
            roles: [Type, Declaration],
        },
        type_annotation => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        type_expression => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        type_ref => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        union_variant => {
            type: EnumMember,
            token: self,
            roles: [Member],
        },
        pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        lower_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        anything_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        cons_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        list_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        tuple_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        record_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        union_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        operator => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        operator_identifier => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        exposing_list => {
            type: List,
            token: self,
            roles: [Export],
        },
        line_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        block_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        port_annotation => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        value_expr => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
    }
};
