//! GENERATED by uastmap2rs — transpiled from `git_config.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `git_config` language.
pub static GIT_CONFIG: LanguageMapping = uast_language! {
    name: "git_config",
    extensions: [".gitconfig"],
    rules: {
        config => {
            type: File,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        section => {
            type: Dict,
            roles: [Literal],
        },
        section_header => {
            type: Identifier,
            roles: [Name],
        },
        section_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        subsection_name => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        variable => {
            type: KeyValue,
            roles: [Key, Value],
        },
        name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        shell_command => {
            type: Call,
            token: self,
            roles: [Call],
        },
        escape_sequence => {
            type: Synthetic,
            token: self,
        },
    }
};
