//! GENERATED by uastmap2rs — transpiled from `graphql.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `graphql` language.
pub static GRAPHQL: LanguageMapping = uast_language! {
    name: "graphql",
    extensions: [".graphql", ".gql"],
    rules: {
        source_file => {
            type: File,
        },
        document => {
            type: Block,
            roles: [Body],
        },
        definition => {
            type: Synthetic,
        },
        type_system_definition => {
            type: Synthetic,
        },
        type_definition => {
            type: Synthetic,
        },
        object_type_definition => {
            type: Struct,
            roles: [Declaration],
        },
        input_object_type_definition => {
            type: Struct,
            roles: [Declaration],
        },
        interface_type_definition => {
            type: Interface,
            roles: [Declaration],
        },
        enum_type_definition => {
            type: Enum,
            roles: [Declaration],
        },
        union_type_definition => {
            type: Struct,
            roles: [Declaration],
        },
        scalar_type_definition => {
            type: TypeAnnotation,
            roles: [Type, Declaration],
        },
        schema_definition => {
            type: Module,
            roles: [Module],
        },
        directive_definition => {
            type: Annotation,
            roles: [Annotation, Declaration],
        },
        executable_definition => {
            type: Synthetic,
        },
        operation_definition => {
            type: Function,
            roles: [Function, Declaration],
        },
        operation_type => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        fragment_definition => {
            type: Function,
            roles: [Function, Declaration],
        },
        fragment_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        fields_definition => {
            type: Block,
            roles: [Body],
        },
        field_definition => {
            type: Property,
            roles: [Member, Declaration],
        },
        input_fields_definition => {
            type: Block,
            roles: [Body],
        },
        input_value_definition => {
            type: Parameter,
            roles: [Declaration],
        },
        arguments_definition => {
            type: List,
            roles: [Literal],
        },
        field => {
            type: Field,
            roles: [Member],
        },
        arguments => {
            type: List,
            roles: [Literal],
        },
        argument => {
            type: KeyValue,
            roles: [Key, Value],
        },
        selection_set => {
            type: Block,
            roles: [Body],
        },
        selection => {
            type: Synthetic,
        },
        variable_definitions => {
            type: List,
            roles: [Literal],
        },
        variable_definition => {
            type: Parameter,
            roles: [Declaration],
        },
        variable => {
            type: Identifier,
            token: self,
            roles: [Name, Reference],
        },
        type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        named_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        list_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        non_null_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        type_condition => {
            type: TypeAnnotation,
            roles: [Type],
        },
        value => {
            type: Literal,
            roles: [Literal],
        },
        string_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        int_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        float_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        boolean_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        null_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        enum_value => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        list_value => {
            type: List,
            roles: [Literal],
        },
        object_value => {
            type: Dict,
            roles: [Literal],
        },
        object_field => {
            type: KeyValue,
            roles: [Key, Value],
        },
        directive => {
            type: Annotation,
            roles: [Annotation],
        },
        fragment_spread => {
            type: Call,
            roles: [Call],
        },
        inline_fragment => {
            type: Block,
            roles: [Body],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        description => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        alias => {
            type: Identifier,
            roles: [Name],
        },
    }
};
