//! GENERATED by uastmap2rs — transpiled from `html.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `html` language.
pub static HTML: LanguageMapping = uast_language! {
    name: "html",
    extensions: [".html", ".htm"],
    rules: {
        document => {
            type: File,
            children: ["doctype", "element", "comment", "text"],
        },
        element => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["start_tag", "end_tag", "self_closing_tag", "element", "text", "comment", "script_element", "style_element"],
        },
        start_tag => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["tag_name", "attribute"],
        },
        end_tag => {
            type: Synthetic,
            children: ["tag_name"],
        },
        self_closing_tag => {
            type: Identifier,
            roles: [Name],
            children: ["tag_name", "attribute"],
        },
        tag_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        attribute => {
            type: Property,
            roles: [Member],
            children: ["attribute_name", "quoted_attribute_value", "attribute_value"],
        },
        attribute_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        attribute_value => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        quoted_attribute_value => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["attribute_value"],
        },
        text => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        doctype => {
            type: Synthetic,
            token: self,
        },
        script_element => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["start_tag", "end_tag", "raw_text"],
        },
        style_element => {
            type: Call,
            roles: [Call],
            children: ["start_tag", "end_tag", "raw_text"],
        },
        raw_text => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        entity => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        erroneous_end_tag => {
            type: Synthetic,
            token: self,
            children: ["erroneous_end_tag_name"],
        },
        erroneous_end_tag_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
    }
};
