//! GENERATED by uastmap2rs — transpiled from `java.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `java` language.
pub static JAVA: LanguageMapping = uast_language! {
    name: "java",
    extensions: [".java"],
    rules: {
        _literal => {
            type: Literal,
            roles: [Literal],
        },
        _simple_type => {
            type: Synthetic,
            token: self,
        },
        _type => {
            type: Synthetic,
        },
        _unannotated_type => {
            type: Synthetic,
            token: self,
        },
        declaration => {
            type: Synthetic,
        },
        expression => {
            type: Synthetic,
            token: self,
        },
        module_directive => {
            type: Module,
            roles: [Module],
        },
        primary_expression => {
            type: Synthetic,
            token: self,
        },
        statement => {
            type: Synthetic,
        },
        annotated_type => {
            type: Synthetic,
            token: self,
        },
        annotation => {
            type: Attribute,
            roles: [Attribute, Annotation],
            children: ["annotation_argument_list", "identifier", "scoped_identifier"],
        },
        annotation_argument_list => {
            type: List,
            token: self,
        },
        annotation_type_body => {
            type: Synthetic,
        },
        annotation_type_declaration => {
            type: Synthetic,
            token: self,
            children: ["annotation_type_body", "identifier"],
        },
        annotation_type_element_declaration => {
            type: Synthetic,
            children: ["_unannotated_type", "annotation", "dimensions", "element_value_array_initializer", "expression", "identifier", "marker_annotation"],
        },
        argument_list => {
            type: List,
            token: self,
        },
        array_access => {
            type: Index,
            token: self,
            roles: [Index],
            children: ["expression", "primary_expression"],
        },
        array_creation_expression => {
            type: Synthetic,
            token: self,
            children: ["_simple_type", "array_initializer", "dimensions", "dimensions_expr"],
        },
        array_initializer => {
            type: Synthetic,
        },
        array_type => {
            type: Synthetic,
            token: self,
            children: ["_unannotated_type", "dimensions"],
        },
        assert_statement => {
            type: Synthetic,
        },
        assignment_expression => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["array_access", "expression", "field_access", "identifier"],
        },
        asterisk => {
            type: Synthetic,
        },
        binary_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        block => {
            type: Block,
            roles: [Body],
        },
        break_statement => {
            type: Break,
            token: self,
            roles: [Break],
        },
        cast_expression => {
            type: Cast,
            children: ["_type", "expression"],
        },
        catch_clause => {
            type: Catch,
            token: self,
            roles: [Catch],
            children: ["block"],
        },
        catch_formal_parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["dimensions", "identifier", "underscore_pattern"],
        },
        catch_type => {
            type: Catch,
            token: self,
            roles: [Catch],
        },
        class_body => {
            type: Class,
            roles: [Class, Declaration],
        },
        class_declaration => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["class_body", "identifier", "permits", "super_interfaces", "superclass", "type_parameters"],
        },
        class_literal => {
            type: Class,
            roles: [Class, Declaration],
        },
        compact_constructor_declaration => {
            type: Struct,
            token: self,
            roles: [Struct, Declaration],
            children: ["block", "identifier"],
        },
        constant_declaration => {
            type: Synthetic,
            children: ["_unannotated_type", "variable_declarator"],
        },
        constructor_body => {
            type: Struct,
            token: self,
            roles: [Struct, Declaration],
        },
        constructor_declaration => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["constructor_body", "formal_parameters", "identifier", "type_parameters"],
        },
        continue_statement => {
            type: Continue,
            token: self,
            roles: [Continue],
        },
        dimensions => {
            type: Synthetic,
        },
        dimensions_expr => {
            type: Synthetic,
            token: self,
        },
        do_statement => {
            type: Loop,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        element_value_array_initializer => {
            type: Synthetic,
            token: self,
        },
        element_value_pair => {
            type: Synthetic,
            children: ["annotation", "element_value_array_initializer", "expression", "identifier", "marker_annotation"],
        },
        enhanced_for_statement => {
            type: Loop,
            token: self,
            roles: [Loop, For],
            children: ["_unannotated_type", "dimensions", "expression", "identifier", "statement", "underscore_pattern"],
        },
        enum_body => {
            type: Enum,
            roles: [Enum, Declaration],
        },
        enum_body_declarations => {
            type: Enum,
            token: self,
            roles: [Enum, Declaration],
        },
        enum_constant => {
            type: EnumMember,
            roles: [Enum, Declaration],
            children: ["argument_list", "class_body", "identifier"],
        },
        enum_declaration => {
            type: Enum,
            token: self,
            roles: [Enum, Declaration],
            children: ["enum_body", "identifier", "super_interfaces"],
        },
        explicit_constructor_invocation => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["argument_list", "primary_expression", "super", "this", "type_arguments"],
        },
        exports_module_directive => {
            type: Module,
            token: self,
            roles: [Module],
            children: ["identifier", "scoped_identifier"],
        },
        expression_statement => {
            type: Synthetic,
        },
        extends_interfaces => {
            type: Interface,
            token: self,
            roles: [Interface, Declaration],
        },
        field_access => {
            type: Field,
            roles: [Member],
            children: ["identifier", "primary_expression", "super", "this"],
        },
        field_declaration => {
            type: Field,
            token: self,
            roles: [Member],
            children: ["_unannotated_type", "variable_declarator"],
        },
        finally_clause => {
            type: Finally,
            roles: [Finally],
        },
        floating_point_type => {
            type: Finally,
            token: self,
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
            children: ["expression", "local_variable_declaration", "statement"],
        },
        formal_parameter => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["_unannotated_type", "dimensions", "identifier", "underscore_pattern"],
        },
        formal_parameters => {
            type: Parameter,
            roles: [Parameter],
        },
        generic_type => {
            type: Synthetic,
            token: self,
        },
        guard => {
            type: Synthetic,
        },
        if_statement => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["parenthesized_expression", "statement"],
        },
        import_declaration => {
            type: Import,
            roles: [Import],
        },
        inferred_parameters => {
            type: Parameter,
            token: self,
            roles: [Parameter],
        },
        instanceof_expression => {
            type: Synthetic,
            children: ["_type", "expression", "identifier", "record_pattern"],
        },
        integral_type => {
            type: Synthetic,
            token: self,
        },
        interface_body => {
            type: Interface,
            roles: [Interface, Declaration],
        },
        interface_declaration => {
            type: Interface,
            token: self,
            roles: [Interface, Declaration],
            children: ["identifier", "interface_body", "permits", "type_parameters"],
        },
        labeled_statement => {
            type: Synthetic,
        },
        lambda_expression => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["block", "expression", "formal_parameters", "identifier", "inferred_parameters"],
        },
        local_variable_declaration => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["_unannotated_type", "variable_declarator"],
        },
        marker_annotation => {
            type: Attribute,
            token: child("identifier"),
            roles: [Attribute, Annotation],
            children: ["identifier", "scoped_identifier"],
        },
        method_declaration => {
            type: Method,
            roles: [Function, Declaration, Member],
            children: ["_unannotated_type", "block", "dimensions", "formal_parameters", "identifier", "type_parameters"],
        },
        method_invocation => {
            type: Call,
            token: child("identifier"),
            roles: [Call],
            children: ["argument_list", "identifier", "primary_expression", "super", "type_arguments"],
        },
        method_reference => {
            type: Method,
            roles: [Function, Declaration, Member],
        },
        modifiers => {
            type: Synthetic,
            token: self,
        },
        module_body => {
            type: Module,
            roles: [Module],
        },
        module_declaration => {
            type: Module,
            token: self,
            roles: [Module],
            children: ["identifier", "module_body", "scoped_identifier"],
        },
        multiline_string_fragment => {
            type: Synthetic,
        },
        object_creation_expression => {
            type: Synthetic,
            token: self,
            children: ["_simple_type", "argument_list", "type_arguments"],
        },
        opens_module_directive => {
            type: Module,
            roles: [Module],
            children: ["identifier", "scoped_identifier"],
        },
        package_declaration => {
            type: Package,
            token: self,
            roles: [Module],
        },
        parenthesized_expression => {
            type: Synthetic,
        },
        pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        permits => {
            type: Synthetic,
        },
        program => {
            type: File,
        },
        provides_module_directive => {
            type: Module,
            roles: [Module],
            children: ["identifier", "scoped_identifier"],
        },
        receiver_parameter => {
            type: Parameter,
            token: self,
            roles: [Parameter],
        },
        record_declaration => {
            type: Synthetic,
            children: ["class_body", "formal_parameters", "identifier", "super_interfaces", "type_parameters"],
        },
        record_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        record_pattern_body => {
            type: Pattern,
            roles: [Pattern],
        },
        record_pattern_component => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        requires_modifier => {
            type: If,
        },
        requires_module_directive => {
            type: Module,
            token: self,
            roles: [Module],
            children: ["identifier", "requires_modifier", "scoped_identifier"],
        },
        resource => {
            type: Synthetic,
            children: ["_unannotated_type", "dimensions", "expression", "identifier", "underscore_pattern"],
        },
        resource_specification => {
            type: Synthetic,
            token: self,
        },
        return_statement => {
            type: Return,
            roles: [Return],
        },
        scoped_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["identifier", "scoped_identifier"],
        },
        scoped_type_identifier => {
            type: If,
        },
        spread_parameter => {
            type: Spread,
            token: self,
            roles: [Spread, Parameter],
        },
        static_initializer => {
            type: Synthetic,
        },
        string_interpolation => {
            type: Synthetic,
            token: self,
        },
        string_literal => {
            type: Literal,
            roles: [Literal],
        },
        super_interfaces => {
            type: Interface,
            token: self,
            roles: [Interface, Declaration],
        },
        superclass => {
            type: Class,
            roles: [Class, Declaration],
        },
        switch_block => {
            type: Block,
            token: self,
            roles: [Body],
        },
        switch_block_statement_group => {
            type: Block,
            roles: [Body],
        },
        switch_expression => {
            type: Switch,
            token: self,
            children: ["parenthesized_expression", "switch_block"],
        },
        switch_label => {
            type: Switch,
        },
        switch_rule => {
            type: Switch,
            token: self,
        },
        synchronized_statement => {
            type: Synthetic,
            children: ["block"],
        },
        template_expression => {
            type: Synthetic,
            token: self,
            children: ["primary_expression", "string_literal"],
        },
        ternary_expression => {
            type: Synthetic,
            children: ["expression"],
        },
        throw_statement => {
            type: Throw,
            token: self,
            roles: [Throw],
        },
        throws => {
            type: Throw,
            roles: [Throw],
        },
        try_statement => {
            type: Try,
            token: self,
            roles: [Try],
            children: ["block"],
        },
        try_with_resources_statement => {
            type: Try,
            roles: [Try],
            children: ["block", "resource_specification"],
        },
        type_arguments => {
            type: Synthetic,
            token: self,
        },
        type_bound => {
            type: Synthetic,
        },
        type_list => {
            type: List,
            token: self,
        },
        type_parameter => {
            type: Parameter,
            roles: [Parameter],
        },
        type_parameters => {
            type: Parameter,
            token: self,
            roles: [Parameter],
        },
        type_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        unary_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        update_expression => {
            type: Synthetic,
        },
        uses_module_directive => {
            type: Module,
            token: self,
            roles: [Module],
            children: ["identifier", "scoped_identifier"],
        },
        variable_declarator => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["array_initializer", "dimensions", "expression", "identifier", "underscore_pattern"],
        },
        while_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        wildcard => {
            type: Synthetic,
        },
        yield_statement => {
            type: Yield,
            token: self,
            roles: [Yield],
        },
        abstract => {
            type: Synthetic,
        },
        assert => {
            type: Synthetic,
            token: self,
        },
        binary_integer_literal => {
            type: Literal,
            roles: [Literal],
        },
        block_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        boolean_type => {
            type: Synthetic,
        },
        break => {
            type: Break,
            token: self,
            roles: [Break],
        },
        byte => {
            type: Synthetic,
        },
        case => {
            type: Case,
            token: self,
            roles: [Branch],
        },
        catch => {
            type: Catch,
            roles: [Catch],
        },
        char => {
            type: Synthetic,
            token: self,
        },
        character_literal => {
            type: Literal,
            roles: [Literal],
        },
        class => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
        },
        continue => {
            type: Continue,
            roles: [Continue],
        },
        decimal_floating_point_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        decimal_integer_literal => {
            type: Literal,
            roles: [Literal],
        },
        default => {
            type: Synthetic,
            token: self,
        },
        do => {
            type: Loop,
            token: self,
            roles: [Loop],
        },
        double => {
            type: Synthetic,
            token: self,
        },
        else => {
            type: Synthetic,
        },
        enum => {
            type: Enum,
            token: self,
            roles: [Enum, Declaration],
        },
        escape_sequence => {
            type: Synthetic,
        },
        exports => {
            type: Synthetic,
            token: self,
        },
        extends => {
            type: Synthetic,
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        final => {
            type: Synthetic,
        },
        finally => {
            type: Finally,
            token: self,
            roles: [Finally],
        },
        float => {
            type: Synthetic,
        },
        for => {
            type: Loop,
            token: self,
            roles: [Loop],
        },
        hex_floating_point_literal => {
            type: Literal,
            roles: [Literal],
        },
        hex_integer_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        if => {
            type: Synthetic,
            token: self,
        },
        implements => {
            type: Synthetic,
        },
        import => {
            type: Import,
            token: self,
            roles: [Import],
        },
        instanceof => {
            type: Synthetic,
        },
        int => {
            type: Synthetic,
            token: self,
        },
        interface => {
            type: Interface,
            roles: [Interface, Declaration],
        },
        line_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        long => {
            type: Synthetic,
        },
        module => {
            type: Module,
            token: self,
            roles: [Module],
        },
        native => {
            type: Synthetic,
        },
        new => {
            type: Synthetic,
            token: self,
        },
        null_literal => {
            type: Literal,
            roles: [Literal],
        },
        octal_integer_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        open => {
            type: Synthetic,
        },
        opens => {
            type: Synthetic,
            token: self,
        },
        package => {
            type: Package,
            roles: [Module],
        },
        permits => {
            type: Synthetic,
            token: self,
        },
        private => {
            type: Synthetic,
        },
        protected => {
            type: Synthetic,
            token: self,
        },
        provides => {
            type: Synthetic,
        },
        public => {
            type: Synthetic,
            token: self,
        },
        record => {
            type: Synthetic,
        },
        requires => {
            type: Synthetic,
            token: self,
        },
        return => {
            type: Return,
            roles: [Return],
        },
        sealed => {
            type: Synthetic,
            token: self,
        },
        short => {
            type: Synthetic,
        },
        static => {
            type: Synthetic,
            token: self,
        },
        strictfp => {
            type: Synthetic,
        },
        string_fragment => {
            type: Synthetic,
            token: self,
        },
        super => {
            type: Synthetic,
        },
        switch => {
            type: Switch,
            token: self,
        },
        synchronized => {
            type: Synthetic,
        },
        this => {
            type: Synthetic,
            token: self,
        },
        throw => {
            type: Throw,
            roles: [Throw],
        },
        throws => {
            type: Throw,
            token: self,
            roles: [Throw],
        },
        to => {
            type: Synthetic,
        },
        transient => {
            type: Synthetic,
            token: self,
        },
        transitive => {
            type: Synthetic,
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        try => {
            type: Try,
            roles: [Try],
        },
        type_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        underscore_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        uses => {
            type: Pattern,
            token: self,
        },
        void_type => {
            type: Synthetic,
        },
        volatile => {
            type: Synthetic,
            token: self,
        },
        when => {
            type: Synthetic,
        },
        while => {
            type: Loop,
            token: self,
            roles: [Loop],
        },
        with => {
            type: Synthetic,
        },
        yield => {
            type: Yield,
            token: self,
            roles: [Yield],
        },
    }
};
