//! GENERATED by uastmap2rs — transpiled from `javascript.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `javascript` language.
pub static JAVASCRIPT: LanguageMapping = uast_language! {
    name: "javascript",
    extensions: [".js", ".jsx", ".mjs"],
    rules: {
        declaration => {
            type: Synthetic,
        },
        expression => {
            type: Synthetic,
            token: self,
        },
        pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        primary_expression => {
            type: Synthetic,
            token: self,
        },
        statement => {
            type: Synthetic,
        },
        arguments => {
            type: Synthetic,
            token: self,
        },
        array => {
            type: List,
            roles: [Literal],
        },
        array_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        arrow_function => {
            type: Lambda,
            roles: [Lambda],
            children: ["expression", "formal_parameters", "identifier", "statement_block"],
        },
        assignment_expression => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["array_pattern", "expression", "identifier", "member_expression", "object_pattern", "parenthesized_expression", "subscript_expression", "undefined"],
        },
        assignment_pattern => {
            type: Assignment,
            roles: [Assignment],
            children: ["expression", "pattern"],
        },
        augmented_assignment_expression => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["expression", "identifier", "member_expression", "parenthesized_expression", "subscript_expression"],
        },
        await_expression => {
            type: Await,
            roles: [Await],
        },
        binary_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["expression", "in", "instanceof", "private_property_identifier"],
        },
        break_statement => {
            type: Break,
            roles: [Break],
            children: ["statement_identifier"],
        },
        call_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["arguments", "expression", "import", "optional_chain", "template_string"],
        },
        catch_clause => {
            type: Catch,
            roles: [Catch],
            children: ["array_pattern", "identifier", "object_pattern", "statement_block"],
        },
        class => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
        },
        class_body => {
            type: Block,
            roles: [Body],
            children: ["class_static_block", "field_definition", "method_definition"],
        },
        class_declaration => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["class_body", "decorator", "identifier"],
        },
        class_heritage => {
            type: Synthetic,
            roles: [Type],
        },
        class_static_block => {
            type: Block,
            token: self,
            roles: [Static, Body],
            children: ["statement_block"],
        },
        computed_property_name => {
            type: Property,
            roles: [Member],
        },
        continue_statement => {
            type: Continue,
            token: self,
            roles: [Continue],
            children: ["statement_identifier"],
        },
        debugger_statement => {
            type: Synthetic,
        },
        decorator => {
            type: Decorator,
            token: self,
            roles: [Attribute],
        },
        do_statement => {
            type: Loop,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
            props: { "props": "kind=do-while" },
        },
        else_clause => {
            type: Synthetic,
            token: self,
            roles: [Body],
        },
        empty_statement => {
            type: Synthetic,
        },
        export_clause => {
            type: Synthetic,
            token: self,
        },
        export_specifier => {
            type: Synthetic,
            children: ["identifier", "string"],
        },
        export_statement => {
            type: Synthetic,
            token: self,
            roles: [Exported],
            children: ["declaration", "decorator", "expression", "string"],
        },
        expression_statement => {
            type: Synthetic,
        },
        field_definition => {
            type: Field,
            token: self,
            roles: [Member],
            children: ["computed_property_name", "decorator", "expression", "number", "private_property_identifier", "property_identifier", "string"],
        },
        finally_clause => {
            type: Finally,
            roles: [Finally],
            children: ["statement_block"],
        },
        for_in_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["array_pattern", "const", "expression", "identifier", "in", "let", "member_expression", "object_pattern", "of", "parenthesized_expression", "sequence_expression", "statement", "subscript_expression", "undefined", "var"],
            props: { "props": "kind=for-in" },
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
            children: ["empty_statement", "expression", "lexical_declaration", "sequence_expression", "statement", "variable_declaration"],
            props: { "props": "kind=for" },
        },
        formal_parameters => {
            type: Synthetic,
            token: self,
            roles: [Parameter],
        },
        function_declaration => {
            type: Function,
            roles: [Function, Declaration],
            children: ["formal_parameters", "identifier", "statement_block"],
        },
        function_expression => {
            type: Function,
            token: child("identifier"),
            roles: [Function, Declaration],
            children: ["formal_parameters", "identifier", "statement_block"],
        },
        generator_function => {
            type: Generator,
            roles: [Function, Declaration, Generator],
            children: ["formal_parameters", "identifier", "statement_block"],
        },
        generator_function_declaration => {
            type: Generator,
            token: self,
            roles: [Function, Declaration, Generator],
            children: ["formal_parameters", "identifier", "statement_block"],
        },
        if_statement => {
            type: If,
            roles: [Condition],
            children: ["else_clause", "parenthesized_expression", "statement"],
        },
        import => {
            type: Import,
            token: self,
            roles: [Import],
        },
        import_attribute => {
            type: Synthetic,
            roles: [Attribute],
        },
        import_clause => {
            type: Synthetic,
            token: self,
            roles: [Import],
        },
        import_specifier => {
            type: Synthetic,
            roles: [Import],
            children: ["identifier", "string"],
        },
        import_statement => {
            type: Import,
            token: self,
            roles: [Import],
            children: ["string"],
        },
        jsx_attribute => {
            type: Attribute,
            roles: [Attribute],
        },
        jsx_closing_element => {
            type: Synthetic,
            token: self,
            children: ["identifier", "jsx_namespace_name", "member_expression"],
        },
        jsx_element => {
            type: Synthetic,
            children: ["jsx_closing_element", "jsx_opening_element"],
        },
        jsx_expression => {
            type: Synthetic,
            token: self,
        },
        jsx_namespace_name => {
            type: Namespace,
            roles: [Module],
        },
        jsx_opening_element => {
            type: Synthetic,
            token: self,
            children: ["identifier", "jsx_attribute", "jsx_expression", "jsx_namespace_name", "member_expression"],
        },
        jsx_self_closing_element => {
            type: Synthetic,
            children: ["identifier", "jsx_attribute", "jsx_expression", "jsx_namespace_name", "member_expression"],
        },
        labeled_statement => {
            type: Synthetic,
            token: self,
            children: ["statement", "statement_identifier"],
        },
        lexical_declaration => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["const", "let"],
        },
        member_expression => {
            type: Synthetic,
            token: self,
            roles: [Member],
            children: ["expression", "import", "optional_chain", "private_property_identifier", "property_identifier"],
        },
        meta_property => {
            type: Property,
            roles: [Member],
        },
        method_definition => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
            children: ["computed_property_name", "decorator", "formal_parameters", "number", "private_property_identifier", "property_identifier", "statement_block", "string"],
        },
        named_imports => {
            type: Synthetic,
            roles: [Import],
        },
        namespace_export => {
            type: Namespace,
            token: self,
            roles: [Module, Exported],
        },
        namespace_import => {
            type: Synthetic,
            roles: [Import],
        },
        new_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["arguments", "new_expression", "primary_expression"],
        },
        object => {
            type: Dict,
            roles: [Literal],
        },
        object_assignment_pattern => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["array_pattern", "expression", "object_pattern", "shorthand_property_identifier_pattern"],
        },
        object_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        pair => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
            children: ["computed_property_name", "expression", "number", "private_property_identifier", "property_identifier", "string"],
        },
        pair_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["assignment_pattern", "computed_property_name", "number", "pattern", "private_property_identifier", "property_identifier", "string"],
        },
        parenthesized_expression => {
            type: Synthetic,
            token: self,
        },
        program => {
            type: File,
        },
        regex => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["regex_flags", "regex_pattern"],
        },
        rest_pattern => {
            type: Spread,
            roles: [Spread, Pattern],
        },
        return_statement => {
            type: Return,
            token: self,
            roles: [Return],
        },
        sequence_expression => {
            type: Synthetic,
        },
        spread_element => {
            type: Spread,
            token: self,
            roles: [Spread],
        },
        statement_block => {
            type: Block,
            roles: [Body],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        subscript_expression => {
            type: Index,
            roles: [Index],
            children: ["expression", "optional_chain", "sequence_expression"],
        },
        switch_body => {
            type: Block,
            token: self,
            roles: [Body],
        },
        switch_case => {
            type: Case,
            roles: [Branch],
            children: ["expression", "sequence_expression", "statement"],
        },
        switch_default => {
            type: Case,
            token: self,
            roles: [Branch],
            children: ["statement"],
        },
        switch_statement => {
            type: Switch,
            children: ["parenthesized_expression", "switch_body"],
        },
        template_string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        template_substitution => {
            type: Synthetic,
        },
        ternary_expression => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["expression"],
        },
        throw_statement => {
            type: Throw,
            roles: [Throw],
        },
        try_statement => {
            type: Try,
            token: self,
            roles: [Try],
            children: ["catch_clause", "finally_clause", "statement_block"],
        },
        unary_expression => {
            type: UnaryOp,
            roles: [Operator],
            children: ["delete", "expression", "typeof", "void"],
        },
        update_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        variable_declaration => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        variable_declarator => {
            type: Variable,
            token: child("identifier"),
            roles: [Variable, Declaration],
            children: ["array_pattern", "expression", "identifier", "object_pattern"],
        },
        while_statement => {
            type: Loop,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
            props: { "props": "kind=while" },
        },
        with_statement => {
            type: Synthetic,
            token: self,
            children: ["parenthesized_expression", "statement"],
        },
        yield_expression => {
            type: Yield,
            roles: [Yield],
        },
        as => {
            type: Synthetic,
            token: self,
        },
        async => {
            type: Synthetic,
        },
        await => {
            type: Await,
            token: self,
            roles: [Await],
        },
        break => {
            type: Break,
            roles: [Break],
        },
        case => {
            type: Synthetic,
            token: self,
        },
        catch => {
            type: Catch,
            roles: [Catch],
        },
        class => {
            type: Synthetic,
            token: self,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        const => {
            type: Synthetic,
            token: self,
            roles: [Constant],
        },
        continue => {
            type: Continue,
            roles: [Continue],
        },
        debugger => {
            type: Synthetic,
            token: self,
        },
        default => {
            type: Synthetic,
        },
        delete => {
            type: Synthetic,
            token: self,
        },
        do => {
            type: Synthetic,
        },
        else => {
            type: Synthetic,
            token: self,
        },
        escape_sequence => {
            type: Synthetic,
        },
        export => {
            type: Synthetic,
            token: self,
            roles: [Exported],
        },
        extends => {
            type: Synthetic,
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        finally => {
            type: Finally,
            roles: [Finally],
        },
        for => {
            type: Synthetic,
            token: self,
        },
        from => {
            type: Synthetic,
        },
        function => {
            type: Synthetic,
            token: self,
        },
        get => {
            type: Synthetic,
            roles: [Getter],
        },
        hash_bang_line => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        html_character_reference => {
            type: Synthetic,
        },
        html_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        if => {
            type: Synthetic,
            token: self,
        },
        import => {
            type: Import,
            roles: [Import],
        },
        in => {
            type: Synthetic,
            token: self,
        },
        instanceof => {
            type: Synthetic,
        },
        jsx_text => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        let => {
            type: Synthetic,
            roles: [Mutable],
        },
        meta => {
            type: Synthetic,
            token: self,
        },
        new => {
            type: Synthetic,
        },
        null => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        of => {
            type: Synthetic,
            token: self,
        },
        optional_chain => {
            type: Synthetic,
        },
        private_property_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Private],
        },
        property_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        regex_flags => {
            type: Synthetic,
            token: self,
        },
        regex_pattern => {
            type: Synthetic,
        },
        return => {
            type: Return,
            token: self,
            roles: [Return],
        },
        set => {
            type: Synthetic,
            roles: [Setter],
        },
        shorthand_property_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        shorthand_property_identifier_pattern => {
            type: Identifier,
            token: self,
            roles: [Name, Pattern],
        },
        statement_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        static => {
            type: Synthetic,
            roles: [Static],
        },
        string_fragment => {
            type: Synthetic,
            token: self,
        },
        super => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        switch => {
            type: Synthetic,
            token: self,
        },
        target => {
            type: Synthetic,
        },
        this => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        throw => {
            type: Throw,
            roles: [Throw],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        try => {
            type: Try,
            roles: [Try],
        },
        typeof => {
            type: Synthetic,
            token: self,
        },
        undefined => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        var => {
            type: Synthetic,
            token: self,
            roles: [Mutable],
        },
        void => {
            type: Synthetic,
        },
        while => {
            type: Synthetic,
            token: self,
        },
        with => {
            type: Synthetic,
        },
        yield => {
            type: Yield,
            token: self,
            roles: [Yield],
        },
    }
};
