//! GENERATED by uastmap2rs — transpiled from `kotlin.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `kotlin` language.
pub static KOTLIN: LanguageMapping = uast_language! {
    name: "kotlin",
    extensions: [".kt", ".kts"],
    rules: {
        source_file => {
            type: File,
        },
        simple_identifier => {
            type: Identifier,
            roles: [Name],
        },
        type_identifier => {
            type: Identifier,
            roles: [Type, Name],
        },
        identifier => {
            type: Identifier,
            roles: [Name],
        },
        interpolated_identifier => {
            type: Identifier,
            roles: [Name],
        },
        boolean_literal => {
            type: Literal,
            roles: [Literal],
        },
        true => {
            type: Literal,
            roles: [Literal],
        },
        false => {
            type: Literal,
            roles: [Literal],
        },
        null_literal => {
            type: Literal,
            roles: [Literal],
        },
        integer_literal => {
            type: Literal,
            roles: [Literal],
        },
        long_literal => {
            type: Literal,
            roles: [Literal],
        },
        hex_literal => {
            type: Literal,
            roles: [Literal],
        },
        bin_literal => {
            type: Literal,
            roles: [Literal],
        },
        real_literal => {
            type: Literal,
            roles: [Literal],
        },
        unsigned_literal => {
            type: Literal,
            roles: [Literal],
        },
        character_literal => {
            type: Literal,
            roles: [Literal],
        },
        string_literal => {
            type: Literal,
            roles: [Literal],
        },
        collection_literal => {
            type: List,
            roles: [Literal],
        },
        object_literal => {
            type: Dict,
            roles: [Literal],
        },
        additive_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        multiplicative_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        comparison_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        equality_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        conjunction_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        disjunction_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        infix_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        range_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        prefix_expression => {
            type: UnaryOp,
            roles: [Operator],
        },
        postfix_expression => {
            type: UnaryOp,
            roles: [Operator],
        },
        elvis_expression => {
            type: If,
            roles: [Condition],
        },
        as_expression => {
            type: Cast,
            roles: [Type],
        },
        check_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        spread_expression => {
            type: Spread,
            roles: [Spread],
        },
        if_expression => {
            type: If,
            roles: [Condition],
        },
        when_expression => {
            type: Match,
            roles: [Match],
        },
        when_subject => {
            type: Synthetic,
        },
        when_entry => {
            type: Case,
            roles: [Branch],
        },
        when_condition => {
            type: Pattern,
            roles: [Pattern],
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
            props: { "props": "kind=for" },
        },
        while_statement => {
            type: Loop,
            roles: [Loop],
            props: { "props": "kind=while" },
        },
        do_while_statement => {
            type: Loop,
            roles: [Loop],
            props: { "props": "kind=do-while" },
        },
        jump_expression => {
            type: Synthetic,
        },
        return => {
            type: Return,
            roles: [Return],
        },
        break => {
            type: Break,
            roles: [Break],
        },
        continue => {
            type: Continue,
            roles: [Continue],
        },
        throw => {
            type: Throw,
            roles: [Throw],
        },
        try_expression => {
            type: Try,
            roles: [Try],
        },
        catch_block => {
            type: Catch,
            roles: [Catch],
        },
        finally_block => {
            type: Finally,
            roles: [Finally],
        },
        try => {
            type: Synthetic,
        },
        catch => {
            type: Synthetic,
        },
        finally => {
            type: Synthetic,
        },
        function_declaration => {
            type: Function,
            roles: [Function, Declaration],
        },
        anonymous_function => {
            type: Function,
            roles: [Function, Declaration],
        },
        function_body => {
            type: Block,
            roles: [Body],
        },
        function_value_parameters => {
            type: Synthetic,
        },
        function_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        function_type_parameters => {
            type: Synthetic,
        },
        fun => {
            type: Synthetic,
        },
        lambda_literal => {
            type: Lambda,
            roles: [Lambda],
        },
        annotated_lambda => {
            type: Lambda,
            roles: [Lambda],
        },
        lambda_parameters => {
            type: Synthetic,
        },
        parameter => {
            type: Parameter,
            roles: [Parameter],
        },
        parameter_with_optional_type => {
            type: Parameter,
            roles: [Parameter],
        },
        type_parameter => {
            type: Parameter,
            roles: [Parameter, Type],
        },
        type_parameters => {
            type: Synthetic,
        },
        class_declaration => {
            type: Class,
            roles: [Class, Declaration],
        },
        class_body => {
            type: Block,
            roles: [Body],
        },
        class_parameter => {
            type: Parameter,
            roles: [Parameter, Declaration],
        },
        class => {
            type: Synthetic,
        },
        object_declaration => {
            type: Class,
            roles: [Class, Declaration],
        },
        companion_object => {
            type: Class,
            roles: [Class, Static],
        },
        object => {
            type: Synthetic,
        },
        companion => {
            type: Synthetic,
        },
        interface => {
            type: Interface,
            roles: [Interface, Declaration],
        },
        enum => {
            type: Synthetic,
        },
        enum_class_body => {
            type: Block,
            roles: [Body],
        },
        enum_entry => {
            type: EnumMember,
            roles: [Member, Declaration],
        },
        primary_constructor => {
            type: Function,
            roles: [Function, Declaration],
        },
        secondary_constructor => {
            type: Function,
            roles: [Function, Declaration],
        },
        constructor => {
            type: Synthetic,
        },
        constructor_delegation_call => {
            type: Call,
            roles: [Call],
        },
        constructor_invocation => {
            type: Call,
            roles: [Call],
        },
        anonymous_initializer => {
            type: Block,
            roles: [Body],
        },
        init => {
            type: Synthetic,
        },
        property_declaration => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        property_delegate => {
            type: Synthetic,
        },
        property => {
            type: Synthetic,
        },
        field => {
            type: Field,
            roles: [Member],
        },
        getter => {
            type: Getter,
            roles: [Getter],
        },
        setter => {
            type: Setter,
            roles: [Setter],
        },
        get => {
            type: Synthetic,
        },
        set => {
            type: Synthetic,
        },
        variable_declaration => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        multi_variable_declaration => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        val => {
            type: Synthetic,
            roles: [Constant],
        },
        var => {
            type: Synthetic,
            roles: [Mutable],
        },
        assignment => {
            type: Assignment,
            roles: [Assignment],
        },
        directly_assignable_expression => {
            type: Synthetic,
        },
        call_expression => {
            type: Call,
            roles: [Call],
        },
        call_suffix => {
            type: Synthetic,
        },
        callable_reference => {
            type: Call,
            roles: [Call, Reference],
        },
        value_arguments => {
            type: Synthetic,
        },
        value_argument => {
            type: Synthetic,
            roles: [Argument],
        },
        indexing_expression => {
            type: Index,
            roles: [Index],
        },
        indexing_suffix => {
            type: Synthetic,
        },
        navigation_expression => {
            type: Synthetic,
        },
        navigation_suffix => {
            type: Synthetic,
        },
        import_list => {
            type: Synthetic,
        },
        import_header => {
            type: Import,
            roles: [Import],
        },
        import_alias => {
            type: Synthetic,
        },
        import => {
            type: Synthetic,
        },
        wildcard_import => {
            type: Synthetic,
        },
        package_header => {
            type: Package,
            roles: [Module],
        },
        package => {
            type: Synthetic,
        },
        annotation => {
            type: Attribute,
            roles: [Attribute],
        },
        file_annotation => {
            type: Attribute,
            roles: [Attribute],
        },
        use_site_target => {
            type: Synthetic,
        },
        user_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        nullable_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        not_nullable_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        parenthesized_type => {
            type: Synthetic,
        },
        parenthesized_user_type => {
            type: Synthetic,
        },
        type_arguments => {
            type: Synthetic,
        },
        type_projection => {
            type: Synthetic,
        },
        type_projection_modifiers => {
            type: Synthetic,
        },
        type_constraint => {
            type: Synthetic,
        },
        type_constraints => {
            type: Synthetic,
        },
        type_alias => {
            type: Synthetic,
        },
        typealias => {
            type: Synthetic,
        },
        receiver_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        modifiers => {
            type: Synthetic,
        },
        visibility_modifier => {
            type: Synthetic,
        },
        inheritance_modifier => {
            type: Synthetic,
        },
        member_modifier => {
            type: Synthetic,
        },
        function_modifier => {
            type: Synthetic,
        },
        class_modifier => {
            type: Synthetic,
        },
        property_modifier => {
            type: Synthetic,
        },
        parameter_modifier => {
            type: Synthetic,
        },
        parameter_modifiers => {
            type: Synthetic,
        },
        type_parameter_modifiers => {
            type: Synthetic,
        },
        type_modifiers => {
            type: Synthetic,
        },
        platform_modifier => {
            type: Synthetic,
        },
        reification_modifier => {
            type: Synthetic,
        },
        variance_modifier => {
            type: Synthetic,
        },
        public => {
            type: Synthetic,
            roles: [Public],
        },
        private => {
            type: Synthetic,
            roles: [Private],
        },
        protected => {
            type: Synthetic,
        },
        internal => {
            type: Synthetic,
        },
        open => {
            type: Synthetic,
        },
        final => {
            type: Synthetic,
        },
        abstract => {
            type: Synthetic,
        },
        sealed => {
            type: Synthetic,
        },
        override => {
            type: Synthetic,
        },
        suspend => {
            type: Synthetic,
        },
        inline => {
            type: Synthetic,
        },
        noinline => {
            type: Synthetic,
        },
        crossinline => {
            type: Synthetic,
        },
        infix => {
            type: Synthetic,
        },
        operator => {
            type: Synthetic,
        },
        tailrec => {
            type: Synthetic,
        },
        external => {
            type: Synthetic,
        },
        inner => {
            type: Synthetic,
        },
        data => {
            type: Synthetic,
        },
        value => {
            type: Synthetic,
        },
        lateinit => {
            type: Synthetic,
        },
        vararg => {
            type: Synthetic,
        },
        expect => {
            type: Synthetic,
        },
        actual => {
            type: Synthetic,
        },
        const => {
            type: Synthetic,
            roles: [Constant],
        },
        if => {
            type: Synthetic,
        },
        else => {
            type: Synthetic,
        },
        when => {
            type: Synthetic,
        },
        for => {
            type: Synthetic,
        },
        while => {
            type: Synthetic,
        },
        do => {
            type: Synthetic,
        },
        in => {
            type: Synthetic,
        },
        out => {
            type: Synthetic,
        },
        is => {
            type: Synthetic,
        },
        as => {
            type: Synthetic,
        },
        by => {
            type: Synthetic,
        },
        where => {
            type: Synthetic,
        },
        dynamic => {
            type: Synthetic,
        },
        this => {
            type: Identifier,
            roles: [Reference],
        },
        this_expression => {
            type: Identifier,
            roles: [Reference],
        },
        super => {
            type: Identifier,
            roles: [Reference],
        },
        super_expression => {
            type: Identifier,
            roles: [Reference],
        },
        control_structure_body => {
            type: Block,
            roles: [Body],
        },
        statements => {
            type: Synthetic,
        },
        binding_pattern_kind => {
            type: Pattern,
            roles: [Pattern],
        },
        line_comment => {
            type: Comment,
            roles: [Comment],
        },
        multiline_comment => {
            type: Comment,
            roles: [Comment],
        },
        shebang_line => {
            type: Comment,
            roles: [Comment],
        },
        explicit_delegation => {
            type: Synthetic,
        },
        delegation_specifier => {
            type: Synthetic,
        },
        delegate => {
            type: Synthetic,
        },
        interpolated_expression => {
            type: Synthetic,
        },
        string_content => {
            type: Synthetic,
        },
        character_escape_seq => {
            type: Synthetic,
        },
        range_test => {
            type: Synthetic,
        },
        type_test => {
            type: Synthetic,
        },
        label => {
            type: Synthetic,
        },
        parenthesized_expression => {
            type: Synthetic,
        },
        L => {
            type: Synthetic,
        },
        receiver => {
            type: Synthetic,
        },
        param => {
            type: Synthetic,
        },
        setparam => {
            type: Synthetic,
        },
        file => {
            type: Synthetic,
        },
    }
};
