//! GENERATED by uastmap2rs — transpiled from `lua.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `lua` language.
pub static LUA: LanguageMapping = uast_language! {
    name: "lua",
    extensions: [".lua"],
    rules: {
        chunk => {
            type: File,
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        number => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["escape_sequence", "string_content"],
        },
        string_content => {
            type: Synthetic,
            token: self,
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        nil => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        function_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["block", "dot_index_expression", "identifier", "method_index_expression", "parameters"],
        },
        function_definition => {
            type: Lambda,
            roles: [Lambda],
            children: ["block", "parameters"],
        },
        function_call => {
            type: Call,
            roles: [Call],
            children: ["arguments", "function_call", "identifier", "method_index_expression", "parenthesized_expression", "variable"],
        },
        parameters => {
            type: Synthetic,
            token: self,
            children: ["identifier", "vararg_expression"],
        },
        arguments => {
            type: List,
            roles: [Argument],
        },
        block => {
            type: Block,
            roles: [Body],
        },
        variable => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        variable_declaration => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
            children: ["assignment_statement"],
        },
        variable_list => {
            type: List,
            children: ["attribute", "identifier", "variable"],
        },
        // `M.foo = function(...) end` — the standard Lua module-function
        // idiom; as a plain Assignment it was invisible to function
        // detection.
        assignment_function ("(assignment_statement)") => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["expression_list", "variable_list"],
            when: ["expression_list.value.type == \"function_definition\""],
        },
        assignment_statement => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["expression_list", "variable_list"],
        },
        expression_list => {
            type: List,
            token: self,
        },
        binary_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["expression", "identifier", "number", "string"],
        },
        unary_expression => {
            type: UnaryOp,
            roles: [Operator],
            children: ["expression"],
        },
        table_constructor => {
            type: Dict,
            token: self,
            roles: [Literal],
            children: ["field"],
        },
        // Table-field functions (`{ foo = function() ... end }`) are how Lua
        // modules and specs define most behavior.
        field_function ("(field)") => {
            type: Function,
            roles: [Function, Declaration],
            children: ["expression", "identifier"],
            when: ["value.type == \"function_definition\""],
        },
        field => {
            type: KeyValue,
            roles: [Key, Value],
            children: ["expression", "identifier"],
        },
        if_statement => {
            type: If,
            roles: [Condition],
            children: ["block", "else_statement", "elseif_statement", "expression"],
        },
        elseif_statement => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["block", "expression"],
        },
        else_statement => {
            type: Block,
            roles: [Body],
            children: ["block"],
        },
        for_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["block", "for_generic_clause", "for_numeric_clause"],
        },
        for_numeric_clause => {
            type: Synthetic,
            children: ["expression", "identifier"],
        },
        for_generic_clause => {
            type: Synthetic,
            token: self,
        },
        while_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["block", "expression"],
        },
        repeat_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["block", "expression"],
        },
        do_statement => {
            type: Block,
            roles: [Body],
            children: ["block"],
        },
        return_statement => {
            type: Return,
            roles: [Return],
        },
        break_statement => {
            type: Break,
            token: self,
            roles: [Break],
        },
        goto_statement => {
            type: Synthetic,
            token: self,
        },
        label_statement => {
            type: Synthetic,
            token: self,
        },
        bracket_index_expression => {
            type: Index,
            token: self,
            roles: [Index],
            children: ["expression", "function_call", "parenthesized_expression", "variable"],
        },
        dot_index_expression => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["function_call", "identifier", "parenthesized_expression", "variable"],
        },
        method_index_expression => {
            type: Identifier,
            roles: [Name, Member],
            children: ["function_call", "identifier", "parenthesized_expression", "variable"],
        },
        attribute => {
            type: Attribute,
            roles: [Attribute],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
            children: ["comment_content"],
        },
        comment_content => {
            type: Synthetic,
            token: self,
        },
        parenthesized_expression => {
            type: Synthetic,
        },
        vararg_expression => {
            type: Spread,
            roles: [Spread],
        },
        declaration => {
            type: Synthetic,
        },
        expression => {
            type: Synthetic,
            token: self,
        },
        statement => {
            type: Synthetic,
        },
        empty_statement => {
            type: Synthetic,
        },
        hash_bang_line => {
            type: Synthetic,
        },
        and => {
            type: Synthetic,
        },
        or => {
            type: Synthetic,
        },
        not => {
            type: Synthetic,
        },
        do => {
            type: Synthetic,
            token: self,
        },
        end => {
            type: Synthetic,
        },
        if => {
            type: Synthetic,
        },
        then => {
            type: Synthetic,
            token: self,
        },
        else => {
            type: Synthetic,
        },
        elseif => {
            type: Synthetic,
            token: self,
        },
        for => {
            type: Synthetic,
            token: self,
        },
        in => {
            type: Synthetic,
            token: self,
        },
        while => {
            type: Synthetic,
            token: self,
        },
        repeat => {
            type: Synthetic,
            token: self,
        },
        until => {
            type: Synthetic,
            token: self,
        },
        return => {
            type: Synthetic,
        },
        function => {
            type: Synthetic,
        },
        local => {
            type: Synthetic,
        },
        goto => {
            type: Synthetic,
            token: self,
        },
        escape_sequence => {
            type: Synthetic,
            token: self,
        },
    }
};
