//! GENERATED by uastmap2rs — transpiled from `perl.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `perl` language.
pub static PERL: LanguageMapping = uast_language! {
    name: "perl",
    extensions: [".pl", ".pm", ".t"],
    rules: {
        source_file => {
            type: File,
        },
        use_statement => {
            type: Import,
            token: self,
            roles: [Import],
        },
        require_statement => {
            type: Import,
            token: self,
            roles: [Import],
        },
        package_statement => {
            type: Module,
            roles: [Declaration],
        },
        package => {
            type: Identifier,
            roles: [Import, Name],
        },
        subroutine_declaration_statement => {
            type: Function,
            roles: [Function, Declaration],
        },
        function => {
            type: Identifier,
            roles: [Name],
        },
        bareword => {
            type: Identifier,
            roles: [Name],
        },
        block => {
            type: Block,
            roles: [Body],
        },
        conditional_statement => {
            type: If,
            roles: [Branch],
        },
        else => {
            type: If,
            roles: [Branch],
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
        },
        foreach_statement => {
            type: Loop,
            roles: [Loop],
        },
        loop_statement => {
            type: Loop,
            roles: [Loop],
        },
        while_statement => {
            type: Loop,
            roles: [Loop],
        },
        until_statement => {
            type: Loop,
            roles: [Loop],
        },
        loopex_expression => {
            type: Break,
            roles: [Break],
        },
        binary_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        assignment_expression => {
            type: Assignment,
            roles: [Assignment],
        },
        variable_declaration => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        scalar => {
            type: Identifier,
            roles: [Variable],
        },
        array => {
            type: Identifier,
            roles: [Variable],
        },
        hash => {
            type: Identifier,
            roles: [Variable],
        },
        container_variable => {
            type: Identifier,
            roles: [Variable],
        },
        varname => {
            type: Identifier,
            roles: [Name],
        },
        array_element_expression => {
            type: Index,
            roles: [Index],
        },
        hash_element_expression => {
            type: Index,
            roles: [Index],
        },
        list_expression => {
            type: List,
            roles: [Literal],
        },
        number => {
            type: Literal,
            roles: [Literal],
        },
        string_literal => {
            type: Literal,
            roles: [Literal],
        },
        interpolated_string_literal => {
            type: Literal,
            roles: [Literal],
        },
        string_content => {
            type: Literal,
            roles: [Literal],
        },
        autoquoted_bareword => {
            type: Literal,
            roles: [Literal],
        },
        ambiguous_function_call_expression => {
            type: Call,
            roles: [Call],
        },
        function_call_expression => {
            type: Call,
            roles: [Call],
        },
        method_call_expression => {
            type: Call,
            roles: [Call],
        },
        return_expression => {
            type: Return,
            roles: [Return],
        },
        refgen_expression => {
            type: UnaryOp,
            roles: [Operator],
        },
        expression_statement => {
            type: Block,
            roles: [Body],
        },
        comment => {
            type: Comment,
            roles: [Comment],
        },
        escape_sequence => {
            type: Literal,
            roles: [Literal],
        },
    }
};
