//! GENERATED by uastmap2rs — transpiled from `proto.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `proto` language.
pub static PROTO: LanguageMapping = uast_language! {
    name: "proto",
    extensions: [".proto"],
    rules: {
        source_file => {
            type: File,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        syntax => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        edition => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        package => {
            type: Module,
            roles: [Module, Declaration],
        },
        import => {
            type: Import,
            token: self,
            roles: [Import],
        },
        message => {
            type: Struct,
            roles: [Struct, Declaration],
        },
        message_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        message_body => {
            type: Block,
            roles: [Body],
        },
        field => {
            type: Property,
            roles: [Member],
        },
        field_number => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        field_option => {
            type: Property,
            roles: [Member],
        },
        field_options => {
            type: List,
            roles: [Literal],
        },
        map_field => {
            type: Property,
            roles: [Member],
        },
        oneof => {
            type: Property,
            roles: [Member],
        },
        oneof_field => {
            type: Property,
            roles: [Member],
        },
        enum => {
            type: Enum,
            roles: [Enum, Declaration],
        },
        enum_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        enum_body => {
            type: Block,
            roles: [Body],
        },
        enum_field => {
            type: EnumMember,
            roles: [Member],
        },
        enum_value_option => {
            type: Property,
            roles: [Member],
        },
        service => {
            type: Interface,
            roles: [Interface, Declaration],
        },
        service_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        rpc => {
            type: Method,
            roles: [Method, Declaration],
        },
        rpc_name => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        option => {
            type: Property,
            roles: [Member],
        },
        extend => {
            type: Struct,
            roles: [Struct],
        },
        extensions => {
            type: Synthetic,
        },
        reserved => {
            type: Synthetic,
        },
        reserved_field_names => {
            type: List,
            roles: [Literal],
        },
        ranges => {
            type: List,
            roles: [Literal],
        },
        range => {
            type: Literal,
            roles: [Literal],
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        full_ident => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        message_or_enum_type => {
            type: Identifier,
            roles: [Name, Type],
        },
        type => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        key_type => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        constant => {
            type: Literal,
            roles: [Literal],
        },
        int_lit => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        decimal_lit => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        octal_lit => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        hex_lit => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        float_lit => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        bool => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        block_lit => {
            type: Block,
            roles: [Body],
        },
        empty_statement => {
            type: Synthetic,
        },
        escape_sequence => {
            type: Synthetic,
            token: self,
        },
        reserved_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        returns => {
            type: Synthetic,
            token: self,
        },
        stream => {
            type: Synthetic,
            token: self,
        },
        optional => {
            type: Synthetic,
            token: self,
        },
        repeated => {
            type: Synthetic,
            token: self,
        },
        required => {
            type: Synthetic,
            token: self,
        },
        public => {
            type: Synthetic,
            token: self,
        },
        weak => {
            type: Synthetic,
            token: self,
        },
        to => {
            type: Synthetic,
            token: self,
        },
        max => {
            type: Synthetic,
            token: self,
        },
        map => {
            type: Synthetic,
            token: self,
        },
        int32 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        int64 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        uint32 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        uint64 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        sint32 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        sint64 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        fixed32 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        fixed64 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        sfixed32 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        sfixed64 => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        float => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        double => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        bytes => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
    }
};
