//! GENERATED by uastmap2rs — transpiled from `r.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `r` language.
pub static R: LanguageMapping = uast_language! {
    name: "r",
    extensions: [".r", ".R", ".rmd", ".Rmd"],
    rules: {
        program => {
            type: File,
        },
        call => {
            type: Call,
            roles: [Call],
        },
        arguments => {
            type: List,
            roles: [Argument],
        },
        argument => {
            type: Identifier,
            roles: [Argument],
        },
        function_definition => {
            type: Function,
            roles: [Function, Declaration],
        },
        parameters => {
            type: Block,
            roles: [Parameter],
        },
        parameter => {
            type: Parameter,
            roles: [Parameter],
        },
        braced_expression => {
            type: Block,
            roles: [Body],
        },
        if_statement => {
            type: If,
            roles: [Branch],
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
        },
        while_statement => {
            type: Loop,
            roles: [Loop],
        },
        repeat_statement => {
            type: Loop,
            roles: [Loop],
        },
        break => {
            type: Break,
            roles: [Break],
        },
        next => {
            type: Continue,
            roles: [Continue],
        },
        return => {
            type: Return,
            roles: [Return],
        },
        binary_operator => {
            type: BinaryOp,
            roles: [Operator],
        },
        unary_operator => {
            type: UnaryOp,
            roles: [Operator],
        },
        identifier => {
            type: Identifier,
            roles: [Name],
        },
        float => {
            type: Literal,
            roles: [Literal],
        },
        integer => {
            type: Literal,
            roles: [Literal],
        },
        complex => {
            type: Literal,
            roles: [Literal],
        },
        string => {
            type: Literal,
            roles: [Literal],
        },
        string_content => {
            type: Literal,
            roles: [Literal],
        },
        true => {
            type: Literal,
            roles: [Literal],
        },
        false => {
            type: Literal,
            roles: [Literal],
        },
        null => {
            type: Literal,
            roles: [Literal],
        },
        na => {
            type: Literal,
            roles: [Literal],
        },
        inf => {
            type: Literal,
            roles: [Literal],
        },
        nan => {
            type: Literal,
            roles: [Literal],
        },
        comment => {
            type: Comment,
            roles: [Comment],
        },
        comma => {
            type: Identifier,
            roles: [Name],
        },
        subset => {
            type: Index,
            roles: [Index],
        },
        subset2 => {
            type: Index,
            roles: [Index],
        },
        extract_operator => {
            type: Field,
            roles: [Member],
        },
        formula => {
            type: BinaryOp,
            roles: [Operator],
        },
        special => {
            type: Identifier,
            roles: [Operator],
        },
    }
};
