//! GENERATED by uastmap2rs — transpiled from `rego.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `rego` language.
pub static REGO: LanguageMapping = uast_language! {
    name: "rego",
    extensions: [".rego"],
    rules: {
        source_file => {
            type: File,
        },
        module => {
            type: Module,
            roles: [Module],
        },
        package => {
            type: Module,
            roles: [Module],
        },
        policy => {
            type: Block,
            roles: [Body],
        },
        import => {
            type: Import,
            token: self,
            roles: [Import],
        },
        var => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        ref => {
            type: MemberAccess,
            roles: [Member],
        },
        ref_arg => {
            type: Synthetic,
        },
        ref_arg_dot => {
            type: Identifier,
            roles: [Name, Member],
        },
        ref_arg_brack => {
            type: Index,
            roles: [Index],
        },
        rule => {
            type: Function,
            roles: [Function, Declaration],
        },
        rule_head => {
            type: Identifier,
            roles: [Name, Declaration],
        },
        rule_body => {
            type: Block,
            roles: [Body],
        },
        default => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        boolean => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        null => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        scalar => {
            type: Literal,
            roles: [Literal],
        },
        literal => {
            type: Literal,
            roles: [Literal],
        },
        object => {
            type: Dict,
            roles: [Literal],
        },
        object_item => {
            type: KeyValue,
            roles: [Key, Value],
        },
        set => {
            type: Set,
            roles: [Literal],
        },
        non_empty_set => {
            type: Set,
            roles: [Literal],
        },
        array => {
            type: List,
            roles: [Literal],
        },
        array_compr => {
            type: List,
            roles: [Literal],
        },
        set_compr => {
            type: Set,
            roles: [Literal],
        },
        object_compr => {
            type: Dict,
            roles: [Literal],
        },
        expr => {
            type: Synthetic,
        },
        term => {
            type: Synthetic,
        },
        expr_infix => {
            type: BinaryOp,
            roles: [Operator],
        },
        expr_call => {
            type: Call,
            roles: [Call],
        },
        infix_operator => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        bool_operator => {
            type: Identifier,
            token: self,
            roles: [Operator],
        },
        assignment_operator => {
            type: Synthetic,
        },
        assignment => {
            type: Assignment,
            roles: [Assignment],
        },
        if => {
            type: If,
            roles: [Condition],
        },
        query => {
            type: Block,
            roles: [Body],
        },
        some_decl => {
            type: Variable,
            roles: [Variable, Declaration],
        },
        some => {
            type: Synthetic,
        },
        membership => {
            type: BinaryOp,
            roles: [Operator],
        },
        in => {
            type: Synthetic,
        },
        not => {
            type: UnaryOp,
            roles: [Operator],
        },
        fn_name => {
            type: Identifier,
            roles: [Name],
        },
        fn_args => {
            type: List,
            roles: [Literal],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        open_paren => {
            type: Synthetic,
        },
        close_paren => {
            type: Synthetic,
        },
        open_bracket => {
            type: Synthetic,
        },
        close_bracket => {
            type: Synthetic,
        },
        open_curly => {
            type: Synthetic,
        },
        close_curly => {
            type: Synthetic,
        },
        with => {
            type: Synthetic,
        },
        every => {
            type: Loop,
            roles: [Loop],
        },
        contains => {
            type: Synthetic,
        },
        else => {
            type: Block,
            roles: [Body],
        },
    }
};
