//! GENERATED by uastmap2rs — transpiled from `swift.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `swift` language.
pub static SWIFT: LanguageMapping = uast_language! {
    name: "swift",
    extensions: [".swift"],
    rules: {
        source_file => {
            type: File,
        },
        simple_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        identifier => {
            type: Identifier,
            roles: [Name],
        },
        import_declaration => {
            type: Import,
            roles: [Import],
        },
        import => {
            type: Synthetic,
            token: self,
        },
        class_declaration => {
            type: Class,
            roles: [Class, Declaration],
            children: ["class_body", "type_identifier"],
        },
        class_body => {
            type: Block,
            token: self,
            roles: [Body],
        },
        class => {
            type: Synthetic,
            token: self,
        },
        struct_declaration => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["type_identifier"],
        },
        struct => {
            type: Synthetic,
            token: self,
        },
        enum => {
            type: Synthetic,
        },
        enum_class_body => {
            type: Block,
            token: self,
            roles: [Body],
        },
        enum_entry => {
            type: EnumMember,
            roles: [Member, Declaration],
            children: ["simple_identifier"],
        },
        enum_type_parameters => {
            type: Synthetic,
            token: self,
        },
        protocol_declaration => {
            type: Interface,
            roles: [Interface, Declaration],
            children: ["protocol_body", "type_identifier"],
        },
        protocol_body => {
            type: Block,
            roles: [Body],
            children: ["protocol_function_declaration"],
        },
        protocol => {
            type: Synthetic,
            token: self,
        },
        Protocol => {
            type: Synthetic,
            token: self,
        },
        function_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["function_body", "simple_identifier", "parameter"],
        },
        function_body => {
            type: Block,
            roles: [Body],
        },
        function => {
            type: Synthetic,
            token: self,
        },
        func => {
            type: Synthetic,
        },
        function_modifier => {
            type: Synthetic,
        },
        function_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["type"],
        },
        protocol_function_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["simple_identifier", "parameter"],
        },
        init_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["function_body", "parameter"],
        },
        deinit_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["function_body"],
        },
        init => {
            type: Synthetic,
            token: self,
        },
        deinit => {
            type: Synthetic,
        },
        parameter => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["simple_identifier", "type_annotation"],
        },
        parameter_modifier => {
            type: Synthetic,
        },
        parameter_modifiers => {
            type: Synthetic,
            token: self,
        },
        lambda_parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["simple_identifier", "type_annotation"],
        },
        type_parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["simple_identifier"],
        },
        type_parameter_modifiers => {
            type: Synthetic,
            token: self,
        },
        type_parameter_pack => {
            type: Synthetic,
        },
        type_parameters => {
            type: Synthetic,
            token: self,
        },
        value_parameter_pack => {
            type: Synthetic,
            token: self,
        },
        property_declaration => {
            type: Property,
            roles: [Member],
            children: ["pattern", "type_annotation", "computed_property"],
        },
        property_modifier => {
            type: Synthetic,
            token: self,
        },
        property_behavior_modifier => {
            type: Synthetic,
            token: self,
        },
        computed_property => {
            type: Property,
            roles: [Member],
        },
        computed_getter => {
            type: Getter,
            roles: [Getter],
        },
        computed_setter => {
            type: Setter,
            token: self,
            roles: [Setter],
        },
        computed_modify => {
            type: Synthetic,
            token: self,
        },
        protocol_property_declaration => {
            type: Property,
            roles: [Member],
            children: ["pattern"],
        },
        protocol_property_requirements => {
            type: Synthetic,
            token: self,
        },
        if_statement => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["if_statement", "pattern"],
        },
        if => {
            type: Synthetic,
            token: self,
        },
        else => {
            type: Synthetic,
            token: self,
        },
        guard_statement => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["pattern"],
        },
        guard => {
            type: Synthetic,
            token: self,
        },
        for_statement => {
            type: Loop,
            roles: [Loop],
            children: ["pattern"],
        },
        for => {
            type: Synthetic,
            token: self,
        },
        while_statement => {
            type: Loop,
            roles: [Loop],
            children: ["pattern"],
        },
        while => {
            type: Synthetic,
            token: self,
        },
        repeat_while_statement => {
            type: Loop,
            roles: [Loop],
            children: ["pattern"],
        },
        repeat => {
            type: Synthetic,
        },
        in => {
            type: Synthetic,
        },
        switch_statement => {
            type: Switch,
            token: self,
            children: ["switch_entry"],
        },
        switch => {
            type: Synthetic,
            token: self,
        },
        switch_entry => {
            type: Case,
            token: self,
            roles: [Branch],
        },
        switch_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        case => {
            type: Synthetic,
            token: self,
        },
        default_keyword => {
            type: Synthetic,
            token: self,
        },
        do_statement => {
            type: Try,
            roles: [Try],
        },
        do => {
            type: Synthetic,
            token: self,
        },
        catch_block => {
            type: Catch,
            token: self,
            roles: [Catch],
            children: ["pattern"],
        },
        catch_keyword => {
            type: Synthetic,
        },
        try_expression => {
            type: Try,
            roles: [Try],
        },
        try => {
            type: Synthetic,
            token: self,
        },
        try_operator => {
            type: Synthetic,
            token: self,
        },
        throw_keyword => {
            type: Throw,
            token: self,
            roles: [Throw],
        },
        throws => {
            type: Synthetic,
            token: self,
        },
        return => {
            type: Return,
            roles: [Return],
        },
        break => {
            type: Break,
            token: self,
            roles: [Break],
        },
        continue => {
            type: Continue,
            token: self,
            roles: [Continue],
        },
        fallthrough => {
            type: Synthetic,
            token: self,
        },
        yield => {
            type: Yield,
            roles: [Yield],
        },
        control_transfer_statement => {
            type: Synthetic,
            token: self,
        },
        comparison_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        equality_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        additive_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        multiplicative_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        conjunction_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        disjunction_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        bitwise_operation => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        infix_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        prefix_expression => {
            type: UnaryOp,
            roles: [Operator],
        },
        postfix_expression => {
            type: UnaryOp,
            roles: [Operator],
        },
        nil_coalescing_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        ternary_expression => {
            type: If,
            roles: [Condition],
        },
        range_expression => {
            type: Slice,
        },
        open_end_range_expression => {
            type: Slice,
        },
        open_start_range_expression => {
            type: Slice,
            token: self,
        },
        fully_open_range => {
            type: Slice,
            token: self,
        },
        as_expression => {
            type: Cast,
            token: self,
        },
        as_operator => {
            type: Synthetic,
        },
        as => {
            type: Synthetic,
        },
        is => {
            type: Synthetic,
            token: self,
        },
        check_expression => {
            type: BinaryOp,
            roles: [Operator],
        },
        assignment => {
            type: Assignment,
            token: self,
            roles: [Assignment],
        },
        call_expression => {
            type: Call,
            token: self,
            roles: [Call],
        },
        call_suffix => {
            type: Synthetic,
            children: ["simple_identifier"],
        },
        constructor_expression => {
            type: Call,
            token: self,
            roles: [Call],
        },
        constructor_suffix => {
            type: Synthetic,
            children: ["simple_identifier"],
        },
        navigation_expression => {
            type: Synthetic,
            children: ["navigation_suffix"],
        },
        navigation_suffix => {
            type: Synthetic,
            token: self,
            children: ["simple_identifier"],
        },
        subscript_declaration => {
            type: Index,
            roles: [Index],
        },
        subscript => {
            type: Synthetic,
        },
        key_path_expression => {
            type: Synthetic,
            token: self,
        },
        key_path_string_expression => {
            type: Synthetic,
        },
        keyPath => {
            type: Synthetic,
        },
        selector_expression => {
            type: Synthetic,
            token: self,
        },
        selector => {
            type: Synthetic,
            token: self,
        },
        self_expression => {
            type: Identifier,
            roles: [Reference],
        },
        self => {
            type: Synthetic,
        },
        super_expression => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        super => {
            type: Synthetic,
            token: self,
        },
        tuple_expression => {
            type: Tuple,
        },
        tuple_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["tuple_type_item"],
        },
        tuple_type_item => {
            type: Synthetic,
        },
        lambda_literal => {
            type: Lambda,
            token: self,
            roles: [Lambda],
            children: ["capture_list", "lambda_function_type"],
        },
        lambda_function_type => {
            type: Synthetic,
            token: self,
        },
        lambda_function_type_parameters => {
            type: Synthetic,
        },
        capture_list => {
            type: Synthetic,
            token: self,
        },
        capture_list_item => {
            type: Synthetic,
        },
        array_literal => {
            type: List,
            token: self,
        },
        dictionary_literal => {
            type: Dict,
        },
        array_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        dictionary_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        boolean_literal => {
            type: Literal,
            roles: [Literal],
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        nil => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        real_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        hex_literal => {
            type: Literal,
            roles: [Literal],
        },
        oct_literal => {
            type: Literal,
            roles: [Literal],
        },
        bin_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        line_string_literal => {
            type: Literal,
            roles: [Literal],
            children: ["interpolated_expression", "line_str_text"],
        },
        multi_line_string_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
            children: ["interpolated_expression", "multi_line_str_text"],
        },
        raw_string_literal => {
            type: Literal,
            roles: [Literal],
        },
        regex_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        special_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        playground_literal => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        colorLiteral => {
            type: Literal,
            roles: [Literal],
        },
        fileLiteral => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        imageLiteral => {
            type: Literal,
            roles: [Literal],
        },
        line_str_text => {
            type: Synthetic,
            token: self,
        },
        multi_line_str_text => {
            type: Synthetic,
        },
        str_escaped_char => {
            type: Synthetic,
            token: self,
        },
        interpolated_expression => {
            type: Synthetic,
        },
        raw_str_interpolation => {
            type: Synthetic,
            token: self,
            children: ["interpolated_expression"],
        },
        raw_str_part => {
            type: Synthetic,
        },
        raw_str_end_part => {
            type: Synthetic,
        },
        raw_str_interpolation_start => {
            type: Synthetic,
            token: self,
        },
        raw_str_continuing_indicator => {
            type: Synthetic,
            token: self,
        },
        type_annotation => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        type_identifier => {
            type: Identifier,
            token: self,
            roles: [Name, Type],
        },
        user_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        optional_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        opaque_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        existential_type => {
            type: TypeAnnotation,
            roles: [Type],
        },
        metatype => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        protocol_composition_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        suppressed_constraint => {
            type: Synthetic,
            children: ["type_identifier"],
        },
        type_arguments => {
            type: Synthetic,
        },
        type_constraint => {
            type: Synthetic,
            token: self,
        },
        type_constraints => {
            type: Synthetic,
        },
        type_modifiers => {
            type: Synthetic,
        },
        type_pack_expansion => {
            type: Synthetic,
            token: self,
        },
        typealias_declaration => {
            type: Synthetic,
            children: ["type_identifier"],
        },
        typealias => {
            type: Synthetic,
        },
        Type => {
            type: Synthetic,
        },
        pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["simple_identifier"],
        },
        wildcard_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        value_binding_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        attribute => {
            type: Attribute,
            token: child("identifier"),
            roles: [Attribute],
        },
        precedence_group_attribute => {
            type: Attribute,
            token: self,
            roles: [Attribute],
        },
        precedence_group_attributes => {
            type: Synthetic,
        },
        precedence_group_declaration => {
            type: Synthetic,
            token: self,
        },
        precedencegroup => {
            type: Synthetic,
        },
        comment => {
            type: Comment,
            roles: [Comment],
        },
        multiline_comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        await_expression => {
            type: Await,
            token: self,
            roles: [Await],
        },
        await => {
            type: Synthetic,
        },
        async => {
            type: Synthetic,
        },
        member_modifier => {
            type: Synthetic,
        },
        modifiers => {
            type: Synthetic,
        },
        ownership_modifier => {
            type: Synthetic,
        },
        visibility_modifier => {
            type: Synthetic,
        },
        inheritance_modifier => {
            type: Synthetic,
            token: self,
        },
        mutation_modifier => {
            type: Synthetic,
            token: self,
        },
        getter_specifier => {
            type: Synthetic,
        },
        setter_specifier => {
            type: Synthetic,
            token: self,
        },
        modify_specifier => {
            type: Synthetic,
            token: self,
        },
        _modify => {
            type: Synthetic,
        },
        public => {
            type: Synthetic,
        },
        private => {
            type: Synthetic,
        },
        fileprivate => {
            type: Synthetic,
            token: self,
        },
        internal => {
            type: Synthetic,
        },
        open => {
            type: Synthetic,
            token: self,
        },
        static => {
            type: Synthetic,
        },
        final => {
            type: Synthetic,
        },
        override => {
            type: Synthetic,
            token: self,
        },
        required => {
            type: Synthetic,
            token: self,
        },
        convenience => {
            type: Synthetic,
        },
        lazy => {
            type: Synthetic,
            token: self,
        },
        weak => {
            type: Synthetic,
            token: self,
        },
        unowned => {
            type: Synthetic,
            token: self,
        },
        mutating => {
            type: Synthetic,
        },
        nonmutating => {
            type: Synthetic,
            token: self,
        },
        nonisolated => {
            type: Synthetic,
        },
        dynamic => {
            type: Synthetic,
            token: self,
        },
        indirect => {
            type: Synthetic,
            token: self,
        },
        infix => {
            type: Synthetic,
        },
        prefix => {
            type: Synthetic,
            token: self,
        },
        postfix => {
            type: Synthetic,
            token: self,
        },
        optional => {
            type: Synthetic,
            token: self,
        },
        distributed => {
            type: Synthetic,
        },
        consuming => {
            type: Synthetic,
        },
        borrowing => {
            type: Synthetic,
        },
        inout => {
            type: Synthetic,
        },
        let => {
            type: Synthetic,
        },
        var => {
            type: Synthetic,
        },
        get => {
            type: Synthetic,
        },
        set => {
            type: Synthetic,
            token: self,
        },
        willSet => {
            type: Synthetic,
            token: self,
        },
        didSet => {
            type: Synthetic,
            token: self,
        },
        willset_clause => {
            type: Synthetic,
            token: self,
        },
        didset_clause => {
            type: Synthetic,
        },
        willset_didset_block => {
            type: Block,
            roles: [Body],
        },
        actor => {
            type: Synthetic,
            token: self,
        },
        extension => {
            type: Synthetic,
            token: self,
        },
        some => {
            type: Synthetic,
        },
        any => {
            type: Synthetic,
        },
        each => {
            type: Synthetic,
        },
        where_clause => {
            type: Synthetic,
            token: self,
        },
        where_keyword => {
            type: Synthetic,
        },
        inheritance_specifier => {
            type: Synthetic,
        },
        inheritance_constraint => {
            type: Synthetic,
        },
        equality_constraint => {
            type: Synthetic,
        },
        associatedtype_declaration => {
            type: Synthetic,
            children: ["type_identifier"],
        },
        associatedtype => {
            type: Synthetic,
            token: self,
        },
        availability_condition => {
            type: Synthetic,
        },
        available => {
            type: Synthetic,
            token: self,
        },
        unavailable => {
            type: Synthetic,
        },
        canImport => {
            type: Synthetic,
        },
        swift => {
            type: Synthetic,
        },
        compiler => {
            type: Synthetic,
            token: self,
        },
        os => {
            type: Synthetic,
        },
        arch => {
            type: Synthetic,
            token: self,
        },
        targetEnvironment => {
            type: Synthetic,
        },
        diagnostic => {
            type: Synthetic,
            token: self,
        },
        directive => {
            type: Synthetic,
            token: self,
        },
        macro => {
            type: Synthetic,
        },
        macro_declaration => {
            type: Synthetic,
            token: self,
        },
        macro_definition => {
            type: Synthetic,
        },
        macro_invocation => {
            type: Synthetic,
            token: self,
        },
        external_macro_definition => {
            type: Synthetic,
            token: self,
        },
        externalMacro => {
            type: Synthetic,
        },
        operator_declaration => {
            type: Synthetic,
        },
        deprecated_operator_declaration_body => {
            type: Synthetic,
        },
        operator => {
            type: Synthetic,
        },
        custom_operator => {
            type: Synthetic,
        },
        bang => {
            type: Synthetic,
        },
        package => {
            type: Synthetic,
        },
        directly_assignable_expression => {
            type: Synthetic,
        },
        value_argument => {
            type: Synthetic,
        },
        value_argument_label => {
            type: Synthetic,
            token: self,
        },
        value_arguments => {
            type: Synthetic,
        },
        value_pack_expansion => {
            type: Synthetic,
        },
        statements => {
            type: Synthetic,
        },
        shebang_line => {
            type: Synthetic,
        },
        statement_label => {
            type: Synthetic,
            token: self,
        },
        _expression => {
            type: Synthetic,
            token: self,
        },
        line => {
            type: Synthetic,
            token: self,
        },
        column => {
            type: Synthetic,
            token: self,
        },
        file => {
            type: Synthetic,
            token: self,
        },
        fileID => {
            type: Synthetic,
        },
        filePath => {
            type: Synthetic,
        },
        dsohandle => {
            type: Synthetic,
        },
        u => {
            type: Synthetic,
            token: self,
        },
    }
};
