//! GENERATED by uastmap2rs — transpiled from `tcl.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `tcl` language.
pub static TCL: LanguageMapping = uast_language! {
    name: "tcl",
    extensions: [".tcl"],
    rules: {
        source_file => {
            type: File,
        },
        simple_word => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        quoted_word => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        braced_word => {
            type: Block,
            token: self,
            roles: [Body],
        },
        braced_word_simple => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        command => {
            type: Call,
            token: self,
            roles: [Call],
        },
        procedure => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
        },
        if => {
            type: If,
            token: self,
            roles: [Condition],
        },
        elseif => {
            type: If,
            token: self,
            roles: [Condition],
        },
        else => {
            type: Block,
            token: self,
            roles: [Body],
        },
        while => {
            type: Loop,
            token: self,
            roles: [Loop],
        },
        foreach => {
            type: Loop,
            token: self,
            roles: [Loop],
        },
        set => {
            type: Assignment,
            token: self,
            roles: [Assignment],
        },
        try => {
            type: Try,
            token: self,
            roles: [Try],
        },
        catch => {
            type: Catch,
            token: self,
            roles: [Catch],
        },
        finally => {
            type: Finally,
            token: self,
            roles: [Finally],
        },
        namespace => {
            type: Module,
            token: self,
            roles: [Module],
        },
        variable_substitution => {
            type: Identifier,
            token: self,
            roles: [Reference],
        },
        command_substitution => {
            type: Call,
            token: self,
            roles: [Call],
        },
        expr => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        binop_expr => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
        },
        unary_expr => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
        },
        ternary_expr => {
            type: If,
            token: self,
            roles: [Condition],
        },
        word_list => {
            type: List,
            token: self,
            roles: [Argument],
        },
        arguments => {
            type: List,
            token: self,
            roles: [Parameter],
        },
        argument => {
            type: Parameter,
            token: self,
            roles: [Parameter],
        },
        array_index => {
            type: Index,
            token: self,
            roles: [Index],
        },
        global => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        regexp => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        escaped_character => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
    }
};
