//! GENERATED by uastmap2rs — transpiled from `toml.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `toml` language.
pub static TOML: LanguageMapping = uast_language! {
    name: "toml",
    extensions: [".toml"],
    rules: {
        document => {
            type: File,
        },
        table => {
            type: Dict,
            roles: [Literal],
        },
        inline_table => {
            type: Dict,
            roles: [Literal],
        },
        table_array_element => {
            type: Dict,
            roles: [Literal],
        },
        pair => {
            type: KeyValue,
            roles: [Key, Value],
        },
        array => {
            type: List,
            roles: [Literal],
        },
        bare_key => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        quoted_key => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        dotted_key => {
            type: Identifier,
            roles: [Name],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        integer => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        float => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        boolean => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        local_date => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        local_time => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        local_date_time => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        offset_date_time => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        escape_sequence => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
    }
};
