//! GENERATED by uastmap2rs — transpiled from `typescript.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `typescript` language.
pub static TYPESCRIPT: LanguageMapping = uast_language! {
    name: "typescript",
    extensions: [".ts"],
    rules: {
        program => {
            type: File,
        },
        declaration => {
            type: Synthetic,
        },
        expression => {
            type: Synthetic,
            token: self,
        },
        pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        primary_expression => {
            type: Synthetic,
            token: self,
        },
        primary_type => {
            type: Synthetic,
        },
        statement => {
            type: Synthetic,
            token: self,
        },
        type => {
            type: Synthetic,
        },
        abstract_class_declaration => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["class_body", "decorator", "type_identifier", "type_parameters"],
        },
        abstract_method_signature => {
            type: Method,
            roles: [Function, Declaration, Member],
            children: ["asserts_annotation", "computed_property_name", "formal_parameters", "number", "private_property_identifier", "property_identifier", "string", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        accessibility_modifier => {
            type: Synthetic,
            token: self,
        },
        adding_type_annotation => {
            type: TypeAnnotation,
            roles: [Type],
        },
        ambient_declaration => {
            type: TypeAnnotation,
            token: self,
        },
        arguments => {
            type: Synthetic,
        },
        array => {
            type: List,
            token: self,
        },
        array_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        array_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        arrow_function => {
            type: Lambda,
            roles: [Lambda],
            children: ["asserts_annotation", "expression", "formal_parameters", "identifier", "statement_block", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        as_expression => {
            type: Cast,
            token: self,
        },
        asserts => {
            type: Synthetic,
        },
        asserts_annotation => {
            type: Synthetic,
            token: self,
        },
        assignment_expression => {
            type: Assignment,
            roles: [Assignment],
            children: ["array_pattern", "expression", "identifier", "member_expression", "non_null_expression", "object_pattern", "parenthesized_expression", "subscript_expression", "undefined"],
        },
        assignment_pattern => {
            type: Assignment,
            token: self,
            roles: [Assignment],
            children: ["expression", "pattern"],
        },
        augmented_assignment_expression => {
            type: Assignment,
            roles: [Assignment],
            children: ["expression", "identifier", "member_expression", "non_null_expression", "parenthesized_expression", "subscript_expression"],
        },
        await_expression => {
            type: Await,
            token: self,
            roles: [Await],
        },
        binary_expression => {
            type: BinaryOp,
            token: self,
            roles: [Operator],
            children: ["expression", "in", "instanceof", "private_property_identifier"],
        },
        break_statement => {
            type: Break,
            token: self,
            roles: [Break],
            children: ["statement_identifier"],
        },
        call_expression => {
            type: Call,
            roles: [Call],
            children: ["arguments", "expression", "import", "template_string", "type_arguments"],
        },
        call_signature => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["asserts_annotation", "formal_parameters", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        catch_clause => {
            type: Catch,
            roles: [Catch],
            children: ["array_pattern", "identifier", "object_pattern", "statement_block", "type_annotation"],
        },
        class => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["class_body", "decorator", "type_identifier", "type_parameters"],
        },
        class_body => {
            type: Block,
            roles: [Body],
            children: ["decorator"],
        },
        class_declaration => {
            type: Class,
            token: self,
            roles: [Class, Declaration],
            children: ["class_body", "decorator", "type_identifier", "type_parameters"],
        },
        class_heritage => {
            type: Synthetic,
        },
        class_static_block => {
            type: Block,
            token: self,
            roles: [Body],
            children: ["statement_block"],
        },
        computed_property_name => {
            type: Property,
            roles: [Member],
        },
        conditional_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
            children: ["type"],
        },
        constraint => {
            type: Synthetic,
        },
        construct_signature => {
            type: Struct,
            token: self,
            roles: [Struct, Declaration],
            children: ["formal_parameters", "type_annotation", "type_parameters"],
        },
        constructor_type => {
            type: Struct,
            roles: [Struct, Declaration],
            children: ["formal_parameters", "type", "type_parameters"],
        },
        continue_statement => {
            type: Continue,
            token: self,
            roles: [Continue],
            children: ["statement_identifier"],
        },
        debugger_statement => {
            type: Synthetic,
        },
        decorator => {
            type: Decorator,
            token: self,
            roles: [Attribute],
        },
        default_type => {
            type: Synthetic,
        },
        do_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        else_clause => {
            type: Synthetic,
        },
        empty_statement => {
            type: Synthetic,
            token: self,
        },
        enum_assignment => {
            type: Enum,
            roles: [Enum, Declaration],
            children: ["computed_property_name", "expression", "number", "private_property_identifier", "property_identifier", "string"],
        },
        enum_body => {
            type: Enum,
            token: self,
            roles: [Enum, Declaration],
            children: ["computed_property_name", "number", "private_property_identifier", "property_identifier", "string"],
        },
        enum_declaration => {
            type: Enum,
            roles: [Enum, Declaration],
            children: ["enum_body", "identifier"],
        },
        existential_type => {
            type: TypeAnnotation,
            token: child("identifier"),
            roles: [Type],
        },
        export_clause => {
            type: Synthetic,
        },
        export_specifier => {
            type: Synthetic,
            token: self,
            children: ["identifier", "string"],
        },
        export_statement => {
            type: Synthetic,
            children: ["declaration", "decorator", "expression", "string"],
        },
        expression_statement => {
            type: Synthetic,
            token: self,
        },
        extends_clause => {
            type: Synthetic,
            children: ["expression", "type_arguments"],
        },
        extends_type_clause => {
            type: Synthetic,
            token: self,
            children: ["generic_type", "nested_type_identifier", "type_identifier"],
        },
        finally_clause => {
            type: Finally,
            roles: [Finally],
            children: ["statement_block"],
        },
        flow_maybe_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        for_in_statement => {
            type: Loop,
            roles: [Loop],
            children: ["array_pattern", "const", "expression", "identifier", "in", "let", "member_expression", "non_null_expression", "object_pattern", "of", "parenthesized_expression", "sequence_expression", "statement", "subscript_expression", "undefined", "var"],
        },
        for_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["empty_statement", "expression", "lexical_declaration", "sequence_expression", "statement", "variable_declaration"],
        },
        formal_parameters => {
            type: Parameter,
            roles: [Parameter],
        },
        function_declaration => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["asserts_annotation", "formal_parameters", "identifier", "statement_block", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        function_expression => {
            type: Function,
            roles: [Function, Declaration],
            children: ["asserts_annotation", "formal_parameters", "identifier", "statement_block", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        function_signature => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["asserts_annotation", "formal_parameters", "identifier", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        function_type => {
            type: Function,
            roles: [Function, Declaration],
            children: ["asserts", "formal_parameters", "type", "type_parameters", "type_predicate"],
        },
        generator_function => {
            type: Function,
            token: self,
            roles: [Function, Declaration],
            children: ["asserts_annotation", "formal_parameters", "identifier", "statement_block", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        generator_function_declaration => {
            type: Function,
            roles: [Function, Declaration],
            children: ["asserts_annotation", "formal_parameters", "identifier", "statement_block", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        generic_type => {
            type: TypeAnnotation,
            token: child("identifier"),
            roles: [Type],
            children: ["nested_type_identifier", "type_arguments", "type_identifier"],
        },
        identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        if_statement => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["else_clause", "parenthesized_expression", "statement"],
        },
        implements_clause => {
            type: Synthetic,
        },
        import => {
            type: Import,
            token: self,
            roles: [Import],
        },
        import_alias => {
            type: Import,
            roles: [Import],
        },
        import_attribute => {
            type: Import,
            token: self,
            roles: [Import],
        },
        import_clause => {
            type: Import,
            roles: [Import],
        },
        import_require_clause => {
            type: Import,
            token: self,
            roles: [Import],
            children: ["string"],
        },
        import_specifier => {
            type: Synthetic,
            children: ["identifier", "string"],
        },
        import_statement => {
            type: Import,
            token: self,
            roles: [Import],
            children: ["string"],
        },
        index_signature => {
            type: Index,
            roles: [Index],
            children: ["adding_type_annotation", "identifier", "omitting_type_annotation", "opting_type_annotation", "type", "type_annotation"],
        },
        index_type_query => {
            type: Index,
            token: self,
            roles: [Index],
        },
        infer_type => {
            type: Synthetic,
        },
        instantiation_expression => {
            type: Synthetic,
            token: self,
            children: ["identifier", "import", "member_expression", "subscript_expression", "type_arguments"],
        },
        interface_body => {
            type: Block,
            roles: [Body],
        },
        interface_declaration => {
            type: Interface,
            token: self,
            roles: [Interface, Declaration],
            children: ["interface_body", "type_identifier", "type_parameters"],
        },
        internal_module => {
            type: Module,
            roles: [Module],
            children: ["identifier", "nested_identifier", "statement_block", "string"],
        },
        intersection_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        labeled_statement => {
            type: Synthetic,
            children: ["statement", "statement_identifier"],
        },
        lexical_declaration => {
            type: Synthetic,
            token: self,
            children: ["const", "let"],
        },
        literal_type => {
            type: Literal,
            roles: [Literal],
        },
        lookup_type => {
            type: Synthetic,
            token: self,
        },
        mapped_type_clause => {
            type: Synthetic,
            children: ["type", "type_identifier"],
        },
        member_expression => {
            type: Synthetic,
            token: self,
            children: ["expression", "import", "optional_chain", "private_property_identifier", "property_identifier"],
        },
        meta_property => {
            type: Property,
            roles: [Member],
        },
        method_definition => {
            type: Method,
            token: self,
            roles: [Function, Declaration, Member],
            children: ["asserts_annotation", "computed_property_name", "formal_parameters", "number", "private_property_identifier", "property_identifier", "statement_block", "string", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        method_signature => {
            type: Method,
            roles: [Function, Declaration, Member],
            children: ["asserts_annotation", "computed_property_name", "formal_parameters", "number", "private_property_identifier", "property_identifier", "string", "type_annotation", "type_parameters", "type_predicate_annotation"],
        },
        module => {
            type: Module,
            token: self,
            roles: [Module],
            children: ["identifier", "nested_identifier", "statement_block", "string"],
        },
        named_imports => {
            type: Import,
            roles: [Import],
        },
        namespace_export => {
            type: Namespace,
            token: self,
            roles: [Module],
        },
        namespace_import => {
            type: Import,
            roles: [Import],
        },
        nested_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
            children: ["identifier", "member_expression", "property_identifier"],
        },
        nested_type_identifier => {
            type: TypeAnnotation,
            roles: [Type],
            children: ["identifier", "nested_identifier", "type_identifier"],
        },
        new_expression => {
            type: Call,
            token: self,
            roles: [Call],
            children: ["arguments", "primary_expression", "type_arguments"],
        },
        non_null_expression => {
            type: Synthetic,
        },
        object => {
            type: Dict,
            token: self,
        },
        object_assignment_pattern => {
            type: Assignment,
            roles: [Assignment],
            children: ["array_pattern", "expression", "object_pattern", "shorthand_property_identifier_pattern"],
        },
        object_pattern => {
            type: Pattern,
            token: self,
            roles: [Pattern],
        },
        object_type => {
            type: Synthetic,
        },
        omitting_type_annotation => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        opting_type_annotation => {
            type: TypeAnnotation,
            roles: [Type],
        },
        optional_chain => {
            type: Synthetic,
            token: self,
        },
        optional_parameter => {
            type: Parameter,
            roles: [Parameter],
            children: ["decorator", "expression", "identifier", "pattern", "this", "type_annotation"],
        },
        optional_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        override_modifier => {
            type: Synthetic,
        },
        pair => {
            type: KeyValue,
            token: self,
            roles: [Key, Value],
            children: ["computed_property_name", "expression", "number", "private_property_identifier", "property_identifier", "string"],
        },
        pair_pattern => {
            type: Pattern,
            roles: [Pattern],
            children: ["assignment_pattern", "computed_property_name", "number", "pattern", "private_property_identifier", "property_identifier", "string"],
        },
        parenthesized_expression => {
            type: Synthetic,
            token: self,
            children: ["type_annotation"],
        },
        parenthesized_type => {
            type: Synthetic,
        },
        predefined_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        property_signature => {
            type: Property,
            token: self,
            roles: [Member],
            children: ["computed_property_name", "number", "private_property_identifier", "property_identifier", "string", "type_annotation"],
        },
        public_field_definition => {
            type: Field,
            roles: [Member],
            children: ["computed_property_name", "decorator", "expression", "number", "private_property_identifier", "property_identifier", "string", "type_annotation"],
        },
        readonly_type => {
            type: Synthetic,
            token: self,
        },
        regex => {
            type: Literal,
            roles: [Literal],
            children: ["regex_flags", "regex_pattern"],
        },
        required_parameter => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["decorator", "expression", "identifier", "pattern", "rest_pattern", "this", "type_annotation"],
        },
        rest_pattern => {
            type: Pattern,
            roles: [Pattern],
        },
        rest_type => {
            type: Spread,
            token: self,
            roles: [Spread],
        },
        return_statement => {
            type: Return,
            token: self,
            roles: [Return],
        },
        satisfies_expression => {
            type: Cast,
            token: self,
        },
        sequence_expression => {
            type: Synthetic,
        },
        spread_element => {
            type: Spread,
            token: self,
            roles: [Spread],
        },
        statement_block => {
            type: Block,
            roles: [Body],
        },
        string => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        subscript_expression => {
            type: Index,
            roles: [Index],
            children: ["expression", "number", "optional_chain", "predefined_type", "sequence_expression", "string"],
        },
        switch_body => {
            type: Block,
            token: self,
            roles: [Body],
        },
        switch_case => {
            type: Case,
            roles: [Branch],
            children: ["expression", "sequence_expression", "statement"],
        },
        switch_default => {
            type: Case,
            token: self,
            roles: [Branch],
            children: ["statement"],
        },
        switch_statement => {
            type: Switch,
            children: ["parenthesized_expression", "switch_body"],
        },
        template_literal_type => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        template_string => {
            type: Literal,
            roles: [Literal],
        },
        template_substitution => {
            type: Synthetic,
            token: self,
        },
        template_type => {
            type: Synthetic,
        },
        ternary_expression => {
            type: If,
            token: self,
            roles: [Condition],
            children: ["expression"],
        },
        throw_statement => {
            type: Throw,
            token: self,
            roles: [Throw],
        },
        try_statement => {
            type: Try,
            token: self,
            roles: [Try],
            children: ["catch_clause", "finally_clause", "statement_block"],
        },
        tuple_type => {
            type: Tuple,
        },
        type_alias_declaration => {
            type: TypeAnnotation,
            token: self,
            roles: [Type, Declaration],
            children: ["type", "type_identifier", "type_parameters"],
        },
        type_annotation => {
            type: TypeAnnotation,
            roles: [Type],
        },
        type_arguments => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        type_assertion => {
            type: Cast,
        },
        type_parameter => {
            type: Parameter,
            token: self,
            roles: [Parameter],
            children: ["constraint", "default_type", "type_identifier"],
        },
        type_parameters => {
            type: Parameter,
            roles: [Parameter],
        },
        type_predicate => {
            type: Synthetic,
            token: self,
            children: ["identifier", "this", "type"],
        },
        type_predicate_annotation => {
            type: Synthetic,
        },
        type_query => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        unary_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["delete", "expression", "number", "typeof", "void"],
        },
        union_type => {
            type: TypeAnnotation,
            token: self,
            roles: [Type],
        },
        update_expression => {
            type: UnaryOp,
            token: self,
            roles: [Operator],
            children: ["expression"],
        },
        variable_declaration => {
            type: Variable,
            token: self,
            roles: [Variable, Declaration],
        },
        variable_declarator => {
            type: Variable,
            roles: [Variable, Declaration],
            children: ["array_pattern", "expression", "identifier", "object_pattern", "type_annotation"],
        },
        while_statement => {
            type: Loop,
            token: self,
            roles: [Loop],
            children: ["parenthesized_expression", "statement"],
        },
        with_statement => {
            type: Synthetic,
            children: ["parenthesized_expression", "statement"],
        },
        yield_expression => {
            type: Yield,
            token: self,
            roles: [Yield],
        },
        abstract => {
            type: Synthetic,
        },
        accessor => {
            type: Synthetic,
            token: self,
        },
        any => {
            type: Synthetic,
        },
        as => {
            type: Synthetic,
            token: self,
        },
        assert => {
            type: Synthetic,
        },
        asserts => {
            type: Synthetic,
            token: self,
        },
        async => {
            type: Synthetic,
        },
        await => {
            type: Synthetic,
            token: self,
        },
        boolean => {
            type: Synthetic,
        },
        break => {
            type: Synthetic,
            token: self,
        },
        case => {
            type: Synthetic,
        },
        catch => {
            type: Synthetic,
            token: self,
        },
        class => {
            type: Synthetic,
        },
        comment => {
            type: Comment,
            token: self,
            roles: [Comment],
        },
        const => {
            type: Synthetic,
        },
        continue => {
            type: Synthetic,
            token: self,
        },
        debugger => {
            type: Synthetic,
        },
        declare => {
            type: Synthetic,
            token: self,
        },
        default => {
            type: Synthetic,
        },
        delete => {
            type: Synthetic,
            token: self,
        },
        do => {
            type: Synthetic,
        },
        else => {
            type: Synthetic,
            token: self,
        },
        enum => {
            type: Synthetic,
        },
        escape_sequence => {
            type: Synthetic,
            token: self,
        },
        export => {
            type: Synthetic,
        },
        extends => {
            type: Synthetic,
            token: self,
        },
        false => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        finally => {
            type: Synthetic,
            token: self,
        },
        for => {
            type: Synthetic,
        },
        from => {
            type: Synthetic,
            token: self,
        },
        function => {
            type: Synthetic,
        },
        get => {
            type: Synthetic,
            token: self,
        },
        global => {
            type: Synthetic,
        },
        hash_bang_line => {
            type: Synthetic,
            token: self,
        },
        html_comment => {
            type: Comment,
            roles: [Comment],
        },
        if => {
            type: Synthetic,
            token: self,
        },
        implements => {
            type: Synthetic,
        },
        import => {
            type: Import,
            token: self,
            roles: [Import],
        },
        in => {
            type: Synthetic,
        },
        infer => {
            type: Synthetic,
            token: self,
        },
        instanceof => {
            type: Synthetic,
        },
        interface => {
            type: Synthetic,
            token: self,
        },
        is => {
            type: Synthetic,
        },
        keyof => {
            type: Synthetic,
            token: self,
        },
        let => {
            type: Synthetic,
        },
        meta => {
            type: Synthetic,
            token: self,
        },
        module => {
            type: Synthetic,
        },
        namespace => {
            type: Synthetic,
            token: self,
        },
        never => {
            type: Synthetic,
        },
        new => {
            type: Synthetic,
            token: self,
        },
        null => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        number => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        object => {
            type: Synthetic,
            token: self,
        },
        of => {
            type: Synthetic,
        },
        override => {
            type: Synthetic,
            token: self,
        },
        private => {
            type: Synthetic,
        },
        private_property_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        property_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        protected => {
            type: Synthetic,
            token: self,
        },
        public => {
            type: Synthetic,
        },
        readonly => {
            type: Synthetic,
            token: self,
        },
        regex_flags => {
            type: Synthetic,
        },
        regex_pattern => {
            type: Synthetic,
            token: self,
        },
        require => {
            type: Synthetic,
        },
        return => {
            type: Synthetic,
            token: self,
        },
        satisfies => {
            type: Synthetic,
        },
        set => {
            type: Synthetic,
            token: self,
        },
        shorthand_property_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        shorthand_property_identifier_pattern => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        statement_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        static => {
            type: Synthetic,
            token: self,
        },
        string_fragment => {
            type: Synthetic,
            token: self,
        },
        super => {
            type: Synthetic,
        },
        switch => {
            type: Synthetic,
            token: self,
        },
        symbol => {
            type: Synthetic,
        },
        target => {
            type: Synthetic,
            token: self,
        },
        this => {
            type: Synthetic,
        },
        this_type => {
            type: Synthetic,
            token: self,
        },
        throw => {
            type: Synthetic,
        },
        true => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        try => {
            type: Synthetic,
        },
        type => {
            type: Synthetic,
            token: self,
        },
        type_identifier => {
            type: Identifier,
            token: self,
            roles: [Name],
        },
        typeof => {
            type: Synthetic,
            token: self,
        },
        undefined => {
            type: Literal,
            token: self,
            roles: [Literal],
        },
        unknown => {
            type: Synthetic,
            token: self,
        },
        using => {
            type: Synthetic,
        },
        var => {
            type: Synthetic,
            token: self,
        },
        void => {
            type: Synthetic,
        },
        while => {
            type: Synthetic,
            token: self,
        },
        with => {
            type: Synthetic,
        },
        yield => {
            type: Synthetic,
            token: self,
        },
    }
};
