//! Snapshot tests pinning the exact emitted module text for a synthetic
//! `.uastmap` exercising: default + explicit patterns, every token form, role
//! lists, children, props (including the literal `props:` DSL key, which the
//! parser stores as a regular prop), an extensions-free header, the
//! `--escape-hatch` flag, and the automatic plain-literal fallback for the
//! wildcard rule name `_`.

use std::collections::BTreeSet;

use uastmap2rs::{transpile, Options};

const SYN_DSL: &str = r#"[language "syn", files: "Synfile"]

plain_rule <- (plain_rule) => uast(
    type: "Synthetic"
)

self_tok <- (self_tok) => uast(
    token: "self",
    type: "Identifier",
    roles: "Name", "Variable"
)

child_tok <- (child_tok) => uast(
    token: "child:identifier",
    type: "Function",
    children: "block", "identifier"
)

qualified_type <- (qualified_type package: (package_identifier) @pkg) => uast(
    type: "Synthetic",
    token: "@pkg",
    props: "kind=test",
    custom_prop: "v"
)
"#;

const SYN_EXPECTED: &str = r#"//! GENERATED by uastmap2rs — transpiled from `syn.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.

use cf_uast_mapping::{uast_language, LanguageMapping};

/// Mapping table for the `syn` language.
pub static SYN: LanguageMapping = uast_language! {
    name: "syn",
    extensions: [],
    files: ["Synfile"],
    rules: {
        plain_rule => {
            type: Synthetic,
        },
        self_tok => {
            type: Identifier,
            token: self,
            roles: [Name, Variable],
        },
        child_tok => {
            type: Function,
            token: child("identifier"),
            children: ["block", "identifier"],
        },
        qualified_type ("(qualified_type package: (package_identifier) @pkg)") => {
            type: Synthetic,
            token: capture("pkg"),
            props: { "custom_prop": "v", "props": "kind=test" },
        },
    }
};
"#;

#[test]
fn macro_form_snapshot() {
    let out = transpile(SYN_DSL, "syn.uastmap", &Options::default()).expect("transpiles");
    assert_eq!(out, SYN_EXPECTED);
}

#[test]
fn transpilation_is_idempotent() {
    let opts = Options::default();
    let a = transpile(SYN_DSL, "syn.uastmap", &opts).expect("transpiles");
    let b = transpile(SYN_DSL, "syn.uastmap", &opts).expect("transpiles");
    assert_eq!(a, b, "same input must emit byte-identical output");
}

const HATCH_DSL: &str = r#"[language "syn", extensions: ".syn"]

plain_rule <- (plain_rule) => uast(
    token: "self",
    type: "Identifier",
    roles: "Name"
)
"#;

const HATCH_EXPECTED: &str = r#"//! GENERATED by uastmap2rs — transpiled from `syn.uastmap`. Do not edit by
//! hand; re-run the transpiler and commit its output instead.
//!
//! Plain-literal form (the `uast_language!` escape hatch); rules forcing it:
//! * `plain_rule` — flagged via --escape-hatch.

use cf_uast_mapping::{LanguageMapping, MappingRule, Role, TokenSource, UastType};

/// Mapping table for the `syn` language.
#[rustfmt::skip]
pub static SYN: LanguageMapping = LanguageMapping {
    name: "syn",
    extensions: &[".syn"],
    files: &[],
    rules: &[
        MappingRule {
            name: "plain_rule",
            pattern: "(plain_rule)",
            extends: "",
            uast_type: UastType::Identifier,
            token: TokenSource::SelfText,
            roles: &[Role::Name],
            children: &[],
            props: &[],
            conditions: &[],
        },
    ],
};
"#;

#[test]
fn escape_hatch_flag_emits_plain_rule_literal() {
    let opts = Options {
        escape_hatch: BTreeSet::from(["plain_rule".to_string()]),
    };
    let out = transpile(HATCH_DSL, "syn.uastmap", &opts).expect("transpiles");
    assert_eq!(out, HATCH_EXPECTED);
}

#[test]
fn wildcard_rule_name_falls_back_to_plain_form_automatically() {
    let dsl = "[language \"u\", extensions: \".u\"]\n\n_ <- (_) => uast(\n    type: \"Synthetic\"\n)\n";
    let out = transpile(dsl, "u.uastmap", &Options::default()).expect("transpiles");
    assert!(
        out.contains("//! * `_` — rule name is not a macro identifier."),
        "got:\n{out}"
    );
    assert!(out.contains("name: \"_\""), "got:\n{out}");
    assert!(out.contains("pattern: \"(_)\""), "got:\n{out}");
    assert!(out.contains("uast_type: UastType::Synthetic"), "got:\n{out}");
    // No roles anywhere — the Role import must be omitted (unused-import clean).
    assert!(
        out.contains("use cf_uast_mapping::{LanguageMapping, MappingRule, TokenSource, UastType};"),
        "got:\n{out}"
    );
}

#[test]
fn out_of_vocabulary_type_is_a_hard_error() {
    let dsl = "[language \"u\", extensions: \".u\"]\n\nx <- (x) => uast(\n    type: \"Bogus\"\n)\n";
    let err = transpile(dsl, "u.uastmap", &Options::default()).unwrap_err();
    assert!(err.contains("out-of-vocabulary type"), "got: {err}");
    assert!(err.contains("Bogus"), "error must name the value: {err}");
}
