//! Grammar-conformance gate: for every language whose tree-sitter grammar is
//! WIRED (`cf_uast::languages::get_language` → `Some`), every mapping rule's
//! pattern must compile as a [`tree_sitter::Query`] against that grammar.
//!
//! Because every corpus pattern is the default `"(<name>)"` form, query
//! compilation doubles as the node-kind existence check: a `(kind)` query on an
//! unknown kind fails with "invalid node type". Rules that fail are DEAD — the
//! runtime `PatternMatcher` would error identically, so the lowering's behavior
//! is unchanged — but each must be acknowledged in the allow-list below so new
//! dead rules cannot appear silently.
//!
//! Unwired languages are skipped via an explicit list asserted against
//! `get_language`: wiring a grammar without updating this test fails CI, which
//! forces the new grammar into coverage.

use std::collections::BTreeSet;

/// Languages with NO wired grammar (registry stems). Wiring one of these in
/// `cf-uast/src/languages.rs` makes the assertion below fail until it is
/// removed from this list — at which point its rules join the conformance scope.
const UNWIRED: &[&str] = &[
    "ansible",
    "c_sharp",
    "clojure",
    "commonlisp",
    "crystal",
    "css",
    "csv",
    "dart",
    "dockerfile",
    "dotenv",
    "elixir",
    "elm",
    "fish",
    "fortran",
    "git_config",
    "gosum",
    "gotmpl",
    "gowork",
    "graphql",
    "groovy",
    "haskell",
    "hcl",
    "helm",
    "ini",
    "kotlin",
    "latex",
    "lua",
    "make",
    "markdown",
    "nim",
    "nim_format_string",
    "php",
    "properties",
    "proxima",
    "prql",
    "psv",
    "r",
    "rego",
    "ruby",
    "rust_with_rstml",
    "scala",
    "sql",
    "ssh_config",
    "swift",
    "tcl",
    "zig",
];

/// Dead rules: patterns that do not compile against the WIRED grammar version.
/// Each entry is `(registry stem, rule name)` with the reason. The runtime
/// pattern matcher fails identically for these, so behavior is unchanged; they
/// are findings inherited from the DSL corpus, not regressions.
/// All entries share one category: the rule's node type is not a queryable
/// named kind in the wired grammar version — an ANONYMOUS token (`if`, `else`,
/// `then`, operators…), a HIDDEN `_`-prefixed rule, or a kind from a different
/// grammar revision. The runtime `PatternMatcher` fails compilation for these
/// identically in Go and Rust, so they have never matched anything; they are
/// inherited findings from the DSL corpus, not behavior changes.
const DEAD_RULE_ALLOW_LIST: &[(&str, &str)] = &[
    // bash: 34 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("bash", "until_statement"),
    ("bash", "if"),
    ("bash", "then"),
    ("bash", "elif"),
    ("bash", "else"),
    ("bash", "fi"),
    ("bash", "case"),
    ("bash", "esac"),
    ("bash", "for"),
    ("bash", "in"),
    ("bash", "do"),
    ("bash", "done"),
    ("bash", "while"),
    ("bash", "until"),
    ("bash", "select"),
    ("bash", "function"),
    ("bash", "declare"),
    ("bash", "local"),
    ("bash", "export"),
    ("bash", "readonly"),
    ("bash", "typeset"),
    ("bash", "unset"),
    ("bash", "unsetenv"),
    ("bash", "_primary_expression"),
    ("bash", "_statement"),
    ("bash", "A"),
    ("bash", "K"),
    ("bash", "L"),
    ("bash", "P"),
    ("bash", "Q"),
    ("bash", "U"),
    ("bash", "a"),
    ("bash", "k"),
    ("bash", "u"),
    // c: 73 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("c", "NULL"),
    ("c", "nullptr"),
    ("c", "if"),
    ("c", "else"),
    ("c", "for"),
    ("c", "while"),
    ("c", "do"),
    ("c", "switch"),
    ("c", "case"),
    ("c", "default"),
    ("c", "break"),
    ("c", "continue"),
    ("c", "return"),
    ("c", "goto"),
    ("c", "struct"),
    ("c", "union"),
    ("c", "enum"),
    ("c", "typedef"),
    ("c", "const"),
    ("c", "volatile"),
    ("c", "restrict"),
    ("c", "register"),
    ("c", "static"),
    ("c", "extern"),
    ("c", "inline"),
    ("c", "auto"),
    ("c", "sizeof"),
    ("c", "alignof"),
    ("c", "offsetof"),
    ("c", "asm"),
    ("c", "defined"),
    ("c", "short"),
    ("c", "long"),
    ("c", "signed"),
    ("c", "unsigned"),
    ("c", "thread_local"),
    ("c", "constexpr"),
    ("c", "noreturn"),
    ("c", "_Alignas"),
    ("c", "_Alignof"),
    ("c", "_Atomic"),
    ("c", "_Generic"),
    ("c", "_Nonnull"),
    ("c", "_Noreturn"),
    ("c", "__alignof"),
    ("c", "__alignof__"),
    ("c", "__asm"),
    ("c", "__asm__"),
    ("c", "__attribute"),
    ("c", "__attribute__"),
    ("c", "__based"),
    ("c", "__cdecl"),
    ("c", "__clrcall"),
    ("c", "__declspec"),
    ("c", "__except"),
    ("c", "__extension__"),
    ("c", "__fastcall"),
    ("c", "__finally"),
    ("c", "__forceinline"),
    ("c", "__inline"),
    ("c", "__inline__"),
    ("c", "__leave"),
    ("c", "__restrict__"),
    ("c", "__stdcall"),
    ("c", "__thiscall"),
    ("c", "__thread"),
    ("c", "__try"),
    ("c", "__unaligned"),
    ("c", "__vectorcall"),
    ("c", "__volatile__"),
    ("c", "_alignof"),
    ("c", "_unaligned"),
    ("c", "alignas"),
    // cmake: 2 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("cmake", "ENV"),
    ("cmake", "CACHE"),
    // cpp: 114 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("cpp", "nullptr"),
    ("cpp", "NULL"),
    ("cpp", "explicit_object_parameter_declaration"),
    ("cpp", "if"),
    ("cpp", "else"),
    ("cpp", "for"),
    ("cpp", "while"),
    ("cpp", "do"),
    ("cpp", "switch"),
    ("cpp", "case"),
    ("cpp", "default"),
    ("cpp", "break"),
    ("cpp", "continue"),
    ("cpp", "return"),
    ("cpp", "goto"),
    ("cpp", "try"),
    ("cpp", "catch"),
    ("cpp", "throw"),
    ("cpp", "class"),
    ("cpp", "struct"),
    ("cpp", "union"),
    ("cpp", "enum"),
    ("cpp", "namespace"),
    ("cpp", "template"),
    ("cpp", "typename"),
    ("cpp", "typedef"),
    ("cpp", "using"),
    ("cpp", "new"),
    ("cpp", "delete"),
    ("cpp", "sizeof"),
    ("cpp", "alignof"),
    ("cpp", "offsetof"),
    ("cpp", "operator"),
    ("cpp", "const"),
    ("cpp", "volatile"),
    ("cpp", "mutable"),
    ("cpp", "register"),
    ("cpp", "static"),
    ("cpp", "extern"),
    ("cpp", "inline"),
    ("cpp", "virtual"),
    ("cpp", "explicit"),
    ("cpp", "friend"),
    ("cpp", "public"),
    ("cpp", "protected"),
    ("cpp", "private"),
    ("cpp", "final"),
    ("cpp", "override"),
    ("cpp", "constexpr"),
    ("cpp", "consteval"),
    ("cpp", "constinit"),
    ("cpp", "thread_local"),
    ("cpp", "noreturn"),
    ("cpp", "requires"),
    ("cpp", "concept"),
    ("cpp", "co_await"),
    ("cpp", "co_return"),
    ("cpp", "co_yield"),
    ("cpp", "module"),
    ("cpp", "import"),
    ("cpp", "export"),
    ("cpp", "and"),
    ("cpp", "and_eq"),
    ("cpp", "bitand"),
    ("cpp", "bitor"),
    ("cpp", "compl"),
    ("cpp", "not"),
    ("cpp", "not_eq"),
    ("cpp", "or"),
    ("cpp", "or_eq"),
    ("cpp", "xor"),
    ("cpp", "xor_eq"),
    ("cpp", "defined"),
    ("cpp", "short"),
    ("cpp", "long"),
    ("cpp", "signed"),
    ("cpp", "unsigned"),
    ("cpp", "restrict"),
    ("cpp", "asm"),
    ("cpp", "_Alignas"),
    ("cpp", "_Alignof"),
    ("cpp", "_Atomic"),
    ("cpp", "_Generic"),
    ("cpp", "_Nonnull"),
    ("cpp", "_Noreturn"),
    ("cpp", "_alignof"),
    ("cpp", "_unaligned"),
    ("cpp", "alignas"),
    ("cpp", "__alignof"),
    ("cpp", "__alignof__"),
    ("cpp", "__asm"),
    ("cpp", "__asm__"),
    ("cpp", "__attribute"),
    ("cpp", "__attribute__"),
    ("cpp", "__based"),
    ("cpp", "__cdecl"),
    ("cpp", "__clrcall"),
    ("cpp", "__declspec"),
    ("cpp", "__except"),
    ("cpp", "__extension__"),
    ("cpp", "__fastcall"),
    ("cpp", "__finally"),
    ("cpp", "__forceinline"),
    ("cpp", "__inline"),
    ("cpp", "__inline__"),
    ("cpp", "__leave"),
    ("cpp", "__restrict__"),
    ("cpp", "__stdcall"),
    ("cpp", "__thiscall"),
    ("cpp", "__thread"),
    ("cpp", "__try"),
    ("cpp", "__unaligned"),
    ("cpp", "__vectorcall"),
    ("cpp", "__volatile__"),
    // gitattributes: 11 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("gitattributes", "text"),
    ("gitattributes", "binary"),
    ("gitattributes", "crlf"),
    ("gitattributes", "eol"),
    ("gitattributes", "diff"),
    ("gitattributes", "merge"),
    ("gitattributes", "filter"),
    ("gitattributes", "ident"),
    ("gitattributes", "delta"),
    ("gitattributes", "encoding"),
    ("gitattributes", "whitespace"),
    // gitignore: 12 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("gitignore", "alnum"),
    ("gitignore", "alpha"),
    ("gitignore", "blank"),
    ("gitignore", "cntrl"),
    ("gitignore", "digit"),
    ("gitignore", "graph"),
    ("gitignore", "lower"),
    ("gitignore", "print"),
    ("gitignore", "punct"),
    ("gitignore", "space"),
    ("gitignore", "upper"),
    ("gitignore", "xdigit"),
    // go: 26 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("go", "_type"),
    ("go", "break"),
    ("go", "case"),
    ("go", "chan"),
    ("go", "const"),
    ("go", "continue"),
    ("go", "default"),
    ("go", "defer"),
    ("go", "else"),
    ("go", "fallthrough"),
    ("go", "for"),
    ("go", "func"),
    ("go", "go"),
    ("go", "goto"),
    ("go", "if"),
    ("go", "import"),
    ("go", "interface"),
    ("go", "map"),
    ("go", "package"),
    ("go", "range"),
    ("go", "return"),
    ("go", "select"),
    ("go", "struct"),
    ("go", "switch"),
    ("go", "type"),
    ("go", "var"),
    // java: 58 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("java", "_simple_type"),
    ("java", "abstract"),
    ("java", "assert"),
    ("java", "break"),
    ("java", "byte"),
    ("java", "case"),
    ("java", "catch"),
    ("java", "char"),
    ("java", "class"),
    ("java", "continue"),
    ("java", "default"),
    ("java", "do"),
    ("java", "double"),
    ("java", "else"),
    ("java", "enum"),
    ("java", "exports"),
    ("java", "extends"),
    ("java", "final"),
    ("java", "finally"),
    ("java", "float"),
    ("java", "for"),
    ("java", "if"),
    ("java", "implements"),
    ("java", "import"),
    ("java", "instanceof"),
    ("java", "int"),
    ("java", "interface"),
    ("java", "long"),
    ("java", "module"),
    ("java", "native"),
    ("java", "new"),
    ("java", "open"),
    ("java", "opens"),
    ("java", "package"),
    ("java", "private"),
    ("java", "protected"),
    ("java", "provides"),
    ("java", "public"),
    ("java", "record"),
    ("java", "requires"),
    ("java", "return"),
    ("java", "sealed"),
    ("java", "short"),
    ("java", "static"),
    ("java", "strictfp"),
    ("java", "switch"),
    ("java", "synchronized"),
    ("java", "throw"),
    ("java", "to"),
    ("java", "transient"),
    ("java", "transitive"),
    ("java", "try"),
    ("java", "uses"),
    ("java", "volatile"),
    ("java", "when"),
    ("java", "while"),
    ("java", "with"),
    ("java", "yield"),
    // javascript: 40 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("javascript", "as"),
    ("javascript", "async"),
    ("javascript", "await"),
    ("javascript", "break"),
    ("javascript", "case"),
    ("javascript", "catch"),
    ("javascript", "const"),
    ("javascript", "continue"),
    ("javascript", "debugger"),
    ("javascript", "default"),
    ("javascript", "delete"),
    ("javascript", "do"),
    ("javascript", "else"),
    ("javascript", "export"),
    ("javascript", "extends"),
    ("javascript", "finally"),
    ("javascript", "for"),
    ("javascript", "from"),
    ("javascript", "function"),
    ("javascript", "get"),
    ("javascript", "if"),
    ("javascript", "in"),
    ("javascript", "instanceof"),
    ("javascript", "let"),
    ("javascript", "meta"),
    ("javascript", "new"),
    ("javascript", "of"),
    ("javascript", "return"),
    ("javascript", "set"),
    ("javascript", "static"),
    ("javascript", "switch"),
    ("javascript", "target"),
    ("javascript", "throw"),
    ("javascript", "try"),
    ("javascript", "typeof"),
    ("javascript", "var"),
    ("javascript", "void"),
    ("javascript", "while"),
    ("javascript", "with"),
    ("javascript", "yield"),
    // markdown_inline: 44 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("markdown_inline", "atx_heading"),
    ("markdown_inline", "block_quote"),
    ("markdown_inline", "code_fence_content"),
    ("markdown_inline", "document"),
    ("markdown_inline", "fenced_code_block"),
    ("markdown_inline", "html_block"),
    ("markdown_inline", "indented_code_block"),
    ("markdown_inline", "info_string"),
    ("markdown_inline", "language"),
    ("markdown_inline", "link_reference_definition"),
    ("markdown_inline", "list"),
    ("markdown_inline", "list_item"),
    ("markdown_inline", "list_marker_dot"),
    ("markdown_inline", "list_marker_minus"),
    ("markdown_inline", "list_marker_parenthesis"),
    ("markdown_inline", "list_marker_plus"),
    ("markdown_inline", "list_marker_star"),
    ("markdown_inline", "paragraph"),
    ("markdown_inline", "pipe_table"),
    ("markdown_inline", "pipe_table_cell"),
    ("markdown_inline", "pipe_table_delimiter_cell"),
    ("markdown_inline", "pipe_table_delimiter_row"),
    ("markdown_inline", "pipe_table_header"),
    ("markdown_inline", "pipe_table_row"),
    ("markdown_inline", "section"),
    ("markdown_inline", "setext_heading"),
    ("markdown_inline", "task_list_marker_checked"),
    ("markdown_inline", "task_list_marker_unchecked"),
    ("markdown_inline", "thematic_break"),
    ("markdown_inline", "atx_h1_marker"),
    ("markdown_inline", "atx_h2_marker"),
    ("markdown_inline", "atx_h3_marker"),
    ("markdown_inline", "atx_h4_marker"),
    ("markdown_inline", "atx_h5_marker"),
    ("markdown_inline", "atx_h6_marker"),
    ("markdown_inline", "block_continuation"),
    ("markdown_inline", "block_quote_marker"),
    ("markdown_inline", "fenced_code_block_delimiter"),
    ("markdown_inline", "minus_metadata"),
    ("markdown_inline", "pipe_table_align_left"),
    ("markdown_inline", "pipe_table_align_right"),
    ("markdown_inline", "plus_metadata"),
    ("markdown_inline", "setext_h1_underline"),
    ("markdown_inline", "setext_h2_underline"),
    // perl: 4 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("perl", "require_statement"),
    ("perl", "foreach_statement"),
    ("perl", "while_statement"),
    ("perl", "until_statement"),
    // proto: 23 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("proto", "returns"),
    ("proto", "stream"),
    ("proto", "optional"),
    ("proto", "repeated"),
    ("proto", "required"),
    ("proto", "public"),
    ("proto", "weak"),
    ("proto", "to"),
    ("proto", "max"),
    ("proto", "map"),
    ("proto", "int32"),
    ("proto", "int64"),
    ("proto", "uint32"),
    ("proto", "uint64"),
    ("proto", "sint32"),
    ("proto", "sint64"),
    ("proto", "fixed32"),
    ("proto", "fixed64"),
    ("proto", "sfixed32"),
    ("proto", "sfixed64"),
    ("proto", "float"),
    ("proto", "double"),
    ("proto", "bytes"),
    // python: 36 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("python", "_compound_statement"),
    ("python", "_simple_statement"),
    ("python", "__future__"),
    ("python", "and"),
    ("python", "as"),
    ("python", "assert"),
    ("python", "async"),
    ("python", "break"),
    ("python", "case"),
    ("python", "class"),
    ("python", "continue"),
    ("python", "def"),
    ("python", "del"),
    ("python", "elif"),
    ("python", "else"),
    ("python", "except"),
    ("python", "exec"),
    ("python", "finally"),
    ("python", "for"),
    ("python", "from"),
    ("python", "global"),
    ("python", "if"),
    ("python", "import"),
    ("python", "in"),
    ("python", "is"),
    ("python", "match"),
    ("python", "nonlocal"),
    ("python", "not"),
    ("python", "or"),
    ("python", "pass"),
    ("python", "print"),
    ("python", "raise"),
    ("python", "return"),
    ("python", "try"),
    ("python", "while"),
    ("python", "with"),
    // rust: 53 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("rust", "_declaration_statement"),
    ("rust", "as"),
    ("rust", "async"),
    ("rust", "await"),
    ("rust", "break"),
    ("rust", "const"),
    ("rust", "continue"),
    ("rust", "default"),
    ("rust", "dyn"),
    ("rust", "else"),
    ("rust", "enum"),
    ("rust", "expr"),
    ("rust", "expr_2021"),
    ("rust", "extern"),
    ("rust", "false"),
    ("rust", "fn"),
    ("rust", "for"),
    ("rust", "gen"),
    ("rust", "ident"),
    ("rust", "if"),
    ("rust", "impl"),
    ("rust", "in"),
    ("rust", "item"),
    ("rust", "let"),
    ("rust", "literal"),
    ("rust", "loop"),
    ("rust", "match"),
    ("rust", "meta"),
    ("rust", "mod"),
    ("rust", "move"),
    ("rust", "pat"),
    ("rust", "pat_param"),
    ("rust", "path"),
    ("rust", "pub"),
    ("rust", "raw"),
    ("rust", "ref"),
    ("rust", "return"),
    ("rust", "static"),
    ("rust", "stmt"),
    ("rust", "struct"),
    ("rust", "trait"),
    ("rust", "true"),
    ("rust", "try"),
    ("rust", "tt"),
    ("rust", "ty"),
    ("rust", "type"),
    ("rust", "union"),
    ("rust", "unsafe"),
    ("rust", "use"),
    ("rust", "vis"),
    ("rust", "where"),
    ("rust", "while"),
    ("rust", "yield"),
    // tsx: 67 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("tsx", "type_assertion"),
    ("tsx", "jsx_fragment"),
    ("tsx", "abstract"),
    ("tsx", "accessor"),
    ("tsx", "any"),
    ("tsx", "as"),
    ("tsx", "assert"),
    ("tsx", "async"),
    ("tsx", "await"),
    ("tsx", "boolean"),
    ("tsx", "break"),
    ("tsx", "case"),
    ("tsx", "catch"),
    ("tsx", "const"),
    ("tsx", "continue"),
    ("tsx", "debugger"),
    ("tsx", "declare"),
    ("tsx", "default"),
    ("tsx", "delete"),
    ("tsx", "do"),
    ("tsx", "else"),
    ("tsx", "enum"),
    ("tsx", "export"),
    ("tsx", "extends"),
    ("tsx", "finally"),
    ("tsx", "for"),
    ("tsx", "from"),
    ("tsx", "function"),
    ("tsx", "get"),
    ("tsx", "global"),
    ("tsx", "if"),
    ("tsx", "implements"),
    ("tsx", "in"),
    ("tsx", "infer"),
    ("tsx", "instanceof"),
    ("tsx", "interface"),
    ("tsx", "is"),
    ("tsx", "keyof"),
    ("tsx", "let"),
    ("tsx", "meta"),
    ("tsx", "namespace"),
    ("tsx", "never"),
    ("tsx", "new"),
    ("tsx", "of"),
    ("tsx", "override"),
    ("tsx", "private"),
    ("tsx", "protected"),
    ("tsx", "public"),
    ("tsx", "readonly"),
    ("tsx", "require"),
    ("tsx", "return"),
    ("tsx", "satisfies"),
    ("tsx", "set"),
    ("tsx", "static"),
    ("tsx", "switch"),
    ("tsx", "symbol"),
    ("tsx", "target"),
    ("tsx", "throw"),
    ("tsx", "try"),
    ("tsx", "typeof"),
    ("tsx", "unknown"),
    ("tsx", "using"),
    ("tsx", "var"),
    ("tsx", "void"),
    ("tsx", "while"),
    ("tsx", "with"),
    ("tsx", "yield"),
    // typescript: 65 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("typescript", "abstract"),
    ("typescript", "accessor"),
    ("typescript", "any"),
    ("typescript", "as"),
    ("typescript", "assert"),
    ("typescript", "async"),
    ("typescript", "await"),
    ("typescript", "boolean"),
    ("typescript", "break"),
    ("typescript", "case"),
    ("typescript", "catch"),
    ("typescript", "const"),
    ("typescript", "continue"),
    ("typescript", "debugger"),
    ("typescript", "declare"),
    ("typescript", "default"),
    ("typescript", "delete"),
    ("typescript", "do"),
    ("typescript", "else"),
    ("typescript", "enum"),
    ("typescript", "export"),
    ("typescript", "extends"),
    ("typescript", "finally"),
    ("typescript", "for"),
    ("typescript", "from"),
    ("typescript", "function"),
    ("typescript", "get"),
    ("typescript", "global"),
    ("typescript", "if"),
    ("typescript", "implements"),
    ("typescript", "in"),
    ("typescript", "infer"),
    ("typescript", "instanceof"),
    ("typescript", "interface"),
    ("typescript", "is"),
    ("typescript", "keyof"),
    ("typescript", "let"),
    ("typescript", "meta"),
    ("typescript", "namespace"),
    ("typescript", "never"),
    ("typescript", "new"),
    ("typescript", "of"),
    ("typescript", "override"),
    ("typescript", "private"),
    ("typescript", "protected"),
    ("typescript", "public"),
    ("typescript", "readonly"),
    ("typescript", "require"),
    ("typescript", "return"),
    ("typescript", "satisfies"),
    ("typescript", "set"),
    ("typescript", "static"),
    ("typescript", "switch"),
    ("typescript", "symbol"),
    ("typescript", "target"),
    ("typescript", "throw"),
    ("typescript", "try"),
    ("typescript", "typeof"),
    ("typescript", "unknown"),
    ("typescript", "using"),
    ("typescript", "var"),
    ("typescript", "void"),
    ("typescript", "while"),
    ("typescript", "with"),
    ("typescript", "yield"),
    // xml: 17 dead rules (anonymous-token / hidden-rule / version-drift kinds).
    ("xml", "ANY"),
    ("xml", "EMPTY"),
    ("xml", "ATTLIST"),
    ("xml", "CDATA"),
    ("xml", "DOCTYPE"),
    ("xml", "ELEMENT"),
    ("xml", "ENTITY"),
    ("xml", "NDATA"),
    ("xml", "NOTATION"),
    ("xml", "PUBLIC"),
    ("xml", "SYSTEM"),
    ("xml", "encoding"),
    ("xml", "standalone"),
    ("xml", "version"),
    ("xml", "xml"),
    ("xml", "yes"),
    ("xml", "no"),
];

#[test]
fn unwired_list_matches_get_language() {
    for (stem, _) in cf_uast_mappings::ALL {
        let wired = cf_uast::languages::get_language(stem).is_some();
        let listed = UNWIRED.contains(stem);
        assert!(
            wired != listed,
            "{stem}: wired={wired} but unwired-listed={listed} — update UNWIRED"
        );
    }
    // No stale entries for languages that do not exist at all.
    let stems: BTreeSet<&str> = cf_uast_mappings::ALL.iter().map(|(s, _)| *s).collect();
    for u in UNWIRED {
        assert!(
            stems.contains(u),
            "UNWIRED entry {u} is not a known language"
        );
    }
}

#[test]
fn every_pattern_compiles_on_wired_grammars() {
    let allow: BTreeSet<(&str, &str)> = DEAD_RULE_ALLOW_LIST.iter().copied().collect();
    let mut checked = 0usize;
    let mut failures: Vec<String> = Vec::new();
    for (stem, mapping) in cf_uast_mappings::ALL {
        let Some(lang) = cf_uast::languages::get_language(stem) else {
            continue;
        };
        for rule in mapping.rules {
            checked += 1;
            match tree_sitter::Query::new(&lang, rule.pattern) {
                Ok(_) => {
                    assert!(
                        !allow.contains(&(*stem, rule.name)),
                        "{stem}/{}: allow-listed rule now compiles — remove the entry",
                        rule.name
                    );
                }
                Err(e) if allow.contains(&(*stem, rule.name)) => {
                    let _ = e; // acknowledged dead rule.
                }
                Err(e) => {
                    failures.push(format!(
                        "{stem}/{}: pattern {:?}: {e}",
                        rule.name, rule.pattern
                    ));
                }
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} non-allow-listed pattern failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
    assert!(
        checked > 1_000,
        "only {checked} rules checked — wiring regressed?"
    );
}
